- server/polar/config.py
Hey,
This small PR is to adjust enums to explicitly say they are string based and removed duplicate when initializing at the bottom.
> Remove duplicate and make str enums in config

- server/polar/pledge/schemas.py
- server/polar/pledge/service.py
Add state check to all states (except chargebacks).
Unify APIs and throw if pledge or payment is not found.
> server/pledge: stricter transition state checking

- clients/apps/web/src/components/Settings/Badge/Repositories.tsx
- clients/apps/web/src/stories/BadgeRepositories.stories.ts
It's a bit of a compromize, but this makes sure that the list never can be empty.
> clients/settings: show private repositories again

- clients/packages/polarkit/src/components/Badge.tsx
Removed padding/margin and instead made the shadow shorter and with less blur so that it doesn't get cut off on the sides.
Closes #539
> Align badge with text in pull request

- clients/apps/web/package.json
- clients/apps/web/src/components/UI/Toast/Toaster.tsx
- clients/apps/web/src/components/UI/Toast/index.tsx
- clients/apps/web/src/components/UI/Toast/use-toast.ts
- clients/apps/web/src/pages/_app.tsx
- clients/apps/web/tailwind.config.js
- clients/pnpm-lock.yaml
Based on https://ui.shadcn.com/docs/components/toast, tweaked to fit our styling, needs and environment. Adds the `tailwindcss-animate` plugin, which seems pretty handy for intro/exit animations. Available variants are `default`, `success` and `error`.
**Usage**
```
import { ToastAction } from "@/components/UI/Toast"
import { useToast } from "@/components/UI/Toast/use-toast"
export function ToastWithAction() {
const { toast } = useToast()
return (
<button
onClick={() => {
toast({
title: "Uh oh! Something went wrong.",
description: "There was a problem with your request.",
action: <ToastAction altText="Try again">Try again</ToastAction>,
variant: "error"
})
}}
>
Show Toast
</button>
)
}
```
**Demo**
https://github.com/polarsource/polar/assets/1426460/13e922bf-fc24-41bb-86bb-8d86d7885b4d …
> Add toast component

- clients/apps/web/src/stories/IssueListItem.stories.ts
- clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx
- Show status of all pledges
- Ablity to dispute all pledges (if same user has made multiple pledges)
- Show "Pending payout" message when the dispute window has passed, but the transfer has not yet happened
> clients/IssueListItemDecoration: show multiple pledge statuses

- clients/apps/web/src/stories/BadgeRepositories.stories.ts
This components uses a lot of animations which is hard to test reliably with chromatic
> clients/stories: disable BadgeRepositories in chromatic

- server/polar/dashboard/endpoints.py
- server/polar/issue/service.py
Only assigning an issue will count as triaged from now. Having a label will not count as triaged.
Fixes #549
> server/dashboard: change Triaged definition

- clients/apps/web/src/components/Dashboard/Gatekeeper/Gatekeeper.tsx
- clients/apps/web/src/pages/dashboard/initialize/[organization]/index.tsx
- clients/apps/web/src/pages/dashboard/settings/[organization]/index.tsx
- clients/apps/web/src/pages/dashboard/settings/extension.tsx
- clients/apps/web/src/pages/dashboard/settings/index.tsx
If the app has a user in localStorage, but the cookie is invalid or missing, reload the user fully, and ask the user to login.
Fixes #589
> clients/web/Gatekeeper: lazily check and verify auth

- clients/apps/web/tsconfig.json
Spotted this when trying to improve the suggested import paths by vscode in the monorepo
> client/web: stricter tsconfig import paths

- server/poetry.lock
- server/pyproject.toml
This version contains everything that we had previously patched in our own fork
> server/githubkit: update to upstream 0.10.4

- server/polar/integrations/github/service/reference.py
> Don't crash on ValidationError in githubkit when annotating references

- server/polar/integrations/github/service/api.py
- server/polar/integrations/github/service/issue.py
- server/polar/integrations/github/tasks/issue.py
- server/polar/organization/service.py
If we're rate limited to less than 1000 requests left for an org, don't run the two cron:ed crawl jobs for those orgs.
Do this instead of trying to be smarted about how to crawl, as #674 tried.
Fixes #654
Closes #674
> Don't crawl stuff if rate limit is low

- clients/apps/web/src/pages/github/installation.tsx
Fix #690 
Once the admin installs the app, they will be given access as expected, but not the member requesting it. In part because Github doesn't offer a way to get requestors after the fact: https://github.com/orgs/community/discussions/42351
However, we will build Team Management soon which will allow admins to invite team members.
> Handle Github App installation requests

- clients/apps/web/src/components/Dashboard/Gatekeeper/Gatekeeper.tsx
- clients/apps/web/src/hooks/auth.ts
- clients/apps/web/src/pages/dashboard/settings/[organization]/index.tsx
- clients/packages/polarkit/src/store/userContext.ts
Fix #633
Move hydration check to useAuth. Thereby allowing Gatekeeper to use useRequireAuth and
automatically redirect unauthenticated users appropriately.
- clients/web: Gatekeeper to require auth + centralize auth hydration fix
- clients/polarkit: Remove unused logout callback handler
- clients/web: useRequireAuth always run clientside – no need to check
> Redirect to login on unauthenticated

- server/polar/integrations/github/client.py
- server/polar/integrations/github/service/dependency.py
- server/dependency: Abort early in creating issue dependencies
- server/dependency: Get existing repository without raising exception (Sentry)
- server/dependency: Get or create dependency issue vs. always upsert
- server/dependency: Move get_or_create actions to seperate methods
> Fix exception with dependency detection

- server/polar/issue/service.py
- server/tests/issue/test_service.py
Only use `not_` for statuses that have precedence.
> server/dashboard: fixed query for issue statuses

- server/polar/integrations/github/service/url.py
- server/tests/integrations/github/service/test_url.py
Previously a str like "https://gitlab.com/abc/abc/-/commit/deadbeef#6d123_452" would be matched as: org=commit, repo=deadbeef, number=6.
This change disallows the number segment to be followed by a-z.
Also splits the regexp into two to make it easier to read.
> server/github: stricter dependency regexps

- server/polar/integrations/github/badge.py
- server/tests/integrations/github/test_badge.py
Without this, GitHub links to the image and not to the pledge page
Fixes #778
> server/badge: add newline between <a> and <picture>

- server/README.md
I wanted to just see if I could get the tests running and noticed `docker compose` commands were failing:
```bash
$ docker compose up -d
WARN[0000] The "POLAR_REDIS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_REDIS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_USER" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_PWD" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "POLAR_POSTGRES_PORT" variable is …
```
> fix: re-order commands

- clients/apps/web/src/components/Shared/Topbar.tsx
- clients/apps/web/src/pages/new.tsx
Fixing a few "styling" bugs on the polar.new page, such as missing margins, page padding, and no Polar logo on mobile. Also updated the copy to be a bit clearer.
Solves #793
> Fix styling bugs on polar.new page

- clients/apps/web/src/components/Layout/DashboardLayout.tsx
Let's use the space.
Before:
After:
Solves #796
> Wider issue list on large screens

- server/polar/integrations/github/tasks/webhook.py
We have this information in the webhook, no need to try to detect it ourselves.
This fixes a race condition where it was possible for the badge to not get embedded if we had already updated the issue from somewhere else.
> server/badge: add/remove based on what label changed

- clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/index.tsx
- clients/packages/polarkit/src/api/client/index.ts
- clients/packages/polarkit/src/api/client/models/IssueResources.ts
- clients/packages/polarkit/src/api/client/services/IssuesService.ts
- clients/packages/polarkit/src/api/client/services/PledgesService.ts
- server/polar/issue/endpoints.py
- server/polar/pledge/endpoints.py
We used one endpoint for two jobs which got messy & confusing + caused 404 on the issue pledge page.
**Issue page**: E.g _polar.sh/polarsource/polar/issues/123_
- Get internal resources OR sync them from Github (supporting polar.new)
- Does not include `pledge` and has a different type (new)
**Status page**: E.g post pledge completion
- Get internal resources only. No need to potentially sync from Github in such cases.
- Does include `pledge` resource & requires it
> Fix pledge 404

- clients/apps/web/src/components/Shared/DashboardTopbar.tsx
- clients/apps/web/src/pages/settings/[organization]/index.tsx
- clients/apps/web/src/pages/settings/index.tsx
Not moving the extensions token page for now, as it's referenced by the chrome extension.
> clients/settings: move /dashboard/settings to /settings

- clients/packages/polarkit/src/config.ts
Except Gibraltar since Stripe Transfers is not available there currently
which we need in order to transfer funds from Polar to users connected
Express accounts.
> stripe: Add all countries

- server/polar/integrations/github/service/reference.py
Sufficient messages received to debug this properly for a fix.
> server/github: Remove logging of validation error (spare log)

- server/poetry.lock
- server/pyproject.toml
4.6.0 is causing connection leakage with arq and eventually the pool to
run out. Need to investigate before we upgrade. Until then, let's make
sure we don't run into this again by accident.
+redis = "4.5.5"
+types-redis = "4.5.5.2"
> server: Use fixed version of redis (4.5.5)

- clients/packages/polarkit/src/api/client/PolarAPI.ts
- clients/packages/polarkit/src/api/client/core/OpenAPI.ts
- clients/packages/polarkit/src/api/client/services/DashboardService.ts
- server/polar/dashboard/endpoints.py
- server/tests/dashboard/test_endpoints.py
Adds a filter to the (private) dashboard API to allow filtering by badged status.
Part of #903
> server/dashboard: filter by badged

- clients/apps/web/src/components/Pledge/PledgeForm.tsx
- clients/packages/polarkit/src/api/client/services/IssuesService.ts
- clients/packages/polarkit/src/api/client/services/PledgesService.ts
- server/polar/pledge/endpoints.py
- server/polar/pledge/service.py
* Remove email validation on the client, the only requirement is that the email address must contain `@`
* Gracefully handle Stripe validation errors (on both backend and frontend), for cases such as when the email is invalid according to Stripe.
Fixes #915
> Remove email validation

- server/polar/auth/dependencies.py
- server/polar/organization/endpoints.py
- server/tests/organization/test_endpoints.py
- server/auth: Rename current user dependencies
- api/organization: Raise HTTP 404 w/o proper permissions
> api/organization: Support authentication by org id

- clients/apps/web/src/components/Onboarding/OnboardingConnectPersonalDashboard.tsx
- clients/apps/web/src/components/Onboarding/OnboardingConnectReposToGetStarted.tsx
- clients/apps/web/src/pages/feed.tsx
- clients/apps/web/src/stories/OnboardingConnectDashboard.stories.ts
Recycling components from the previous website design.
Temporary workaround for #981
> clients/feed: add onboarding splash if user have no pledges

- clients/apps/web/src/components/Dashboard/IssueList.tsx
- clients/apps/web/src/components/Dashboard/MaintainerRepoSelection.tsx
- clients/apps/web/src/components/Dropdown/index.tsx
- clients/apps/web/src/components/Layout/DashboardLayout.tsx
- clients/apps/web/src/components/Organization/RepoSelection.tsx
Removed blur on small devices, split the search/filters on three rows.
> clients/issues: responsive header

- server/polar/integrations/github/service/reference.py
The event field seems to be the only field that is always there
> server/references: catch all only event

- server/polar/app.py
- server/polar/worker.py
- server/tests/integrations/github/tasks/test_integration.py
- server/tests/integrations/github/tasks/test_webhook.py
- server/tests/issue/test_endpoints.py
- server/tests/notifications/test_pledge_notifications.py
- server/tests/reward/test_endpoints.py
We've previously relied on the GC to cleanup old arq pool objects and redis connections. With this we're using FastAPI and ARQ lifespans themselves to manage the pool for us.
This updates #873, and should allow us to update the redis library.
> server/worker: reuse arq pool

- clients/apps/web/src/app/(backer)/feed/page.tsx
- clients/apps/web/src/components/Onboarding/OnboardingConnectReposToGetStarted.tsx
> clients/feed: fix onboarding splash

- server/poetry.toml
Following what we discussed on Discord, here is a small config file to tell Poetry to always create the virtual environment in the workspace folder.
This way, it's directly in line with our VS Code config.
Ref: https://python-poetry.org/docs/configuration/#local-configuration
> server/dx: add a Poetry config to create venv in project

- clients/apps/web/src/components/Organization/Header.tsx
- clients/apps/web/src/components/Shared/Topbar.tsx
Using <Link> breaks the site when deployed to Vercel.
Fixes #1062
> clients: link to / with <a>

- server/poetry.lock
- server/polar/app.py
- server/polar/postgres.py
- server/pyproject.toml
- server/tests/account/test_endpoints.py
- server/tests/dashboard/test_endpoints.py
- server/tests/issue/test_endpoints.py
- server/tests/notifications/test_endpoints.py
- server/tests/organization/test_endpoints.py
- server/tests/personal_access_token/test_endpoints.py
- server/tests/pledge/test_endpoints.py
- server/tests/repository/test_endpoints.py
- server/tests/reward/test_endpoints.py
- server/tests/user/test_endpoints.py
Fix #1140
The actual code change is quite short.
However, there are a big bulk of changes in tests, because we need to use the common test client fixture, which overrides the DB session dependency.
> server/dx: instantiate DB engine in lifespan handler

- server/tests/fixtures/base.py
- server/tests/fixtures/database.py
- server/tests/fixtures/predictable_objects.py
- server/tests/integrations/github/tasks/test_webhook.py
This is a revamping of the database fixtures so they behave like the following:
* Database initialization `initialize_test_database` is done only once for the test session
* A session fixture is generated for each test.
* Under the hood, we start a transaction that we rollback at the end.
* This way, each test starts with a fresh DB, without garbage from previous tests
Then, we make sure in the FastAPI test to override `get_db_session` so it returns this test session.
This allows us to get rid of the `initialize_test_database_function` fixture.
It's worth to note that isolation is still not complete: worker tasks are implemented so they generate a DB session from the global session maker, `AsyncSessionLocal`.
In a follow-up improvement, it could be worth to include the session maker …
> server/dx: improve unit tests isolation

- server/polar/reward/service.py
- server/tests/reward/test_service.py
Prevents the test `test_list_rewards_to_user` to be flaky (the DB was not always returningt the Pledges in the same order)
> server/reward: set an order_by clause to RewardService.list

- clients/.vscode/settings.json
- polar.code-workspace
- server/.vscode/extensions.json
- server/.vscode/settings.json
Various upgrades of VS Code settings to keep a nice and productive dev environment.
* Built-in Python linting has been deprecated by VS Code in favor of extensions, in particular for Black.
* Switch to the official mypy extension instead of `matangover.mypy`
* ⚠️ This means you'll need to install a new recommended extension
* Set the Python interpreter globally on the Code Workspace
* Makes Ruff actually working
* Prevents annoying "Invalid Python interpreter selected" warning when switching to `clients` folder
> dx: tweak VS Code settings

- server/run_worker.py
> server/dx: fix ARQ logging configuration override to not swallow its logs

- clients/apps/web/src/app/login/magic-link/authenticate/page.tsx
Yet another difference of behavior between dev and production build of Next.js 🙄
> clients/web: fix magic link authenticate page redirecting even if the token was there

- server/polar/email/email_templates/base.html
- server/tests/magic_link/testdata/magic_link.html
- server/tests/notifications/testdata/test_MaintainerPledgeConfirmationPendingdNotification_no_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgeConfirmationPendingdNotification_with_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_no_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_with_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgePaidNotification.html
- server/tests/notifications/testdata/test_MaintainerPledgePendingdNotification_no_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgePendingdNotification_with_stripe.html
- server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification.html
- server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification_with_account.html
- server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification.html
- server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification_with_account.html
- server/tests/notifications/testdata/test_PledgerPledgePendingNotification.html
- server/tests/notifications/testdata/test_RewardPaidNotification.html
Fix #1175.
Fun fact: if there is a single syntax error in your CSS, Gmail discards it entirely!
> server/email: fix email layout not working on Gmail

- server/polar/worker.py
- server/tests/integrations/github/tasks/test_integration.py
We had to move out the `on_job_start`/`on_job_end` approach.
Unfortunately, we don't have access to task arguments in this hook.
This prevents us to implement things like common arguments handling,
as we do for `request_correlation_id`.
To circumvent this limitation, we implement this behavior
through the `task_hooks` decorator.
> server/dx: implement `request_correlation_id` in tasks logs

- clients/apps/web/src/components/Pledge/Status.tsx
- clients/apps/web/src/components/Pledge/ThankYouUpsell.tsx
- clients/apps/web/src/components/Shared/GithubLoginButton.tsx
- clients/packages/polarkit/src/api/client/models/OAuthAccountRead.ts
- clients/packages/polarkit/src/api/client/models/UserRead.ts
- clients/packages/polarkit/src/api/client/services/IntegrationsService.ts
- server/polar/integrations/github/endpoints.py
- server/polar/pledge/service.py
Change to use the payment_intent_id as the connection token, as it's only known to the pledger, and never known to the public.
All github login buttons on a page with payment_intent_id in the search params automatically forwards the token.
Fixes #1128
> clients/pledge: connect pledge after login

- server/scripts/anonymous_pledge_migration.py
Here is what the script does:
* List all anonymous Pledge (i.e. `Pledge.by_user_id IS NULL`) that are at least `created` (i.e. ignore `initiated` state)
* For each of them:
* Validate the email address (we have some invalid ones in the DB). If the email is invalid, do nothing
* Get or create a user account with this email address
* Set `by_user_id` property on the pledge
---
There is a `--dry-run` option to make sure the actions are correct before proceeding.
---
I share privately here for Polar team the dry run I obtained by running it on a dump of the production DB: https://drive.google.com/file/d/1oMjKJUASG3N6c0ZBnGYuSAB9zBYlAKrO/view?usp=drive_link
> server/scripts: migration to link anonymous pledges to users

- clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge-injected.svg/route.tsx
- clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx
- clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
- clients/apps/web/src/components/Onboarding/OnboardingAddDependency.tsx
- clients/apps/web/src/components/Settings/FakePullRequest.tsx
- clients/apps/web/src/stories/FinancePage.stories.tsx
- clients/apps/web/src/stories/PledgeBadge.stories.tsx
- clients/apps/web/src/stories/testdata.ts
- clients/packages/polarkit/src/api/client/models/Organization.ts
- clients/packages/polarkit/src/components/badge/Badge.tsx
- server/polar/authz/service.py
- server/polar/backoffice/endpoints.py
- server/polar/backoffice/schemas.py
- server/polar/organization/schemas.py
- server/polar/pledge/endpoints.py
- server/polar/pledge/schemas.py
- server/polar/reward/endpoints.py
- server/tests/authz/test_service.py
- server/tests/pledge/test_endpoints.py
* Changes `Pledges` to be **public**. Some fields (refunded_at, scheduled_payout_at, hosted_invoice_url) are only shown to users with write access to the pledge.
* Added `pledge_badge_show_amount` to the public `Organization` object
* Show avatars of pledgers (max 4 shown) in the SVG badge
> Badge: show avatars of pledgers

- server/polar/account/endpoints.py
- server/polar/auth/dependencies.py
- server/polar/dashboard/endpoints.py
- server/polar/eventstream/endpoints.py
- server/polar/integrations/github/endpoints.py
- server/polar/issue/endpoints.py
- server/polar/notifications/endpoints.py
- server/polar/organization/endpoints.py
- server/polar/payment_method/endpoints.py
- server/polar/personal_access_token/endpoints.py
- server/polar/pledge/endpoints.py
- server/polar/repository/endpoints.py
- server/polar/reward/endpoints.py
- server/polar/user/endpoints.py
I was a bit annoyed by the fact that `Auth.current_user` would return us a class instance typed with an optional user (`User | None`), while we *know* by using this constructor that the user is there and not `None`.
So, I've played a bit with typing and the new fancy [`Annotated` approach](https://fastapi.tiangolo.com/tutorial/dependencies/#share-annotated-dependencies) to help us improve this.
I've implemented this in a single endpoint for now. As we see, it helps us get rid of unneeded `if not auth.user` checks.
I would very like your feedback on this, @zegl, before generalizing it.
> server/dx: improve typing of Auth by using Annotated approach

- server/polar/authz/service.py
- server/tests/authz/test_service.py
- server/tests/pledge/test_endpoints.py
Restricts read access to:
* The pledging users
* Members of the org that received the pledge
* Members of the org that made the pledge
Fixes #1210
> server/pledge: restrict read access

- clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/(create)/page.tsx
- clients/apps/web/src/components/Organization/RepositoryPublicPage.tsx
- clients/apps/web/src/components/Organization/index.ts
- clients/apps/web/src/components/Pledge/PaymentForm.tsx
- clients/apps/web/src/components/Pledge/Pledge.tsx
- clients/apps/web/src/components/Pledge/Subtotal.tsx
- clients/apps/web/src/stories/IssueCard.stories.tsx
- clients/apps/web/src/stories/PledgePage.stories.tsx
- clients/apps/web/src/stories/Pledgers.stories.tsx
- clients/apps/web/src/stories/testdata.ts
- clients/packages/polarkit/src/api/client/index.ts
- clients/packages/polarkit/src/api/client/models/Author.ts
- clients/packages/polarkit/src/api/client/models/Issue.ts
- clients/packages/polarkit/src/components/pledge/IssueCard.tsx
- clients/packages/polarkit/src/components/pledge/Pledgers.tsx
- clients/packages/polarkit/src/components/pledge/RepositoryCard.tsx
- clients/packages/polarkit/src/components/pledge/index.ts
- clients/packages/polarkit/src/components/ui/Cards/types.ts
- clients/packages/polarkit/src/components/ui/atoms/Alert.stories.tsx
- clients/packages/polarkit/src/components/ui/atoms/Alert.tsx
- clients/packages/polarkit/src/components/ui/atoms/IssueBodyRenderer.stories.tsx
- clients/packages/polarkit/src/components/ui/atoms/IssueBodyRenderer.tsx
- clients/packages/polarkit/src/components/ui/atoms/index.ts
- clients/packages/polarkit/src/utils/index.ts
- server/polar/issue/schemas.py
I've implemented the first bits of the new issue presentation on the Pledge page.
Related to #1201 and #1200 
* General presentation of the issue (title, number, author, number of comments and reactions)
* Current pledge and optional goal
* Rendered issue description ✨
* Repository details with number of stars
* Optional upfront rewards split notice
* Pledgers avatars
* Component is ready, but still unsure about the API to retrieve them (cf our discussions related to #1210)
* List of rewarded people
* Feature is not yet implemented AFAIK?
* List of linked PR 
* We should implement an API to retrieve this data for an issue
What I propose is to merge and deploy those changes, even if we have some holes compared to the design, and address them in follow-up improvements.
The page looks …
> Implement new design of issue page's left part

- server/polar/dashboard/endpoints.py
- server/polar/integrations/github/service/issue.py
- server/polar/issue/endpoints.py
- server/polar/issue/service.py
- server/tests/issue/test_service.py
Either issues in directly owned repos, or issues that have been pledged towards.
These endpoints are not used.
> server/issues: remove dependencies dashboards

- clients/apps/web/src/components/Settings/PaymentMethodSettings.tsx
- clients/packages/polarkit/src/api/client/index.ts
- clients/packages/polarkit/src/api/client/models/PledgerPledgePendingNotification.ts
- clients/packages/polarkit/src/api/client/models/UserStripePortalSession.ts
- clients/packages/polarkit/src/api/client/services/UsersService.ts
- server/polar/integrations/stripe/service.py
- server/polar/user/endpoints.py
- server/polar/user/schemas.py
Adds a link to the Stripe-hosted customer dashboard. From there, the user can view past and upcoming invoices and manage their payment details.
> clients/settings: add link to stripe customer portal

- clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
Updates the copy in rewards modal to match Figma designs. Fixes #1384.
> clients/rewards: update copy in rewards modal

- clients/apps/web/next.config.js
- clients/apps/web/package.json
- clients/apps/web/src/app/backoffice/layout.tsx
- clients/apps/web/src/components/Dashboard/BackerNavigation.tsx
- clients/apps/web/src/components/Dashboard/MaintainerNavigation.tsx
- clients/apps/web/src/components/Dashboard/MaintainerRepoSelection.tsx
- clients/apps/web/src/components/Dashboard/navigation.tsx
- clients/apps/web/src/components/Layout/BackerLayout.stories.tsx
- clients/apps/web/src/components/Layout/BackerLayout.tsx
- clients/apps/web/src/components/Layout/DashboardLayout.tsx
- clients/apps/web/src/components/Layout/TopbarLayout.tsx
- clients/apps/web/src/components/Shared/DashboardTopbar.tsx
- clients/apps/web/src/components/Shared/ProfileSelection.tsx
- clients/apps/web/src/components/Shared/Topbar.tsx
- clients/apps/web/src/components/Shared/TopbarRight.tsx
- clients/apps/web/src/stories/Topbar.stories.tsx
- clients/apps/web/tailwind.config.js
- clients/pnpm-lock.yaml
Implements new design of the Backer & Maintainer dashboard layouts #1392.
- New Sidebar with integrated profile selection
- Subroutes now lives in the secondary nav (the page header) along with the page name
- Public topbar still has the old logic with profile selection, etc
- Updated iconography
> Implement new dashboard layout

- server/polar/issue/schemas.py
- server/polar/notifications/endpoints.py
- server/polar/notifications/schemas.py
Support for unions/anyOf is not the greatest in OpenAPI. The spec supports it fine, but not all generators (and target languages) do. In particular, the generator that I'm planning to introduce in #1405 does not support unions types.
This PR deprecates the union types, and adds the fields from the union as fields on the parent object instead. This honestly makes the generated code soo much nicer to work with, even if it doesn't use unions.
> server: migrate away from union types

- clients/packages/polarkit/src/components/badge/Badge.tsx
Handle overflows in the rewards banner in the Badge SVG.
Overflow with ellipsis instead of overflowing.
> clients/badge: tweak rewards for long org names

- server/polar/auth/dependencies.py
- server/polar/dashboard/endpoints.py
- server/polar/eventstream/endpoints.py
- server/polar/extension/endpoints.py
- server/tests/dashboard/test_endpoints.py
Removes the last few use cases of `Auth.user_with_org_access` and `Auth.user_with_org_and_repo_access`.
The authentication library now only does authentication. Authorization and data loading is done else where, like in the `Authz` library.
> server/auth: remove data loader and authorisation helpers

- clients/apps/web/src/stories/IssueListItem.stories.tsx
- clients/packages/polarkit/src/components/Issue/IssueReference.tsx
- clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx
- clients/packages/sdk/src/client/models/index.ts
- server/polar/issue/schemas.py
For some reason, the client type generation generates incompatible type names. Changing the names on the server to a format that the client is compatible with
> server/dashboard: fix generated code inconsistencies

- .github/workflows/publish_sdk.yaml
Use --publish-branch option when pushing new version of SDK to NPM.
> Use publish branch option when pushing new version of SDK to NPM

- server/polar/dashboard/endpoints.py
- server/polar/dashboard/schemas.py
- server/polar/funding/schemas.py
- server/polar/funding/service.py
- server/tests/funding/test_service.py
Moving away from JSON:API to get better type safety, and to align the design of this API with our other APIs.
First step is to add all related resources to the issue object without affecting the existing response.
After this is done, we can switch the clients to remove JSON:API parsing, and then finally remove it from the backend.
> server/dashboard: related resources without JSON:API

- server/.env.testing
- server/polar/auth/service.py
- server/polar/config.py
It allows us to set a root domain as cookie domain.
This way, we can forward the cookie to Next.js Server that'll proxy it towards the API.
> server/auth: set auth cookie domain

- clients/apps/web/src/app/maintainer/page.tsx
- clients/apps/web/src/components/Auth/Redirector.tsx
- clients/apps/web/src/components/Layout/DashboardLayout.tsx
- clients/apps/web/src/components/Pledge/OnBehalfOf.tsx
- clients/apps/web/src/components/Shared/ProfileSelection.tsx
- clients/apps/web/src/hooks/org.ts
- clients/packages/polarkit/src/hooks/queries/org.ts
- clients/packages/sdk/src/client/apis/OrganizationsApi.ts
- clients/packages/sdk/src/client/apis/RepositoriesApi.ts
- server/polar/integrations/github/service/user.py
- server/polar/integrations/github/tasks/webhook.py
- server/polar/organization/endpoints.py
- server/polar/organization/service.py
- server/polar/repository/endpoints.py
- server/tests/organization/test_endpoints.py
- server/tests/repository/test_endpoints.py
* Syncs non-admin memberships, and marks them as `is_admin=False`
* Updates the organization listing API to allow filtering by admin status.
* Use admin-only filtering everywhere where we previously listed organisations, and all-orgs listing in `<OnBehalfOf />`-pledging.
> Sync non-admin memberships

- clients/apps/web/next.config.js
- clients/apps/web/src/components/Shared/ProfileSelection.tsx
- server/polar/auth/service.py
The idea is to leverage Next.js server-side redirects to automatically redirect the user if they are logged-in or not.
The good thing is that it'll save us some "flashing" states when accessing login page while authenticated and vice versa.
Ultimately, this might allow us to remove the `Gatekeeper` component.
As a bonus, when accessing `polar.sh`, the user is automatically redirected to `polar.sh/feed` is they are logged in (not sure if desired, but I personally like the behavior. Can remove it otherwise).
---
To make this work, we simply check for the existence of our session cookie, `polar`, which I made a root domain cookie (see https://github.com/polarsource/polar/commit/11cac1d451cb935a87defe739241b69c3dfbbb65)
> clients/web: server-side redirection for logged-in/out users

- clients/apps/web/src/app/(public)/[organization]/subscriptions/page.tsx
- clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
- clients/apps/web/src/components/Subscriptions/OrganizationSubscriptionsPublicPage.tsx
- clients/apps/web/src/components/Subscriptions/PublicSubscriptionUpsell.tsx
- clients/apps/web/src/components/Subscriptions/SubscriptionGroup.tsx
- clients/apps/web/src/components/Subscriptions/SubscriptionGroupPublic.tsx
- clients/apps/web/src/components/Subscriptions/TiersPage.tsx
Implements a public `/{organization}/subscriptions` route which shows all tiers given a certain organization.
> clients/subscriptions: add public tier view for subscriptions

- clients/apps/web/src/components/Settings/Badge/index.tsx
Hiding the funding amount is not a feature anyone we've chatted to actually wants. It adds complexity and is many ways is a bit strange and confusing to the backer. So we're removing it. Starting with hiding the setting now at first. It's been defaulting to `true` for quite some time.
We'll then separately migrate historic accounts with it as `false` (once that was the default in the beginning) pending activity from them. We can then clean up all references to it in the codebase.
**Before**
**After**
> Disable hiding funding amount

- clients/packages/sdk/generate
- clients/packages/sdk/openapi_templates/modelAnyOfInterfaces.mustache
- clients/packages/sdk/openapi_templates/models.index.mustache
So, I digged up a bit and found that we can [actually override templates locally](https://openapi-generator.tech/docs/templating), so it was a good start to try out things.
It turns out that the generator already has all the required metadata to make it work, it's "just" a matter of adapting the templates. I took inspiration from what was done here: https://github.com/OpenAPITools/openapi-generator/pull/14241
And... It works! There are probably edge cases, but it looks to work pretty well for basic union types. Here is what it outputs for a `Union` type:
```ts
/**
* @type SubscriptionBenefitCreate
* @export
*/
export type SubscriptionBenefitCreate = SubscriptionBenefitBuiltinCreate | SubscriptionBenefitCustomCreate;
```
> clients/sdk: add anyOf support to OpenAPI generator

- clients/apps/web/src/components/Organization/RepoSelection.tsx
Makes sure that we relative-position repository picker popover.
> clients/reposelection: fix bug with misaligned repo picker popover

- clients/packages/polarkit/src/components/badge/Badge.tsx
- clients/packages/polarkit/src/components/pledge/IssueCard.tsx
Make sure we clarify upfront in the badge and the pledge page that rewards are specified on the total, but subject to fees so that the expectation is not 1:1 with the total funding amount
> clients/badge: Clarify fees

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
- .devcontainer/post_start_command.sh
- .gitignore
- clients/.vscode/launch.json
- server/.env.devcontainer
- server/.vscode/launch.json
- server/docker-compose.yml
- server/polar/config.py
Hacking on a dev container, as a way to support 1-click-setup for development environments. Mostly tailored for non-employees as an easy way to get started to hack on Polar.
At the current state, you can run the web app, run the server tests, and run the storybook.
The server does not boot, as it depends on a GitHub app. I'll work on that next...
Fixes #1236
> dev: start working on a devcontainer

- server/polar/app.py
- server/polar/kit/db/postgres.py
- server/polar/postgres.py
- server/polar/worker.py
- server/scripts/anonymous_pledge_migration.py
- server/scripts/dev_github.py
- server/scripts/issues.py
- server/scripts/loops_migration.py
- server/scripts/transfer_fix.py
- server/tests/fixtures/database.py
This is useful when querying for `pg_stat_activity` in PostgreSQL
because it'll tell us which processes has opened connections.
Hopefully, it'll help us debug #265.
> server/dx: set application name on PostgreSQL connection

- clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
This check was not really necessary anyway, as no subscription data can be loaded from the API.
> clients/organization: remove isFeatureEnabled from server-side

- server/polar/integrations/github/badge.py
- server/tests/integrations/github/test_badge.py
The onboarded_at check was effectively also an installation_id check. Adding one to check that the GitHub App is installed in it's place.
> server/badge: remove onboarded_at check

- clients/apps/web/src/app/(backer)/posts/[postId]/page.tsx
- clients/apps/web/src/app/(public)/[organization]/page.tsx
- clients/apps/web/src/app/(public)/[organization]/posts/[postId]/page.tsx
- clients/apps/web/src/app/maintainer/[organization]/posts/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/posts/[post]/ClientPage.tsx
- clients/apps/web/src/components/Feed/Feed.tsx
- clients/apps/web/src/components/Feed/data.ts
Previously the page would not load if you did not have a emilwidlund org in your database. This changes the demo to use the current user or organization when generating demo data. :-)
> clients/posts: use current user in demo issues

- server/polar/account/endpoints.py
- server/polar/account/service.py
- server/polar/integrations/stripe/service.py
Set names of Stripe Accounts. Useful for us (Polar) to keep track of accounts. This was triggered by #1729 but does not solve it. This name is not visible in Stripe Express.
> server/stripe: set account names

- clients/apps/web/src/app/(email)/email/article/[id]/route.tsx
- clients/apps/web/src/components/Feed/Posts/Poll.tsx
- clients/apps/web/src/components/Feed/Posts/markdown.tsx
> clients/Poll: override renderer when rendering for emails

- clients/apps/web/src/components/Feed/LongformPost.tsx
- clients/apps/web/src/components/Feed/Posts/BrowserPoll.tsx
- clients/apps/web/src/components/Feed/Posts/Poll.tsx
- clients/apps/web/src/components/Feed/Posts/markdownBrowser.tsx
- clients/apps/web/src/components/Markdown/MarkdownPreview.tsx
Splits the dependency graph into one path for web-components and another one for email-components, so that we can use client-side reactive React. :)
> clients/article: demo with reactive component in browsers

- clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
Fixes the issue where linkes with ?tab=subscriptions doesn't open the subscriptios tab
> clients/organization: reactive tab navigation

- clients/apps/web/src/app/(email)/email/article/[id]/route.tsx
Redesigned the header, and added a new footer.
> clients/article: improved email design

- clients/apps/web/src/app/(backer)/feed/page.tsx
- clients/apps/web/src/app/(backer)/rewards/page.tsx
- clients/apps/web/src/app/(dashboard)/finance/incoming/ClientPage.tsx
- clients/apps/web/src/app/(dashboard)/finance/outgoing/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/finance/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/finance/contributors/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/finance/rewarded/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/finance_new/incoming/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/finance_new/outgoing/ClientPage.tsx
- clients/apps/web/src/components/Finance/Finance.tsx
- clients/apps/web/src/components/Subscriptions/TiersPage.tsx
- clients/apps/web/src/components/Transactions/AccountBanner.tsx
- clients/apps/web/src/stories/FinancePage.stories.tsx
- clients/packages/polarkit/src/hooks/queries/index.ts
- clients/packages/sdk/src/client/apis/AccountsApi.ts
- clients/packages/sdk/src/client/models/index.ts
- server/polar/account/endpoints.py
- server/tests/account/test_endpoints.py
We used to have a `/search` API for Account which returned a list of accounts for a given user/organization.
Since `Account` have a unique constraint on `user_id`/`organization_id`, it makes more sense to use a `/lookup` which return a single account or 404. It greatly simplifies the reasoning in the UI.
Preliminary work for #1807.
> Make Account API return only one account per user/organization

- clients/apps/web/src/components/Subscriptions/SubscriptionTierSubscribeButton.tsx
> clients/web: handle subscription tier downgrade more gracefully

- clients/apps/web/src/app/(public)/[organization]/(layout)/issues/page.tsx
- clients/apps/web/src/app/(public)/[organization]/(layout)/page.tsx
- clients/apps/web/src/app/(public)/[organization]/(layout)/repositories/page.tsx
- clients/apps/web/src/app/(public)/[organization]/(layout)/subscriptions/page.tsx
- clients/apps/web/src/app/(public)/[organization]/[repo]/page.tsx
- clients/apps/web/src/app/(public)/subscribe/route.ts
This fixes some issues with broken links to private repositories etc
> clients/public: use getServerSideAPI()

- server/polar/subscription/endpoints.py
This is the correct type to use to get the file to be downloaded and saved to disk in all browsers
> server/subscriptions: set Content-Disposition type to attachment

- server/Caddyfile
I'm running local dev behind a proxy (for testing in a more realistic environment, with HTTPS etc). Adding trusted_proxies to make FastAPIs request.url_for() work as expected
> server/ingress: fix FastAPI hostname detection when running behind Caddy

- clients/README.md
Ran into this issue last night and was convinced this file was supposed to always be auto-generated, but it seems we need to manually edit it to register new API classes. So adding a friendly note about it.
> clients/readme: Note about adding new API classes

- server/polar/article/endpoints.py
- server/polar/auth/dependencies.py
- server/polar/auth/service.py
- server/polar/authz/service.py
- server/polar/personal_access_token/endpoints.py
- server/polar/personal_access_token/schemas.py
- server/polar/sentry.py
- server/polar/user/endpoints.py
- server/polar/user/schemas.py
- server/tests/personal_access_token/test_endpoints.py
In before: posts-only access tokens for RSS feeds
Adding a `ScopedSubject` that tracks a subject (still `User | Anonymous`) and a list of scopes. By default this scope is "admin" which is the default web scope, and is only used internally.
The goal is to be able to create PATs with a `articles:read` scope that only allows read access to articles endpoints.
> Auth scopes

- server/polar/integrations/github/client.py
- server/polar/integrations/github/service/user.py
- server/polar/models/user.py
- server/polar/user/endpoints.py
- server/polar/user/oauth_service.py
- server/polar/user/service.py
Lazy loading does not work well in async contexts. Removing the second-to-last lazy="joined"!
> server/user: eager loading of oauth accounts

- docs/vercel.json
Pages without a trailing slash will redirect to the slashed version. Eg /faq redirects to /faq/
This mimics the behaviour of `mkdocs serve` on Vercel.
> docs: add trailing slash redirects

- server/pyproject.toml
- server/tests/fixtures/base.py
- server/tests/subscription/conftest.py
- server/tests/subscription/service/test_subscribe_session.py
- server/tests/subscription/service/test_subscription.py
- server/tests/subscription/service/test_subscription_benefit.py
- server/tests/subscription/service/test_subscription_benefit_grant.py
- server/tests/subscription/service/test_subscription_tier.py
- server/tests/subscription/test_endpoints.py
- server/tests/subscription/test_tasks.py
Attempt to enforce calling `session.expunge_all()` between test setup and test execution.
Adding it for all subscriptions related tests to start with.
Updates #2059
> Call `session.expunge_all()` between test setup and execution

- server/polar/models/subscription.py
- server/polar/subscription/service/subscription.py
- server/tests/subscription/service/test_subscription.py
> server/subscription: count subscribers only once when sub/unsub multiple times in a month

- clients/apps/web/src/app/(backer)/funding/FundingPage.tsx
- clients/apps/web/src/app/(backer)/funding/page.tsx
- clients/apps/web/src/components/Dashboard/navigation.tsx
With feature flags:
* Feed links to /posts (new name, same url)
* Funding links to /funding (new route)
Without feature flag:
* Funding links to /feed (same route as before, but renamed)
> clients/navigation: rename Feed and Funding

- clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
This fixes a bug where the tier group icon would disappear when making changes to the tier on the edit page.
> clients/subscriptions: pass all data, including tier group to TierCard when editing

- server/polar/kit/csv.py
Mailchimp uses "Email Address" as the column name:
Let me know if you want me to add a test :)
> Add support for importing subscribers from mailchimp

- clients/apps/web/src/app/(public)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/[post]/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/new/ClientPage.tsx
- clients/apps/web/src/components/Feed/LongformPost.tsx
- clients/apps/web/src/components/Feed/PostEditor.tsx
- clients/apps/web/src/components/Shared/StaggerReveal.tsx
Current thesis is that the animations have a large effect on SEO ranking. Disabling animations for posts on the public pages.
If we want, we could later re-enable animations, but ideally only on in-app navigations, such as when navigating from a list view. But not on the first page load.
> clients/posts: disable reveal animations

- server/polar/subscription/schemas.py
- server/polar/subscription/service/subscription_tier.py
- server/tests/subscription/conftest.py
- server/tests/subscription/service/test_subscription_tier.py
> server/subscription: prevent accepting empty string as tier description

- clients/apps/web/src/app/(public)/[organization]/(layout)/layout.tsx
Hoping that this will lead to more of the page to get rendered serverside when it isn't cached.
> clients: remove <Suspense> boundary on public pages

- server/polar/subscription/service/subscription.py
Previously the query looked like this:
FROM
subscriptions
LEFT OUTER JOIN user_organizations ON user_organizations.organization_id = subscriptions.organization_id
AND user_organizations.user_id = 7
LEFT OUTER JOIN organizations AS organizations_1 ON organizations_1.id = subscriptions.organization_id
LEFT OUTER JOIN subscription_tiers AS subscription_tiers_1 ON subscription_tiers_1.id = subscriptions.subscription_tier_id,
subscription_tiers
Adding the missing join :)
> server/subscriptions: add missing join in subscribed search

- clients/apps/web/src/app/(public)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
Allow users with localStorage disabled to read posts
Fixes #2256
> clients/posts: gracefully handle unavailable localStorage

- clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/[post]/ClientPage.tsx
- clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/new/ClientPage.tsx
- clients/apps/web/src/components/Feed/PostEditor.tsx
- clients/apps/web/src/components/Feed/Toolbar/PostToolbar.tsx
Fixes #2317 
The publish tab now creates the post, and redirects to the settings tab :)
The UI flickers a bit when this happens, which is to be improved later, shipping this as is as it's still a huge improvement.
> clients/posts: publish tab on new post

- .gitignore
- clients/apps/web/src/components/Feed/LongformPost.tsx
- clients/apps/web/src/components/Shared/StaggerReveal.tsx
This is a minor change that makes the `LongFormPost` component use semantic HTML tags. There's more that could be done (e.g. using the `<footer>` tag), but it's somewhat of a start.
This should make posts easier for both screenreader users and crawlers to parse!
I tried to make the `as` property of the `StaggerReveal` component take in any HTML element, but this caused some weird type issues that I'm not familiar enough with React/Framer Motion to fix.
It's also worth noting that I wasn't able to run a local development environment, and codespaces were giving me issues, so it's entirely possible that this is completely borked. Sorry about that 😅
> chore: use semantic HTML for LongFormPost

- clients/apps/web/src/components/Feed/Toolbar/MarkdownToolbar.tsx
Showing the components directly solves a problem in WebKit where focus was lost, and we where unable to move the focus back to the textarea to run document.execCommand(). There might be a better way to fix this, but this is an easy and straight forward one.
Fixes #2342
> clients/editor: component buttons directly

- server/polar/user_organization/service.py
By ensuring our getter for existing organizations filters out
organizations that have been deleted too.
> server/onboarding: Reactivate deleted organization in case one exists

- clients/apps/web/src/components/Subscriptions/SubscriptionSuccess.tsx
For already logged in users
Before/After:
> clients/subscriptions: offer to go to /org after subscribing to org

- clients/apps/web/package.json
- clients/apps/web/src/app/(topbar)/[organization]/(layout)/posts/[postSlug]/page.tsx
- clients/apps/web/src/components/Feed/Markdown/preview.test.tsx
- clients/apps/web/src/components/Feed/Markdown/preview.tsx
- clients/pnpm-lock.yaml
Fixes incorrect html entities in og:description and similar
> clients/articles: decode html entities in the text only renderer

- clients/apps/web/src/app/(topbar)/[organization]/(layout)/[repo]/ClientPage.tsx
- clients/apps/web/src/components/Organization/RepositoriesOverview.tsx
> clients/repositories: notice on private repos

- clients/apps/web/src/components/Feed/Markdown/Img/ImageOverlay.tsx
- clients/apps/web/src/components/Feed/Markdown/__snapshots__/render.test.tsx.snap
- clients/apps/web/src/components/Feed/Markdown/markdown.tsx
- clients/apps/web/src/components/Feed/Markdown/render.test.tsx
Adds support for the `<picture>` and `<source>` HTML elements. As well as respecting alt/height/width properties of `<img>` elements.
(you can now have custom dark-mode images in posts!)
> clients/posts: support or ads markdown directly in posts

- clients/apps/web/src/components/Markdown/MarkdownEditor.tsx
Also running the resize effect more often. This should hopefully fix issues where a scrollbar can appear in the textarea.
Fixes #2435
> clients/editor: allow textarea to shrink

- clients/apps/web/src/components/Layout/Public/Topbar.tsx
- clients/apps/web/src/components/Layout/Public/TopbarRight.tsx
Also making the topbar smaller on mobile devices, by hiding the GH login button (oauth login is also available from the /login page)
> clients/topbar: 'Create with Polar' and 'Login' as actions

- clients/apps/web/src/components/Feed/Markdown/SubscribeNow/SubscribeNow.tsx
> clients/posts: show <SubscribeNow> for subscribed users

- clients/apps/web/src/app/(topbar)/[organization]/(layout)/ClientPage.tsx
- clients/apps/web/src/components/Feed/Posts/Post.tsx
Make sure that we're not using "cursor: pointer" on posts when it's not clickable.
The post div requires JS to be clickable, and you would previsouly see the pointer cursor before document.ready had fired, even if you couldn't click the whole block yet.
Switching to controlling the cursor styling with JS to match the expected result.
Fixes #2437
> clients/posts: clarify post clickability

- clients/apps/web/src/components/Feed/Markdown/SyntaxHighlighter/SyntaxHighlighter.tsx
> clients/SyntaxHighlighter: make line numbers non-selectable

- clients/apps/web/src/app/(topbar)/(backer)/subscriptions/ClientPage.tsx
- clients/apps/web/src/components/Feed/MySubscriptions.tsx
Fixes #2511 
---
Note: I wasn't sure whether to just update the 'Unsubscribe' dropdown items, or whether all dropdown menu items should have `cursor-pointer`, so I did the former. Happy to update so that the `DropdownMenuItem` in `polarkit` uses the class by default.
> chore: add  to unsubscribe dropdowns

- clients/apps/web/package.json
- clients/apps/web/src/components/Feed/Markdown/__snapshots__/render-browser.test.tsx.snap
- clients/apps/web/src/components/Feed/Markdown/__snapshots__/render.test.tsx.snap
- clients/apps/web/src/components/Feed/Markdown/render-browser.test.tsx
- clients/apps/web/src/components/Feed/Markdown/render.test.tsx
- clients/pnpm-lock.yaml
Downgrade markdown-to-jsx as a workaround for issues with `<blockquote>` in Firefox.
The issue has been reported upstream https://github.com/quantizor/markdown-to-jsx/issues/542
> clients/markdown: downgrade renderer to v7.3

- server/polar/integrations/github/service/repository.py
- server/polar/integrations/github/tasks/webhook.py
- server/tests/integrations/github/tasks/test_webhook.py
On a new installation of a repository, and on transferred repositories:
If there alredy exists a (deleted) repository with the same name as the new repository, rename the old repository so that the new one can use it's name.
> server/github: handle deleted repo with same name

- clients/apps/web/next.config.js
- clients/apps/web/src/app/(topbar)/[organization]/(layout)/issues/page.tsx
- clients/apps/web/src/app/(topbar)/[organization]/(layout)/page.tsx
- clients/apps/web/src/app/(topbar)/[organization]/(layout)/posts/[postSlug]/page.tsx
- clients/apps/web/src/app/(topbar)/[organization]/(layout)/subscriptions/page.tsx
- clients/apps/web/src/components/Feed/Posts/Post.tsx
- clients/apps/web/src/components/Organization/OrganizationPublicPageNav.tsx
- clients/apps/web/src/middleware.ts
- clients/apps/web/src/utils/nav.ts
- clients/packages/sdk/src/client/apis/OrganizationsApi.ts
- clients/packages/sdk/src/client/models/index.ts
- clients/turbo.json
Support much of the read-only experience with custom domains.
Organization pages with posts, subscriptions, and issues is browsable.
Client-side fetching of data does not work yet (pending CORS improvements on the server).
The repository pages are not yet routable.
Updates #2632
> Custom domains

- clients/packages/astro/src/upload.ts
The `PolarUploadBuilder` class should never throw an error. This PR fixes some undesirable behaviour where it would throw an incorrectly-instantiated error.
Also use `onfulfilled` to ensure the promise always completes and doesn't throw that way.
> astro: ensure client doesn't throw

- clients/apps/web/src/app/layout.tsx
- clients/apps/web/src/app/maintainer/new/page.tsx
- clients/apps/web/src/app/maintainer/page.tsx
- clients/apps/web/src/components/Layout/DashboardLayout.tsx
- clients/apps/web/src/components/Navigation/DashboardTopbar.tsx
- clients/apps/web/src/hooks/auth.ts
- clients/apps/web/src/hooks/team.ts
- clients/apps/web/src/providers/auth.tsx
- clients/packages/polarkit/src/store/index.ts
- clients/packages/polarkit/src/store/userContext.ts
Makes the cookie the only source of truth, and removes clientside flashes as the client was loading user data
> clients/auth: use a react context instead of zustand

- clients/apps/web/src/app/[organization]/(sidebar)/issues/page.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/page.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/posts/[postSlug]/page.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/posts/page.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/repositories/page.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/subscriptions/page.tsx
- clients/apps/web/src/app/[organization]/[repo]/ClientPage.tsx
- clients/apps/web/src/app/[organization]/[repo]/issues/[number]/(create)/page.tsx
- clients/apps/web/src/app/[organization]/[repo]/page.tsx
- clients/apps/web/src/app/[organization]/subscribe/page.tsx
- clients/apps/web/src/middleware.ts
- clients/apps/web/src/utils/nav.ts
Org lookups are case-insensitive, redirect to the correct spelling if there's a difference
> clients/public: redirect public pages to the canonical spelling of org names

- server/migrations/versions/2024-03-08_oauth_accounts.account_username.py
Sets `account_username` for the GitHub oauth accounts that doesn't already have it set.
> server/users: backfill account_username from users.username

- server/polar/transaction/service/balance.py
- server/polar/transaction/service/dispute.py
- server/polar/transaction/service/payment.py
- server/polar/transaction/service/payout.py
- server/polar/transaction/service/processor_fee.py
- server/polar/transaction/service/refund.py
- server/scripts/account_payout_schedule.py
- server/scripts/anonymous_pledge_migration.py
- server/scripts/platform_fees_migration.py
- server/scripts/pledge_invoice_payment_fix.py
- server/scripts/transfer_fix.py
Remove `.commit()` for transactions logic.
The most straightforward way is to replace `.commit()` by `.flush()`.
There are probably more optimal ways (i.e. limit the number of flushes), but for code that were designed to frenetically commit, it would require to revisit each interaction.
> Post-commit era - Transactions

- server/polar/account/service.py
- server/polar/article/schemas.py
- server/polar/article/tasks.py
- server/polar/auth/dependencies.py
- server/polar/backoffice/endpoints.py
- server/polar/integrations/github/service/issue.py
- server/polar/integrations/github/service/organization.py
- server/polar/integrations/github/service/user.py
- server/polar/integrations/stripe/service.py
- server/polar/models/account.py
- server/polar/models/user.py
- server/polar/pledge/schemas.py
- server/polar/pledge/service.py
- server/tests/article/test_endpoints.py
- server/tests/dashboard/test_endpoints.py
- server/tests/fixtures/random_objects.py
- server/tests/notifications/test_pledge_notifications.py
- server/tests/pledge/test_endpoints.py
- server/tests/pledge/test_service.py
- server/tests/reward/test_service.py
Use user.username_or_email or user.github_username (or similar) to get this data instead
This does not change anything in the wild, as the username field can contain email adresses
> server/users: move away from user.username

- clients/apps/web/src/components/Feed/Markdown/BrowserRender.tsx
- clients/apps/web/src/components/Feed/Markdown/__snapshots__/render.test.tsx.snap
- clients/apps/web/src/components/Feed/Markdown/abbreviatedContent.test.ts
- clients/apps/web/src/components/Feed/Markdown/render.test.tsx
Lifts up content from below the boundary.
This adds support for rendering the abbreviation of the following:
```markdown
Hello [World][world].
---
[world]: https://polar.sh
```
> clients/markdown: support references in abbreviated renderer

- server/polar/config.py
- server/polar/receivers/pledges.py
- Makes Discord embed for pledge events prettier
- Closes #2864
- Feel free to close, just had a wild hair on lunch.
- I tested locally but I'd like to be able to test with the pulled values from the database and others, if someone can do that?
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat(discord): add more detail to pledge embed

- clients/apps/web/src/app/[organization]/(sidebar)/ClientPage.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/page.tsx
- clients/apps/web/src/components/Organization/OrganizationHighlightedTiers.tsx
- clients/apps/web/src/components/Profile/CreatorEditor/CreatorsEditor.tsx
- clients/apps/web/src/components/Profile/LinksEditor/LinksEditor.tsx
- clients/apps/web/src/components/Profile/ProjectEditor/ProjectsEditor.tsx
- clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx
- clients/apps/web/src/components/Subscriptions/SubscriptionTierCreatePage.tsx
- clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
Implements an empty state for creators on the Org profile, where you can setup a simple $5 tier with a single click.
> clients/org: implement automatic tier creation from suggested tier

- server/polar/funding/service.py
- server/polar/models/user.py
- server/tests/fixtures/random_objects.py
- server/tests/funding/test_service.py
Load at most one oauth account. This fixes a bug where pledges where double-counted in the funding API if the pledging user had multiple oauth accounts connected.
> server/funding: override oauth account loading

- server/polar/transaction/service/payout.py
- server/tests/transaction/service/test_payout.py
Because of conflicts when trying to pay out pledges
> server/transaction: temporarily disable setting transfer group while payout

- clients/apps/web/src/app/[organization]/[repo]/ClientPage.tsx
- clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx
- clients/apps/web/src/components/Profile/DescriptionEditor/DescriptionEditor.tsx
- server/polar/organization/schemas.py
- server/polar/repository/schemas.py
- server/tests/organization/test_endpoints.py
- server/tests/repository/test_endpoints.py
- server/tests/subscription/service/test_subscription_tier.py
Same as what I previously added for org descriptions.
> clients/repository: error handling for repository description

- clients/apps/web/src/components/Subscriptions/SubscriptionTierCelebration.tsx
> clients/SubscriptionTierCelebration: fixes for gradient colors in Safari

- clients/apps/web/src/components/Benefit/GitHubRepositoryBenefitForm.tsx
- server/poetry.lock
- server/polar/integrations/github_repository_benefit/service.py
This pull request adds error handling for the refresh token process in the GitHub repository benefit integration. If an error occurs while refreshing the access token, the user will be prompted to reconnect their account.
> Handle GitHub repository benefit refresh token error

- render.yaml
- server/polar/integrations/github/receivers.py
- server/polar/receivers/pull_request.py
- server/polar/worker.py
- server/pyproject.toml
- server/run_worker.py
- server/scripts/dev_github.py
When using outgoing webhooks in production the queue delays have become more noticeable, when developing a 30s delay in hook delivery is not a pleasant experience.
This PR creates a new arq job queue for GitHub sync/crawling, and runs the other jobs on the "default" queue.
All cronjobs still run on the "default" worker.
> server/worker: run github crawl jobs on a separate worker

- clients/apps/web/src/components/Issues/IssueListItem.tsx
- clients/apps/web/src/components/Issues/IssueSummary.tsx
- clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
- clients/apps/web/src/components/Organization/OrganizationIssueSummaryList.tsx
Confusing UX that the entire issue linked to funding in the dashboard
when the main mode is badging. Solving this by removing linking the
headline in the dashboard. But adding the funding button everywhere to
still have it accessible, i.e maintainers funding it themselves for
rewards.
> client: Don't link issue to funding in dashboard, but show funding button

- server/polar/models/issue_reward.py
- server/tests/reward/test_service.py
Ensuring we always get a percentage point that uses decimal arithmetic
vs. binary floating point arithemtic in Python which is not what we
want.
> Rewards percentage using decimal.Decimal

- clients/apps/web/src/app/(installation)/github/installation/page.tsx
Sometimes users report an error during installation. I suspect it might
be that GitHub redirects back immediately, but might not have fully
completed the installation (worker tasks). So our API seems to fail
without us capturing/handling it properly.
Informing the user to attempt to reload + throwing the error so Sentry
logs it for us to debug more closely.
> clients: Better error handling in GitHub installation

- server/polar/app.py
- server/polar/kit/cors.py
The goal is to allow external API callers to be able to do so in a cross-origin scenario *but* only with the `Authorization` header and a proper token: cookie authentication should be blocked for them and allowed only for our own allow-listed origins.
> server: implement more advanced CORS handling

- server/polar/models/transaction.py
- server/polar/transaction/service/payout.py
We were not considering all the balance reversal when computing the transfer of a balance. This caused a mismatch when some balance were refunded.
> server/transaction: fix payout computation

- clients/apps/web/next.config.mjs
Not working at the moment. Uncomment and stop the redirect attempt until
real fix can be deployed.
> docs: Temporarily stop docs.polar.sh redirect

- clients/apps/web/src/components/Documentation/Parameters.tsx
Just causes duplication and confusion + more text to parse.
> docs: Remove human title of parameter names

- server/polar/integrations/open_collective/service.py
- server/tests/account/test_endpoints.py
- server/tests/fixtures/cassettes/open_collective/collective/not_ready.json
- server/tests/integrations/open_collective/test_service.py
> server/integrations/open_collective: handle case where host is null

- clients/apps/web/src/app/[organization]/(sidebar)/layout.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/subscriptions/ClientPage.tsx
- clients/apps/web/src/app/[organization]/(sidebar)/subscriptions/page.tsx
- clients/apps/web/src/app/embed/subscribe.svg/route.tsx
- clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx
- clients/apps/web/src/components/Profile/SubscribeEditor/SubscribeEditor.tsx
- clients/packages/sdk/openapi/source.json
- clients/packages/sdk/openapi/updated.json
- clients/packages/sdk/src/client/apis/IntegrationsDiscordApi.ts
- clients/packages/sdk/src/client/models/index.ts
- server/polar/organization/endpoints.py
- server/polar/organization/schemas.py
- server/polar/organization/service.py
- server/tests/organization/test_endpoints.py
https://github.com/user-attachments/assets/8e35a381-7931-4500-8dec-be319170e829
Give creators more control over how to promote subscriptions on their Polar page.
- Show/hide `Subscribe with Email` and subsequently the `Free` tier on the `Subscriptions` page
- Show/hide the public count/display of active subscribers
- Include/exclude free subscribers in the total count of active subscribers
Leverage the same `profile_settings` in the `Subscribe` embed badge to reflect the same count.
> Polar Page: Customize Free Subscription Promotion & Counting

- clients/apps/web/src/components/Notifications/Popover.tsx
- clients/packages/sdk/openapi/source.json
- clients/packages/sdk/openapi/updated.json
- clients/packages/sdk/src/client/models/index.ts
- server/polar/notifications/notification.py
- server/polar/order/service.py
- server/tests/notifications/test_email.py
- server/tests/notifications/testdata/test_MaintainerNewProductSaleNotification.html
> Product sales notifications

- clients/apps/web/src/app/dashboard/[organization]/(topbar)/issues/overview/ClientPage.tsx
> clients/web: fix repositories picker not showing all repos available

- server/polar/organization/endpoints.py
- server/tests/organization/test_endpoints.py
Prevent users from enumerating organizations.
> server/organization: require either `slug` or `is_member` on list API

- server/polar/magic_link/endpoints.py
- server/tests/magic_link/test_endpoints.py
Prevent magic link code from being consumed when email scanning systems automatically open links
> server/magic_link: add an interstitial HTML page when opening the magic link

- clients/apps/web/next.config.mjs
- clients/apps/web/src/app/start/page.tsx
* If the user has no organization, redirect them to their purchases page.
* If the user has at least one organization, redirect them to the first organization's dashboard.
> clients/web: fix root redirection for authenticated users

- clients/apps/web/src/components/Landing/TopbarNavigation.tsx
The navigation pointed to "https://docs.polar.sh/api/polar-sdk" though this path leads to 404
> fix: update url in top bar nav to point to sdk

- clients/packages/polarkit/src/components/ui/atoms/MoneyInput.tsx
> clients/web: avoid floating point errors when converting money input to cents

- server/polar/subscription/email_templates/cancellation.html
- server/polar/subscription/service.py
On the existing code, Polar send the subscription created email for when the even is subscription cancelation.
> server: differentiate email for subscription cancelation

- clients/packages/polarkit/src/components/ui/atoms/MoneyInput.tsx
https://github.com/user-attachments/assets/5879e618-393b-42ff-b752-0bf4107fbc32
The current input scroll behavior is very error-prone, as shown in the attached video
Lemon Squeezy, Tokopedia also disable the scroll on the input[type=number].
> clients: blur money input on scroll

- clients/apps/web/src/components/Settings/Webhook/NewWebhookModal.tsx
Makes sure that webhook panel is scrollable.
Fixes #3975.
> clients/webhooks: fix overflowing issue

- sdk/overlays/product_price_discriminator.yml
Which Speakeasy doesn't support
> sdk: add an overlay to nested discriminator for ProductPrice schemas

- clients/apps/web/src/components/Layout/DashboardLayout.tsx
We now have `Onboarding` instead with setup steps. Just an unnecessary &
bloated upsell + causes FOC on hard refreshes.
> clients: Remove product creation upsell in sidebar

- clients/apps/web/next.config.mjs
- clients/apps/web/src/app/[organization]/(sidebar)/subscriptions/page.tsx
Avoid overwriting a real route by moving the redirect to the storefront
/:slug/subscriptions app directory
> clients: Fix gready redirect of /purchases/subscriptions

- .devcontainer/Caddyfile
- server/polar/app.py
- server/polar/middlewares.py
Unnecessary to make things work on Render: it was made for GitHub Codespaces.
Removing it because it probably exposes us to security issues (Render doesn't sanitate it), and found a better way to handle it for GH Codespace
> server: remove XForwardedHostMiddleware

- clients/apps/web/src/components/Checkout/CheckoutForm.tsx
The email field was hidden when customer was set, so it was not part of the submit data payload.
Display it as disabled field to solve that.
> clients/web/checkout: fix Stripe complaining email is missing on confirm

- server/polar/checkout/service.py
Prevents a client error from Stripe complaining the amount is 0
> server/checkout: set an arbitrary amount on PWYW product if nothing is set

- server/migrations/versions/2024-10-15-1003_fix_user_attribution_without_polar_.py
Since we created those subscriptions directly upon signup they would
camoflauge the real intent and are worthless to us. We'll get more
intent=creator as a result which is what we want to see.
> User attribution without Polar Newsletter subscriptions

- server/polar/worker.py
- server/tests/fixtures/worker.py
ARQ instance doesn't decode responses, which causes issues with our logic using Redis, esp. GitHub tokens cache.
Create another dedicated connection pool with decoding enabled to avoid this.
> server/worker: fix issues with tasks using the Redis instance

- clients/apps/web/src/components/Landing/LandingPage.tsx
- clients/apps/web/src/components/Landing/Testimonials.tsx
Fixes #4221 
Fix the word “Testimonials” being misspelled.
The typo only happens in code, and there is no use of the word “Testimonials” in the landing page.
Fixed the typo by adjusting the variable, component, and import names.
> clients/landing: Fix "Testimonials" word spelling

- clients/apps/web/src/components/CommandPalette/commands/trigger.tsx
fixes: #3577 
This PR fixes the bug that catches the Chrome search bar on Windows instead of Polar's by preventing the default behavior of the browser.
> fix: fix the Ctrl+ K that catches Chrome search bar on Windows

- server/polar/order/service.py
- server/tests/order/test_service.py
Take the amount from the order doesn't always work, as invoices may apply customer balances which won't reflect the actual payment amount
> server/order: create balances with amount taken from actual payment transaction

- clients/apps/web/src/components/Landing/Hero/Hero.tsx
- clients/apps/web/src/components/Landing/LandingLayout.tsx
- **clients: Shorten pricing copy next to signup nudge**
- **clients: Rename `Login` to `Open Dashboard` on website + different variant**
> website: Rename `Login` to `Open Dashboard`

- clients/apps/web/src/components/Auth/AuthModal.tsx
- clients/apps/web/src/components/Auth/GithubLoginButton.tsx
- clients/apps/web/src/components/Auth/Login.tsx
- clients/apps/web/src/components/Auth/MagicLinkLoginForm.tsx
- clients/apps/web/src/components/Landing/Hero/Hero.tsx
- clients/apps/web/src/components/Landing/LandingLayout.tsx
- **clients: Add GetStartedButton in topbar on landing pages**
- **clients: Call organization name storename in Hero**
- **clients: Make GitHub login/signup primary**
- **clients: Copy to reflect vs. hope for sales**
- **clients: Signup modal copy change**
- **clients: Bigger main signup CTA**
> website: Better Signup CTA

- clients/apps/web/src/components/Checkout/CheckoutForm.tsx
fixes: #4130 
This PR adds a link `Add Tax Id` to toggle the input box for the Tax Id.
Here is how it looks:
https://github.com/user-attachments/assets/53b9caa6-935e-410b-a410-4b4456f0ce27
> feat: add a link to Toggle VAT number field 

- server/polar/benefit/benefits/base.py
- server/polar/benefit/benefits/license_keys.py
- server/polar/benefit/service/benefit_grant.py
- server/tests/benefit/service/test_benefit_grant.py
Useful for license keys where we generate a single key for each grant, contrary to other benefits where the side effect is global and should only revoked for the last remaining grant (like GitHub Repository invitation)
> server/benefit: add a flag on benefit service to check if we should revoke benefit individually or not

- server/polar/transaction/service/payout.py
- server/tests/transaction/conftest.py
- server/tests/transaction/service/test_payout.py
> server/transaction: trigger only once payout per account per run

- clients/apps/web/src/components/Checkout/CheckoutLayout.tsx
Fixes #4295 
Fix the checkout page background being cut off, by removing the `md:h-screen` class.
Before
After
> clients/checkout: Fix checkout page background cut off

- clients/apps/web/src/components/Organization/StorefrontNav.tsx
Fixes #4129 
Use `<Select>` component for storefront mobile navigation.
- Uses the tailwind media query break point for choosing which navigation to show (sm)
- For `Select` component (radix), it does not support putting `Link` inside the `SelectItem` component (nothing will happen upon clicking), that is why it is using router for navigation 
https://github.com/user-attachments/assets/ac1e547b-644b-4692-9342-2d26fca1b649
> clients/storefront: Optimize mobile storefront navigation

- clients/apps/web/sentry.client.config.ts
- clients/apps/web/sentry.edge.config.ts
- clients/apps/web/sentry.server.config.ts
- server/polar/sentry.py
We don't really use them, so better to save a bit of money for the time being
> ops: disable Sentry tracing and replay

- server/polar/redis.py
- server/polar/worker.py
- server/run_worker.py
Make sure the process terminates if Redis is lost. This way, the infrastructure can detect it and automatically restart it... Or at least ping us.
> server: improve resiliency of worker in case of Redis loss

- sdk/overlays/read_only.yml
Prevents Speakeasy from generating "Input" models because of webhooks schemas which are wrongfully considered as payload schemas (due to how they're documented in FastAPI).
We've our own hygiene of separating input and output schemas, so this should not harm the validity of the output SDK.
> sdk: add an overlay to remove readOnly flags

- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/sales/ClientPage.tsx
- clients/apps/web/src/components/Layout/Section.tsx
- clients/apps/web/src/components/Products/ProductBenefitsForm.tsx
- clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
- clients/apps/web/src/hooks/products.ts
Fixes a few issues mentioned by @michael-andreuzza.
- Better layout on Product Create/Edit Page
- Benefit groups with enabled benefits are now collapsable
- Sales Dropdown are automatically adjusting its size
- Bump query limit on products when retrieving them in price type groupings (which previously made sales dropdown not show all products) 
- Skip rendering price section in edit-mode, if price is free
> clients/feedback: fix various low hanging feedback

- server/polar/product/service/product.py
- server/tests/product/service/test_product.py
This was a relicate from the time when Products API was "public". Now that it can only be queried by creators to get their own products, this limitation doesn't make any more sense.
> server/product: allow to list without organization_id parameter with user access token

- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/benefits/ClientPage.tsx
- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/products/benefits/ClientPage.tsx
The existing link from Benefits - Ads (`integrating` link) its broken.
> clients/web: fix liking to Ads benefits documentation

- server/polar/order/service.py
- server/tests/fixtures/random_objects.py
- server/tests/order/test_service.py
**Closes:** #4396 
This PR updates the order creation logic triggered by the `invoice.paid` event.
Instead of using the default `NOW()` timestamp for the `created_at` field, we now use the `created` field value ([Stripe doc](https://docs.stripe.com/api/events/object#event_object-created) regarding the `created` field) from the event object, which represents the time the event was generated by Stripe.
> server: use created timestamp value from stripe event

- clients/apps/web/src/components/Landing/Hero/Hero.tsx
Closes #4389 
This PR enables functionality to trigger the `Get Started` button on the Landing page by pressing the `Enter` key.
> clients/landing/hero: Support submission via Enter key

- clients/packages/polarkit/src/components/ui/atoms/Avatar.tsx
Using `new URL(avatar_url).host` to be able to safely determine the
Avatar is from Gravatar.
However, we need to first then check that the string startsWith
`http(s)` to avoid passing local asset paths from NextJS into `new URL`.
> clients: Fix Gravatar check

- server/polar/checkout/service.py
> server/checkout: fix checkout_id not attached to free subscription invoice

- server/polar/license_key/service.py
- server/polar/models/license_key.py
> server/license_key: hide deactivated activations from API output

- clients/.changeset/weak-maps-occur.md
- clients/apps/web/src/components/Checkout/CheckoutForm.tsx
- clients/examples/checkout-embed/index.html
- clients/packages/checkout/src/embed.ts
> Tweak experience while checkout is processing

- clients/apps/web/src/app/(main)/[organization]/portal/authenticate/ClientPage.tsx
> clients: More prominent OTP border in light & dark mode

- clients/.changeset/slow-rabbits-change.md
- clients/apps/web/src/app/(main)/docs/(mdx)/checkout/page.mdx
- clients/packages/checkout/src/embed.ts
Fix #4600
After investigating, it looks like enabling Apple Pay in embed checkout requires two things:
1. Proper permissions policy on the iframe tag (and only the iframe, phew!). *Done*
2. Allowing the hosting domain on Stripe 👇
For now, I chose to go for a simple manual approach with a notice in the docs about how to do that (i.e. contact us and we'll do it manually). If it becomes a common request, it'll be fairly to offer a form to do that in the org settings (Stripe has an API for that).
> Improve support for wallet methods in checkout embed and document procesure

- clients/apps/web/src/components/Accounts/AccountCreateModal.tsx
- clients/apps/web/src/utils/config.ts
- clients/packages/polarkit/src/components/ui/atoms/CountryPicker.tsx
Bug due to bad (legacy) naming of config variable `STRIPE_COUNTRIES`. It reflects countries supported and enabled by us in Stripe Connect Express (for payouts), but sounds like available countries for Stripe overall. So it was used as a filter in checkout too.
Will rename the config variable to avoid future confusion, but wanted to get a quick fix out without turbo/next modifications of env variables.
Now our `CountryPicker` lists all countries by default in the world and only filters by Stripe Connect countries in case `stripeConnectOnly` is set to `true`
> clients: Don't filter countries in checkout by Stripe Connect

- polar.code-workspace
- server/.vscode/settings.json
That damned extension was implicitly using its builtin version instead of our own. The result? The two of them were constantly overriding the cache, so mypy was very often starting from cold!
> dx: fix VS Code mypy configuration to dramatically speed up things

- server/polar/transaction/service/payout.py
- server/tests/transaction/service/test_payout.py
If a refunded payment appear last, or if it's big enough, we can't compensate its outstanding amount with subsequent transfers, leaving us with an outstanding amount.
To solve that, we simply sort the transactions by their transferrable amount, so the negative one appear first and can be compensated by the positive ones appearing after.
> server/transaction: fix payout not working if refunded payments appear at the end

- server/polar/kit/metadata.py
- server/polar/openapi.py
Plays better with Speakeasy + will ease things when we add it to other endpoints
> server/kit: use dedicated schema for metadata query parameter

- server/polar/transaction/service/refund.py
Since we already do tax deduction in the `refund_amount` for refunds
before passing it on for balancing.
> server: Skip tax deduction in balancing refunds

- server/polar/checkout/schemas.py
The risk of keeping the validated type is that, for any reason, our validation constraints change, we break outputting past data that have been properly validated before that.
The good practice is then to avoid any validation when outputting data and trust what we have in DB.
Fix #4890
> server/checkout: set customer_email and customer_name as plain `str` in output schema

- server/polar/custom_field/data.py
> server/custom_field: allow `None` value in custom_field_data output schema

- clients/apps/web/src/app/(main)/[organization]/[repo]/issues/[number]/(create)/ClientPage.tsx
- clients/apps/web/src/app/(main)/[organization]/[repo]/issues/[number]/(create)/page.tsx
The client assumes JSON by default, but here, we expect HTML!
> clients/web: fix issue funding page

- server/polar/checkout/service.py
- server/polar/custom_field/data.py
- server/tests/checkout/test_service.py
> server/checkout: validate required custom fields only at confirmation, not create/update

- clients/.changeset/calm-pianos-allow.md
- clients/packages/checkout/package.json
> clients/packages/checkout: add React 19 as a peer dependency

- clients/apps/web/src/components/Modal/InlineModal.tsx
If click originates from within the modal content, and mouse is dragged outside (like when selecting in an input field or similar), the modal would hide.
We should hide on mousedown instead.
> modals: hide modal on mousedown instead of click

- server/polar/checkout/service.py
- server/tests/checkout/test_service.py
- server/checkout: recompute tax amount if we matched a customer with existing tax ID
> server/checkout: recompute tax amount if we matched a customer with existing tax ID

- server/polar/benefit/schemas.py
- server/polar/license_key/schemas.py
Fixes #5124 
Our previous limit of `50` was a bit arbitrary and set from the POV of
it being devices, e.g iTunes limitations of 5 Apple devices.
However, a customer has a use case where hundreds make sense so
increasing this to `1000`.
Only problem is that our customer portal does not paginate this
resource, but the liklihood of that being used here is low. Better done
than perfect for now.
> server: Increase license key activation limit

- server/polar/notifications/tasks/email.py
Fixes #5196 
Unnecessary & duplicate information was the sender name is `Polar`
> server: Remove `[Polar]` prefix in email

- clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
Received great feedback that putting the minimum and suggested amounts
next to each other made it appear as a `max-min` range input. But by
placing them vertically, the brain resets after the minimum and better
picks up that the next field is different, i.e suggested amount vs.
maximum.
> clients: Clarify PWYW price input

- server/polar/meter/aggregation.py
- server/tests/meter/test_service.py
- server/meter: fix count aggregation computation when no event
> server/meter: fix count aggregation computation when no event

- clients/packages/ui/src/components/atoms/Button.tsx
Avoid cases where Cancellation-button are nested in Forms, and accidentally submits forms.
> Default button-type to 'button'

- clients/apps/web/src/components/Layout/Dashboard/DashboardSidebar.tsx
In this PR, fixed the display of the sandbox banner on dashboard
> fix: dashboard sidebar header

- clients/apps/web/src/utils/metrics.ts
Before with with an account that has just been created (show $NaN in average order value):
After:
This prevents division by zero, which returns NaN.
> fix: show 0 in average order value when no order is placed

- docs/integrate/webhooks/events.mdx
Just saw the [new order webhooks](https://github.com/polarsource/polar/commit/1572eaa21edf354e5bcd24df735d258d3aecfd2c) are not on the overview page
> docs: add oder.paid and oder.updated webhooks to overview

- server/polar/subscription/service.py
- server/subscription: raise lock update lifetime to account for slow Stripe responses
> server/subscription: raise lock update lifetime to account for slow Stripe responses

- server/polar/benefit/benefits/discord.py
- server/polar/benefit/benefits/github_repository.py
- server/benefits: use compute backoff function on benefit logic to avoid thundering herd problem
> server/benefits: use compute backoff function on benefit logic to avoid thundering herd problem

- server/polar/external_event/repository.py
- server/polar/external_event/service.py
- server/tests/external_event/test_service.py
- server/external_event: avoid to throw error if trying to enqueue an existing event
> server/external_event: avoid to throw error if trying to enqueue an existing event

- server/polar/benefit/strategies/license_keys/schemas.py
- server/tests/license_key/test_endpoints.py
- server/benefit: fix benefit license key schema adding validation to non-input schema
> server/benefit: fix benefit license key schema adding validation to non-input schema

- server/polar/checkout/ip_geolocation.py
Always return None for the empty case instead to avoid a complex API in
its usage and errors as seen in the past 24h as a result of an empty
string.
> server: Avoid returning an empty country string from IP lookup

- clients/packages/client/src/v1.ts
Generates the `notification_recipients:read/write` scopes & makes them available in the OAuth scope form.
> clients/sdk-client: generate enums

- server/polar/checkout/service.py
- server/checkout: set description on payment intent so it's more obvious where it comes from on receipt email
> server/checkout: set description on payment intent so it's more obvious where it comes from on receipt email

- server/polar/config.py
When running on **Windows 11**, I encountered this error even after executing the `uv run task emails` command. It didn't work until I fixed the path.
```
PS C:\Coding\polar\server> uv run task db_migrate
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "C:\Coding\polar\server\scripts\db.py", line 8, in <module>
from polar.config import settings
File "C:\Coding\polar\server\polar\config.py", line 304, in <module>
settings = Settings()
^^^^^^^^^^
File "C:\Coding\polar\server\.venv\Lib\site-packages\pydantic_settings\main.py", line 176, in __init__
super().__init__(
File "C:\Coding\polar\server\.venv\Lib\site-packages\pydantic\main.py", line 214, in __init__
validated_self = …
```
> Fix email renderer path for cross-platform compatibility

- clients/packages/ui/src/components/ui/sidebar.tsx
Fixes double scrollbars. The outer scrollbar is unnecessary. Currently it always overflows by `.5rem` (caused by padding-top of the child). As best as I can tell there's never a reason to overflow the outermost wrapper, so fixed via clipping.
> clients/packages/ui: fix double scrollbar

- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/usage-billing/meters/ClientPage.tsx
- clients/apps/web/src/components/Meter/MeterCreationModal.tsx
- clients/apps/web/src/hooks/queries/events.ts
- clients/apps/web/src/hooks/queries/meters.ts
- clients/packages/client/src/v1.ts
- server/polar/event/endpoints.py
- server/polar/event/service.py
- server/tests/event/test_endpoints.py
- server/tests/event/test_service.py
- clients/web: add preview machinery to meter creation
- clients/web: fix infinite query of meters and events
- server/event: add a filter query parameter to events list endpoint
> Add preview capabilities to the meter creation process

- server/polar/meter/aggregation.py
- server/polar/meter/filter.py
- server/polar/models/event.py
- server/tests/meter/test_aggregation.py
- server/tests/meter/test_filter.py
- server/meter: improve filtering support for model properties like timestamp
- server/meter: automatically strip `metadata.` property prefix on filter clause and aggregation
> server/meter: improve filtering support for model properties like timestamp

- clients/apps/web/src/components/Subscriptions/CancelSubscriptionModal.tsx
- clients/packages/client/src/v1.ts
- server/polar/subscription/schemas.py
- server/polar/subscription/service.py
- server/tests/test_sdk.py
- clients/web: fix subscription cancellation payload following schema update
- server/subscription: tweak schema so there is a clear separation between cancel and revoke
> clients/web: fix subscription cancellation payload following schema update

- server/polar/models/discount.py
- server/tests/discount/test_service.py
- server/discount: fix Stripe API error when trying to create discounts with too long names
> server/discount: fix Stripe API error when trying to create discounts with too long names

- render.yaml
- ops: temporarily disable environment groups on new services since Render *still* doesn't support to set environment in their blueprint
> ops: temporarily disable environment groups on new services since Render *still* doesn't support to set environment in their blueprint

- render.yaml
- Revert "ops: temporarily disable environment groups on new services since Render *still* doesn't support to set environment in their blueprint"
> Revert "ops: temporarily disable environment groups on new services since Render *still* doesn't support to set environment in their blueprint"

- clients/apps/web/src/app/checkout/[clientSecret]/confirmation/page.tsx
- clients/apps/web/src/app/checkout/[clientSecret]/page.tsx
- clients/apps/web/src/components/Checkout/Checkout.tsx
- clients/apps/web/src/components/Checkout/CheckoutConfirmation.tsx
- clients/apps/web/src/hooks/checkout.ts
- server/polar/checkout/service.py
- server/tests/checkout/test_service.py
- clients/web: don't immediately redirect to external success URL if checkout is not fully succeeded
- server/checkout: put back in open state after a payment failure to allow customers to retry
> clients/web: don't immediately redirect to external success URL if checkout is not fully succeeded

- server/polar/checkout/service.py
- server/tests/checkout/test_service.py
- server/checkout: create Stripe customer session when creating API session to display saved payment methods
> server/checkout: create Stripe customer session when creating API session to display saved payment methods

- server/polar/customer_meter/endpoints.py
- server/customer_meter: pass external_customer_id parameter properly to service method
> server/customer_meter: pass external_customer_id parameter properly to service method

- server/polar/license_key/service.py
- server/polar/refund/service.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> fix: resolve warnings of logger library

- server/polar/customer_meter/service.py
- server/polar/customer_meter/tasks.py
- server/tests/customer_meter/test_service.py
- server/customer_meter: add a lock around customer meter update to avoid concurrency issues
> server/customer_meter: add a lock around customer meter update to avoid concurrency issues

- server/polar/order/service.py
- server/order: check if product is tax applicable before applying taxes on Stripe invoice
> server/order: check if product is tax applicable before applying taxes on Stripe invoice

- server/polar/integrations/aws/s3/service.py
- server/integrations/aws: fix type hint not available at runtime
> server/integrations/aws: fix type hint not available at runtime

- clients/apps/web/src/components/Benefit/CreateBenefitModalContent.tsx
This PR fixes an #5812 issue where the “Create” button in the CreateBenefitModal was clickable even when subform validation failed.
Enabled mode: `onChange` in the useForm config to ensure real-time isValid updates.
Updated the button to disable itself when `formState.isValid === false`.
Confirmed` useFormContext()` usage in subcomponents triggers correct validation state on setError() calls.
- Prevents submission of incomplete/invalid forms caused by logic in subcomponents (e.g. GitHub repository validation).
- Improves UX by giving users immediate visual feedback.
- Leverages built-in `react-hook-form` APIs for consistency and future maintainability.
1. Open the “Create Benefit” modal.
2. Select a GitHub repository benefit.
3. Simulate an invalid state (e.g., selecting a personal …
> fix(client): disable "Create" button when form has validation errors

- server/migrations/versions/2025-06-02-1629_create_payout.py
- server/migrations: make payout processor_id non unique
- clients/web: re-add account status banner
- clients/web: reorganize payouts page and adapt to new API
- server/payout: expose fees
- server/payout: add a list endpoint
- server/payout: implement dedicated Payout model and module, refactor logic into it
> server/migrations: make payout processor_id non unique

- server/polar/checkout/service.py
- server/tests/checkout/test_service.py
- server/checkout: prevent to create a new subscription if the existing one is past due
> server/checkout: prevent to create a new subscription if the existing one is past due

- server/polar/worker.py
- server/worker: temporary disable LogfireMiddleware because I suspect it's the one causing memory leaks
> server/worker: temporary disable LogfireMiddleware because I suspect it's the one causing memory leaks

- server/polar/checkout/service.py
- server/checkout: tweak handle_stripe_success to ignore non-recurring product even if checkout already succeeded
> server/checkout: tweak handle_stripe_success to ignore non-recurring product even if checkout already succeeded

- server/polar/kit/repository/base.py
- server/polar/meter/service.py
- server/polar/middlewares.py
- server/polar/worker/__init__.py
- server/tests/fixtures/worker.py
- server/worker: revamp JobQueueManager with a context manager
- server/meter: tweak create_billing_entries memory usage
- server/worker: manage enqueued job as a decorator of actor function instead of middleware
> server/worker: revamp JobQueueManager with a context manager

- server/polar/checkout/service.py
- server/polar/models/subscription.py
- server/tests/subscription/test_service.py
- server/subscription: fix product upgrade when meters are the same
- server/checkout: short-circuit handle_payment_success with recurring products
> server/subscription: fix product upgrade when meters are the same

- .gitignore
- server/polar/invoice/generator.py
- server/tests/invoice/test_generator.py
- server/invoice: fix PDF generation when customer/seller name doesn't fit on a single line
> server/invoice: fix PDF generation when customer/seller name doesn't fit on a single line

- clients/apps/web/src/components/Landing/SDKs.tsx
The current hover state for SDK cards is subtle and lacks visual consistency height, also no contrast in dark mode. This affects usability and discoverability.
| Before |
|--------|
| <img width="1440" alt="455001118-8438394f-bebf-495a-8045-8e5fedabe077" src="https://github.com/user-attachments/assets/981757c7-d11c-4092-a552-6dd0dac494aa" /> |
---
- Add contrast for hover background in dark mode.
- Apply same height for all hovers.
- Add slight rounded borders for design consistency.
| After |
|-------|
| <img width="1433" alt="Screenshot 2025-06-13 at 20 23 59" src="https://github.com/user-attachments/assets/714f80d7-ab46-4682-93f4-1521ddfc84b3" /> |
> fix: hover state landing sdks

- clients/apps/web/src/components/Products/CreateProductPage.tsx
As we've changed how our pricing logic works with the API, a lot of people have broken, persisted product drafts saved in their localStorage. When we apply it, the form values becomes incompatible.
As the form persistence gives almost no value, I ripped it out.
> clients/product: remove error-prone form persistance which adds little value

- DEVELOPMENT.md
- dev/setup-environment
This mainly PR mainly adds instructions on how to properly setup Stripe integration. Aside of that I modify 2 things:
- Add https in the front of `--backend-external-url`, if not added the integration fails
- Modify the url to create a new app to `https://github.com/settings/apps/new` as new contributors are not part of Polar organization usually.
> docs: update setup instructions for GitHub App and add Stripe setup details

- server/polar/customer_portal/endpoints/downloadables.py
Not intended to be used as an API endpoint. It's the URL that our list
endpoint yields to download the file itself using the presigned token
that is not exposed directly.
> server: Hide downloadable endpoint

- server/polar/oauth2/endpoints/oauth2.py
Removed APITag.documented from the 5 client management endpoints (/oauth2/, /oauth2/register/*) as requested in issue #6018. 
These endpoints remain fully functional for dashboard use but won't clutter the public API documentation.
Standard OAuth2 endpoints (/token, /revoke, /introspect, /userinfo) stay documented as they're part of the public API.
Clean solution - no breaking changes, just cleaner docs that follow industry standards.
> OAuth2 client CRUD endpoints have been hidden

- clients/apps/web/src/components/Orders/DownloadInvoice.tsx
Quick fix for #6111 
This UX is suboptimal. An improvement could be falling back to an in-app dialog titled "Your invoice is ready to download" and another download button which is a simple `<a download>` to the pre-signed URL.
> Fallback to same-tab navigation when window.open fails

- docs/features/customer-portal.mdx
Docs example lack `server` parameter, which is required by TS. I expect it to be a mistake, as it's not required in any other method, but in case it's not, here is docs fix
> fix: lack of required `server` parameters in docs

- clients/packages/ui/src/components/atoms/Avatar.tsx
- server/polar/customer/schemas/customer.py
Fixes #5795 
The current logic relied on always rendering the initials, and rendering the avatar on top of that if it was available. Because Gravatar can return a blank image when no avatar matches, this was a nice fallback mechanism.
However, that breaks when you host a transparent PNG on Gravatar as your avatar.
With this change, I try to make the logic a bit more straight-forward:
- If there's not an image, render initials
- If there's an image, attempt to render it
- If the image loading fails, fall back to rendering initials
We can swap the `d=` parameter on Gravatar to `404` to accommodate this behavior.
The only drawback would be a small FOUC where the initials render only when Gravatar returns a 404, which could be a reason not to merge this. In my tests it's not annoying—as …
> Use initials as fallback mechanism in avatar

- clients/apps/web/src/styles/globals.scss
The #polar-bg-gradient had a fixed size making e.g. the login confirmation page overflow in the y-direction.
The overflow would generally only happen on a full page refresh. On normal Next.js navigation you would mostly not see the overflow.
We now simply size and position the background instead of making a large HTML element.
> polar-bg-gradient: Don't make page overflow

- .devcontainer/devcontainer.json
The original devcontainers-contrib repo has disappeared, which blocks codespace installation.
The pnpm installation is done anyway by devcontainers/features/node:1.
See: https://github.com/devcontainers/features/tree/main/src/node
> devcontainer: rely on devcontainers/features/node:1 to install pnpm

- server/polar/email/email_templates/base.html
- server/tests/notifications/testdata/test_MaintainerCreateAccountNotificationPayload.html
- server/tests/notifications/testdata/test_MaintainerNewPaidSubscriptionNotification.html
- server/tests/notifications/testdata/test_MaintainerNewProductSaleNotification.html
I bought the (incredibly well-executed) Devouring Details course and got this order confirmation:
| **Gmail** | **Mail.app** |
|-----------|-------------|
| <img width="1066" height="683" alt="image" src="https://github.com/user-attachments/assets/0594a4ab-0db1-4bce-a851-3e0fc4c676f1" /> | <img width="973" height="652" alt="image" src="https://github.com/user-attachments/assets/4f4bf1d9-dd68-4f97-a310-6d197617f918" /> |
Figured that could be a bit better, or (I'm sorry) time to devour some details.
This PR fixes:
- Custom font not loading properly in Gmail
- Faux bold issues in Mail.app
- Use organization name instead of slug
Resulting in:
| **Gmail** | **Mail.app** |
|-----------|-------------|
| <img width="1066" height="681" alt="image" …
> Improve email styling

- clients/apps/web/src/app/(main)/dashboard/(create)/create/ClientPage.tsx
- clients/apps/web/src/app/(main)/dashboard/(create)/create/page.tsx
- clients/apps/web/src/components/Layout/Dashboard/DashboardSidebar.tsx
- clients/apps/web/src/components/Onboarding/OrganizationStep.tsx
- clients/apps/web/src/components/Onboarding/ProductStep.tsx
This PR:
- Removes the "Back to Dashboard"-button that was shown during onboarding. It still shows when the user creates their second organization.
- Renames "Cancel"-button in the product step of the onboarding to "Skip"
> Onboarding: Don't show "Back to Dashboard" during onboarding

- clients/packages/ui/src/components/atoms/Avatar.tsx
When an image is already in the cache, the `onload` on an `<img>`-tag might not be called. To get around that we look at `img.complete` as well. 
This unfortunately becomes quite complicated as we need a ref to the `<img>` element.
> Avatar: Handle images in browser cache

- clients/packages/ui/src/components/atoms/datatable/DataTablePagination.tsx
The pagination pushes past the viewport width on mobile, leading to that annoying zoom out / horizontal scroll mixture.
I did some flexbox kungfu to wrap the pagination on two lines in a way that makes sense to me.
Curious what you think, @emilwidlund, would understand if you hate it too, haha 😁 
<details>
<summary>Current version for reference</summary>
</details>
> (experimental) Fix pagination on mobile

- server/polar/checkout/service.py
- server/tests/checkout/test_service.py
Fixes #6183 
Regular payments (is_payment_required is True): Only require full addresses if require_billing_address is True or is_business_customer is True
Setup intents (is_payment_required is False but is_payment_setup_required is True): Require full addresses for tax calculation
Free products (is_payment_required is False and is_payment_setup_required is False): Don't require full addresses
> Issue-6183: check validity of tax address

- .github/workflows/test_server.yaml
Potential fix for [https://github.com/polarsource/polar/security/code-scanning/62](https://github.com/polarsource/polar/security/code-scanning/62)
To fix the issue, we should add a `permissions` block to explicitly define the least privileges required for the workflow. Since the workflow involves tasks such as checking out code, running tests, and setting up environments, `contents: read` should suffice for most steps. For any specific tasks requiring write access (e.g., pushing updates), we can add granular permissions at the job level. The `permissions` block will be added at the workflow level to apply to all jobs.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 62: Workflow does not contain permissions

- .github/workflows/test_client.yaml
Potential fix for [https://github.com/polarsource/polar/security/code-scanning/59](https://github.com/polarsource/polar/security/code-scanning/59)
The fix involves adding a `permissions` key to the workflow. The `contents: read` permission is sufficient for most workflows that only need to access the repository's contents without making modifications. In case the individual jobs have specific permission needs (e.g., `pull-requests: write`), those can be defined at the job level.
To resolve the issue:
1. Add a `permissions` block at the workflow level to apply minimal permissions (`contents: read`) to all jobs.
2. If any job requires additional permissions, define those explicitly within the job's configuration.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …
> Potential fix for code scanning alert no. 59: Workflow does not contain permissions

- .github/workflows/chromatic.yaml
Potential fix for [https://github.com/polarsource/polar/security/code-scanning/57](https://github.com/polarsource/polar/security/code-scanning/57)
To fix the issue, we need to add a `permissions` block to the workflow. Since the workflow involves reading the repository contents and interacting with Chromatic, it should have `contents: read` permission at a minimum. If additional permissions are required for specific steps, they should be added explicitly and scoped narrowly. The block can be placed at the root of the workflow to apply globally or inside the job to apply specifically to `chromatic-deployment`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 57: Workflow does not contain permissions

- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/sales/ClientPage.tsx
- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/sales/checkouts/ClientPage.tsx
- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/sales/subscriptions/ClientPage.tsx
- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/members/ClientPage.tsx
- clients/apps/web/src/components/Customer/CustomerContextView.tsx
- clients/apps/web/src/components/Shared/DetailRow.tsx
- clients/packages/ui/src/components/atoms/datatable/DataTable.tsx
- Organization members: Use our own `<Input>` instead of `<input>`
- Orders table: Stop emails from overflowing into amount column
- Order+Subscription+Checkout tables: Stop email filling into next column
- DataTable: Allow setting `size` on columns
- Order+Subscription+Checkout tables: Make status+date columns smaller
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tbody>
<tr>
<td><img width="449" height="212" alt="Screenshot 2025-07-21 at 09 11 03" src="https://github.com/user-attachments/assets/b24004c7-85c0-4f1b-9f42-bf92199784f1" /></td>
<td><img width="440" height="223" alt="Screenshot 2025-07-22 at 10 42 15" src="https://github.com/user-attachments/assets/acdb2a34-5311-476e-b8f0-32b79678b6ec" /></td>
</tr>
<tr>
<td><img width="375" height="265" alt="orders_before" …
> UI fixups: Table and details column sizes

- server/polar/config.py
- server/polar/order/repository.py
- server/polar/order/service.py
- server/polar/order/tasks.py
- server/polar/payment/repository.py
- server/polar/subscription/service.py
- server/tests/integrations/stripe/test_payment.py
- server/tests/order/test_service.py
- server/tests/order/test_tasks.py
- Add a new worker to process dunning orders
- Handle the dunning process:
- Retry the payment up to 4 times. If it fails, the subscription is marked as cancelled.
- If any of those fail, the subscription is marked as active and the benefits are granted again.
> feat: implement retry follow ups

- server/polar/metrics/queries.py
- server/tests/fixtures/random_objects.py
- server/tests/metrics/test_service.py
Fix #6257
- server/metrics: consider ends_at if available when querying active subscriptions
> server/metrics: consider ends_at if available when querying active subscriptions

- server/emails/src/emails/subscription_cancellation.tsx
Fixes #6242
Added conditional rendering to the subscription_cancellation.tsx email template so the entire benefits section only appears when there are actual benefits to display.
> hidden benefit section if benefits is not present

- server/emails/package.json
Hi, thank you for the project!
This pr aims to fix following warning after running `uv run task emails`:
Because pnpm v10 blocks lifecycle scripts by default, allowing only those listed in onlyBuiltDependencies to execute their postinstall scripts.
> fix(server): missing only built dependencies

- server/polar/kit/email.py
Previously the error message would be
"value is not a valid email address: <REASON>"
Notwit'll say:
"<EMAIL> is not a valid email address: <REASON>"
> Login: Improve invalid email address error message

- clients/apps/web/src/components/Benefit/MeterCredit/BenefitForm.tsx
- clients/apps/web/src/components/Meter/CreateMeterModalContent.tsx
- clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
Fixes #6092
_Select a meter_ opens an empty select dropdown makes this basically a dead end in the onboarding flow.
Added a brief alert that lets you create a meter straight from the metered pricing & meter credits sections.
**Metered pricing**
**Meter credits**
From there a new modal opens to create a new meter directly:
Upon completion, the new meter is selected and you can continue.
**Usefulness in terms of UX**: This improves on the current version, which is effectively a dead end. However, I wonder if the whole setup is a bit too technical. You're basically required to set up event ingestion too for this to make sense. This can't/won't be the case in the context of onboarding, which is also I didn't include e.g. the events preview from the in-app meter configuration.  
This makes me …
> Configure meters straight from onboarding

- server/polar/customer_portal/endpoints/license_keys.py
- server/polar/license_key/service.py
- server/tests/license_key/test_endpoints.py
Issue #6302
Updated the error message to be more descriptive and actionable, educating integrators that they should use the `/validate` endpoint instead.
@frankie567 kindly review
>  Issue: #6302 - license key validation

- server/tests/subscription/test_service.py
The problem is that the test is failing because we only allow 3 months:
1st cycle (2nd month):
- started_at: 2025-07-31 09:47:07
- current_period_start: 2025-08-30 09:47:07
- end_at: 2025-10-31 09:47:07
- expired: False ✅
2nd cycle (3rd month):
- started_at: 2025-07-31 09:47:07
- current_period_start: 2025-09-30 09:47:07
- end_at: 2025-10-31 09:47:07
- expired: False ✅
3rd cycle (4th month):
- started_at: 2025-07-31 09:47:07
- current_period_start: 2025-10-30 09:47:07
- end_at: 2025-10-31 09:47:07
- expired: False ❌ (should be True)
The problem is clear now! In the 3rd cycle, current_period_start is 2025-10-30 but end_at is 2025-10-31. So 2025-10-30 >= 2025-10-31 is False.
This is happening because of how relativedelta handles month boundaries. When we started on July 31st and add 3 …
> feat: fix test on subscription edge cases

- docs/changelog/recent.mdx
**Context**
A user reached out to us asking for all changes be fetch-able through RSS.
Mintlify said (in a support case with them) that only the latest update is being shown in RSS today as we do not have rss: true set in the configuration of the frontmatter (as follows):
"Thanks for reaching out - we only update the XML feed after it's created for your docs (by adding rss: true to the front matter of your page).
That's likely why you're only seeing the newer updates!"
**Solution**
Add `rss: true` to the changelog/recent.mdx page
> Changelog: Ability to load all changes to RSS

- sdk/overlays/security.yml
I need to regenerate the SDK and update the OpenAPI spec afterwards.
> sdk/overlays: fix empty security scheme being removed from unauthenticated endpoints

- clients/apps/web/src/app/layout.tsx
- clients/apps/web/src/components/Landing/Adapters.tsx
- clients/apps/web/src/components/Landing/Benefits.tsx
- clients/apps/web/src/components/Landing/Checkout.tsx
- clients/apps/web/src/components/Landing/Hero/Hero.tsx
- clients/apps/web/src/components/Landing/LandingPage.tsx
- clients/apps/web/src/components/Landing/Testimonials.tsx
- clients/apps/web/src/components/Landing/Usage.tsx
- clients/apps/web/src/components/Landing/molecules/SplitPromo.tsx
- clients/apps/web/src/components/SyntaxHighlighterShiki/SyntaxHighlighterClient.tsx
- clients/packages/ui/src/components/atoms/Avatar.tsx
Hi team 👋 
First off, huge thanks to the Polar team for building such a great product and saving time from people's lives. Better-Auth + Polar is truly a chef’s kiss! 🔥 
While exploring the landing page, I noticed several opportunities to reduce bandwidth costs, improve performance, and boost the chances of retaining potential customers. After some optimizations, we went from:
* Before: 101 requests, 4.9 MB transferred
* After: 54 requests, 1.2 MB transferred (📉 75% reduction)
-----
**Changes & Rationale**
1. 🧹 Removed unused preconnects  
- There were preconnect links to `fonts.gstatic.com` and `fonts.googleapis.com`, but I couldn’t find any font usage. May have been leftovers.
2. 🖼️ Optimized background images  
- Several large images (some ~800 KB) were loaded as CSS background images, …
> feat(web): improve landing page performance

- server/polar/discount/schemas.py
Fix #6428
- server/discount: add a maximum to amount, to avoid Stripe error
> server/discount: add a maximum to amount, to avoid Stripe error

- server/polar/config.py
- server/polar/invoice/generator.py
- server/tests/invoice/test_generator.py
Fixes a case where the seller address would overlap with the line item table in cases where the right-side seller address was very short.
> Invoice: Fix case where right-side seller is very short

- server/pyproject.toml
- server/scripts/db.py
This task tries to auto-fix conflicting migrations by reparenting the
head migration from this branch on top of the head migration on the
`main` branch.
> tasks: Add `db_reparent` task

- clients/apps/web/src/utils/testdata.ts
- clients/packages/client/src/v1.ts
- server/polar/enums.py
- server/polar/product/schemas.py
- server/polar/product/service.py
- server/polar/subscription/endpoints.py
- server/polar/user/schemas.py
- server/tests/product/test_endpoints.py
Add daily and weekly Subscription recurrence intervals.
> [Internal-only] Add daily and weekly subscription intervals [part 1, backend]

- server/docker-compose.yml
- server/polar/order/service.py
- server/tests/order/test_service.py
Fix #6622
- server/order: fix subscription creation order when metered prices are involved
- server: remove deprecated version field in docker-compose.yml
> server/order: fix subscription creation order when metered prices are involved

- server/polar/order/service.py
- server/tests/fixtures/random_objects.py
- server/tests/meter/test_service.py
- server/tests/order/test_service.py
Fix #6625
- server/order: reset subscription meters after issuing an update invoice
> server/order: reset subscription meters after issuing an update invoice

- clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/usage-billing/meters/ClientPage.tsx
Previously, when archiving or unarchiving a meter you'd get a flash of
the empty state (instructions on how to use meters).
This commit makes sure we show the loading state instead.
> ui[meters]: Fix weird flash of empty state

- clients/apps/web/src/components/Settings/Webhook/WebhookDeliveriesTable.tsx
Adds a "Sent At" timestamp column to the webhook deliveries table, allowing users to see when webhook deliveries were sent without having to expand each row.
- Added `FormattedDateTime` import for proper timestamp formatting
- Added new "Sent At" column displaying `delivery.created_at` 
- Enabled sorting on the `created_at` field for better usability
- Updated `getCellColSpan` calculation from 4 to 5 columns for expanded rows
- Used short date and time format for optimal readability
**Before**: Users had to expand each webhook delivery row to see the "Sent at" timestamp
**After**: Timestamp is immediately visible in the main table as a dedicated column
Fixes #6316
> Add 'Sent At' timestamp column to webhook deliveries table

- .github/workflows/deploy-environment.yml
- ops: fix Vercel build in CI
- Potential fix for code scanning alert no. 86: Workflow does not contain permissions
- ops: disable automatic Vercel deploy on main branch
- ops: revamp deploy workflow
> ops: fix Vercel build in CI

- server/polar/auth/middlewares.py
- server/polar/auth/service.py
- server/auth: make sure auth tokens are ASCII before trying to handle them
> server/auth: make sure auth tokens are ASCII before trying to handle them

- server/polar/checkout/service.py
- server/tests/checkout/test_endpoints.py
- server/tests/checkout/test_service.py
Updates the checkout creation logic to correctly prioritize the `minimum_amount` from the product's price settings before falling back to the default.
Fixes #6450
> fix(checkout): Use minimum amount for PWYW placeholder

- server/polar/benefit/strategies/discord/service.py
- server/polar/benefit/strategies/github_repository/service.py
- server/polar/models/benefit_grant.py
- server/tests/benefit/grant/test_service.py
- server/benefit/strategies: keep account_id in GitHub/Discord benefit after revoke
- server/benefit/grant: reset revoked_at when granting a benefit again, even if there is an action required error
> server/benefit/strategies: keep account_id in GitHub/Discord benefit after revoke

- server/polar/subscription/service.py
Fix #6853
- server/subscription: trigger subscription.updated webhook after creation
> server/subscription: trigger subscription.updated webhook after creation

- server/polar/discount/service.py
- server/tests/discount/test_service.py
Fix #6879
- server/discount: fix attributeerror when trying to update field not applicable to current discount
> server/discount: fix attributeerror when trying to update field not applicable to current discount

- clients/apps/web/src/components/Landing/LandingLayout.tsx
When login modal was opened from the sidebar, any button inside the modal wouldn't work (see video).
This patch moves the modal outside the sidebar, and closes the sidebar to get the full focus to the modal.
Closes https://github.com/polarsource/polar/issues/6889
https://github.com/user-attachments/assets/4cc9ea04-d46f-4896-8f37-b3feba931ad9
> fix(frontpage/landing): close sidebar when login modal is opened

- server/polar/account/schemas.py
- server/polar/checkout/schemas.py
- server/polar/checkout/service.py
- server/polar/config.py
- server/polar/customer/schemas/customer.py
- server/polar/customer_portal/schemas/customer.py
- server/polar/kit/address.py
- server/polar/order/schemas.py
- server/polar/order/service.py
- server/tests/checkout/test_service.py
- server/tests/checkout/test_tax.py
- server/tests/customer_portal/service/test_customer.py
- server/tests/invoice/test_generator.py
- server/tests/invoice/test_service.py
- server/tests/order/test_service.py
- server/tests/payout/test_service.py
- server/kit/address: add an AddressInput variant to handle restricted countries we have in DB + add Speakeasy enum
- Reapply "server/kit/address: use defined enum for country field"
> server/kit/address: add an AddressInput variant to handle restricted countries we have in DB + add Speakeasy enum

- clients/apps/web/src/app/(main)/[organization]/portal/Navigation.tsx
**Related Issue:** Fixes #6864 (Customer Portal navigation visible on request/authenticate pages)
Hide the customer portal navigation on:
- `/:organization/portal/request`
- `/:organization/portal/authenticate`
Keep navigation visible for all other customer portal routes.
- These routes are pre-auth entry points and don’t need the sidebar.  
- On mobile, the nav collapsed into a dropdown with no active item, which looked broken.  
- Improves UX consistency for the authentication flow.
- Updated `Navigation.tsx` to return `null` when `usePathname()` ends with `/portal/request` or `/portal/authenticate`.  
**Test Instructions:**
1. Go to `/:organization/portal/request` → verify no sidebar or mobile dropdown is shown.  
2. Submit an email → you should be redirected to …
> Fix for issue #6864: hide navigation on Customer Portal sign-in page

- server/polar/license_key/service.py
- server/tests/license_key/test_endpoints.py
**Related Issue**: Fixes #7042
Adds a check for `expires_at` when activating a license key
> Check for `expires_at` when activating license keys

- server/polar/refund/service.py
Fix #7070
- server/refund: don't try to revert tax transaction if no tax has been collected
> server/refund: don't try to revert tax transaction if no tax has been collected

- clients/apps/web/src/middleware.ts
Related to Sentry DASHBOARD-1FH
> Bypass middleware on `/ingest` routes

- clients/apps/web/vercel.json
Follows [this guide](https://www.mintlify.com/docs/deploy/vercel#generate-rewrites), but changed `/_mintlify/api/request` into `/_mintlify/api/:path` because Vercel logs `/_mintlify/api/v1/e` as well, so we probably want to capture that too.
> Set up rewrites according to Mintlify docs

- server/polar/kit/repository/base.py
Fix #7130
- server/kit/repository: don't fail when updating a field not tracked by SQLAlchemy
> server/kit/repository: don't fail when updating a field not tracked by SQLAlchemy

- server/polar/logging.py
- server/polar/worker/__init__.py
- server/polar/worker/scheduler.py
- server/worker: put logfire middleware first so it wraps retry messages inside the span
- server/worker: improve Logfire reports for scheduler process
> Tweak Logfire reporting

- server/polar/worker/__init__.py
- Revert "server/worker: put logfire middleware first so it wraps retry messages inside the span"
> Revert "server/worker: put logfire middleware first so it wraps retry messages inside the span"
