polarsource/polar

clients/apps/chrome-extension/src/api.ts
clients/apps/chrome-extension/src/index.tsx
server/polar/auth/service.py

- chrome-extension: Fix exception of running .forEach() on error response
- chrome-extension: Remove import of non-existant index.css
- chrome-extension: Use Authorization header vs. query string

Fix Chrome Extension

---

clients/apps/chrome-extension/src/manifest.template.json

- chrome-extension: Update description - public in Chrome Store (?)
- chore/chrome-extension: Prettier on manifest

Update Chrome Extension meta info

---

clients/packages/polarkit/src/components/CountryPicker.tsx
clients/packages/polarkit/src/config.ts

Limited during our alpha to EU, US, CA & GB.
Fixes #460

Update Stripe countries supported

---

server/migrations/versions/2023-05-16_issue_polling_columns.py
server/migrations/versions/2023-05-17_issue_polling_columns.py
server/migrations/versions/2023-05-17_merge_a6e6e5f050e0_and_240cf2f2c2f4.py
server/polar/integrations/github/service/api.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/reference.py
server/polar/integrations/github/tasks/issue.py
server/polar/models/issue.py
server/scripts/github.py

Periodically poll issues

---

clients/apps/web/src/components/Dashboard/IssueListItem.tsx

Fix a where the issue pledged to is gone from thank you page

---

clients/apps/web/src/pages/_app.tsx

clients/app: build with strict typescript

---

clients/apps/chrome-extension/package.json
clients/apps/web/package.json
clients/packages/polarkit/package.json
clients/pnpm-lock.yaml

clients: update to typescript 5

---

clients/apps/web/src/components/Website/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Website/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Website/Pledge/index.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/index.tsx
clients/apps/web/tailwind.config.js
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
clients/packages/polarkit/src/components/pledge/RepositoryCard.tsx
clients/packages/polarkit/src/components/ui/Cards/WhiteCard.tsx
clients/packages/polarkit/src/components/ui/PrimaryButton.tsx

Pledge page polish

---

clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Pledge/PledgeNow.tsx

Fixes #452
In this solution, the button still disappears if the mouse leaves the window, but the modal stays

Fix pledge overlay disappearing when mouse leaves window

---

.github/workflows/test_client.yaml
clients/apps/web/.gitignore
clients/apps/web/.storybook/main.ts
clients/apps/web/package.json
clients/apps/web/src/components/Dashboard/Search.tsx
clients/apps/web/src/components/Dashboard/Sidebar.tsx
clients/apps/web/src/stories/NotificationSettings.stories.tsx
clients/apps/web/src/stories/OnboardingConnectReposToGetStarted.stories.ts
clients/apps/web/src/stories/Sidebar.stories.ts
clients/apps/web/tsconfig.json
clients/pnpm-lock.yaml

Enable strict TypeScript!

---

clients/apps/web/src/components/Dashboard/Search.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/stories/Sidebar.stories.ts

clients/sidebar: hide tabs if there is only one

---

clients/apps/web/.storybook/main.ts
clients/apps/web/src/components/Dashboard/Gatekeeper/AcceptTerms.tsx
clients/apps/web/src/components/Dashboard/Gatekeeper/InviteOnly.tsx
clients/apps/web/src/stories/GatekeeperAcceptTerms.stories.ts
clients/apps/web/src/stories/GatekeeperInviteOnly.stories.ts
clients/apps/web/src/stories/Switch.stories.tsx
clients/packages/eslint-config-custom/index.js
clients/packages/polarkit/src/components/ui/PrimaryButton.tsx

- clients/stories: re-enable addons
- clients/ThinButton: loading spinner styling improvements
- clients/stories: add gatekeeper components

Add Gatekeeper components to Storybook

---

server/polar/integrations/github/service/repository.py
server/polar/integrations/github/tasks/webhook.py

- github/webhook: Get rid of commented-out code
- github/webhook: Explicit sync on repo installation vs. all updates

Explicit issue sync on installation only

---

server/polar/integrations/github/endpoints.py
server/polar/integrations/github/tasks/webhook.py

server/github: handle repository events

---

clients/apps/web/src/components/Pledge/ThankYouUpsell.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/status.tsx
clients/apps/web/src/stories/PledgePageThankYouUpsell.stories.ts
clients/apps/web/src/stories/testdata.ts

And created a storybook story for it :-)

clients: move the post-pledge thank you message to a separate component

---

clients/apps/chrome-extension/src/auth.ts
clients/apps/chrome-extension/src/manifest.template.json
clients/apps/chrome-extension/src/service-worker/soft-nav.ts
clients/apps/web/src/components/Auth/Login.tsx
clients/apps/web/src/hooks/auth.ts
clients/apps/web/src/pages/dashboard/settings/extension.tsx
clients/apps/web/src/pages/index.tsx
server/polar/auth/service.py
server/polar/integrations/github/endpoints.py

Chrome Extension: Improve authentication

---

clients/apps/web/src/components/Dashboard/SetupAccount.tsx

Stripe Connect: Don't stop spinner until we redirect to Stripe

---

clients/apps/web/src/components/Dashboard/Account/Topbar.tsx

Hide Stripe onboarding if no public repos

---

server/polar/integrations/github/tasks/badge.py
server/polar/repository/service.py

server/badge: do not trigger badge jobs for private repositories

---

clients/apps/web/src/components/Settings/Badge/index.tsx

webapp/settings: don't count additions in private repos

---

clients/apps/chrome-extension/tsconfig.json
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/stories/IssueListItem.stories.ts
clients/packages/polarkit/src/components/Issue/Reference.tsx
clients/packages/polarkit/src/components/Issue/index.ts
clients/packages/polarkit/src/components/Issue/markdown.tsx

- Support the first word being highlighted
- Support highlights in PR titles
Fixes #541

Markdown Highlights Fixes

---

server/polar/dashboard/schemas.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/tasks/badge.py
server/polar/integrations/github/tasks/webhook.py
server/polar/issue/service.py
server/polar/kit/db/models/mixins/active_record.py
server/polar/models/issue.py
server/tests/fixtures/predictable_objects.py
server/tests/fixtures/random_objects.py
server/tests/issue/test_service.py

Badge ordering fixes

---

clients/apps/web/src/pages/_document.tsx
clients/apps/web/tailwind.config.js

Poppins is the new display/brand font already used on the landing page.

Replace Lexend font with Poppins

---

server/polar/dashboard/endpoints.py
server/polar/issue/service.py
server/polar/models/issue.py
server/tests/fixtures/random_objects.py
server/tests/issue/test_service.py

Dependencies self pledges only

---

clients/apps/chrome-extension/src/index.tsx
clients/apps/chrome-extension/src/manifest.template.json

Fixes #547 
When this is merged, I'll publish a new version of the extension to the Chrome Store.

chrome-extension: cleanup previous embeds on navigation

---

clients/apps/web/src/components/Dashboard/LoadingScreen.tsx

https://github.com/polarsource/polar/assets/1426460/5cbe7ad2-fbe7-4cfa-b325-a18e0ee5c987
https://github.com/polarsource/polar/assets/1426460/93ba7d46-551a-4227-bd9e-97d03b71d497

Fancy loader

---

server/polar/integrations/github/badge.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/tasks/badge.py
server/tests/integrations/github/test_badge.py

server/badge: allow removal of badge when not in auto mode

---

clients/apps/web/src/components/Notifications/Popover.tsx
clients/apps/web/src/stories/LoadingScreen.stories.ts
clients/apps/web/src/stories/Notification.stories.ts
clients/apps/web/src/stories/NotificationList.stories.ts
clients/apps/web/src/stories/testdata.ts

client/notifications: implement PledgerPledgePending

---

clients/apps/web/src/components/Dashboard/Gatekeeper/AcceptTerms.tsx

client/web: hook up AcceptTerms button

---

clients/apps/web/src/components/Dashboard/Gatekeeper/Gatekeeper.tsx
clients/apps/web/src/pages/dashboard/settings/[organization]/index.tsx

Fixes #624
It's an ugly fix, but it works.
Ideally we'd move to support authenticated server side rendering for pages like this one.

clients/settings: cleanup and hydration fix

---

render.yaml

render: add secondary worker deploying from pre built docker image

---

server/polar/integrations/github/tasks/utils.py

More logging when org or repo not found in github webhooks

---

server/poetry.lock
server/pyproject.toml

It contains some nice fixes by yours truly. :-)

server: update githubkit to 0.10.5

---

server/polar/integrations/github/service/dependency.py

Since we ask for org and repo with less permissions, we overwrite essential columns.
Work for #653

Don't overwrite org and repo if they exist when parsing dependencies

---

server/polar/integrations/github/service/repository.py
server/polar/organization/service.py
server/tests/integrations/github/tasks/cassettes/test_integration/test_installation_no_notifications.yaml

Paginate repositories in installation

---

clients/apps/web/src/components/Dashboard/Account/BalanceBadge.tsx
clients/packages/polarkit/src/api/client/models/AccountRead.ts
clients/packages/polarkit/src/utils/index.ts
server/polar/account/endpoints.py
server/polar/account/schemas.py
server/polar/account/service.py
server/polar/integrations/stripe/service.py

Support balances in any currency

---

server/polar/backoffice/endpoints.py

To be able to manually trigger syncs for #653

server/backoffice: add API to trigger organization resyncs

---

server/polar/integrations/github/service/organization.py
server/polar/models/organization.py

Fixes #701
Extracted from #694

server/github: fixes for un-deleting orgs

---

server/polar/models/repository.py

Make sure deleted_at is reset when repo is upserted

---

clients/apps/web/src/pages/dashboard/[organization]/index.tsx
server/polar/integrations/stripe/endpoints.py

Show toast when connecting Stripe account

---

clients/apps/web/src/components/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/index.tsx

Posthog pledge events

---

server/polar/config.py
server/polar/integrations/github/client.py
server/polar/issue/endpoints.py

Use a polar-sh github user for anonymous requests

---

clients/apps/chrome-extension/src/components/AuthorizationBanner.tsx
clients/apps/chrome-extension/src/index.tsx

I noticed that the chrome extension could use some love. 
**Desktop View**
**Mobile View**

style(chrome-extension): improve look and responsiveness

---

clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx

clients/IssueListItem: add space between references

---

clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/apps/web/src/stories/testdata.ts

This keeps snapshots consistent over time

clients: use relative dates in testdata

---

clients/apps/web/src/components/Dashboard/Gatekeeper/Gatekeeper.tsx

Fixes #726 
It's not a config, but I believe that this is easier to maintain. :-)

apps/dashboard: allow signup by anyone

---

clients/apps/web/src/components/Dashboard/Finance/Finance.tsx
clients/apps/web/src/stories/FinancePage.stories.tsx
server/polar/account/endpoints.py
server/polar/account/schemas.py
server/polar/integrations/stripe/service.py

Only show goto-action for the Stripe admin

clients/finance: stripe banner tweaks

---

server/polar/config.py
server/polar/issue/schemas.py
server/polar/issue/service.py
server/polar/kit/db/models/mixins/active_record.py
server/polar/kit/db/models/mixins/serialize.py
server/polar/kit/extensions/sqlalchemy/types.py
server/polar/kit/jwt.py
server/polar/models/repository.py
server/polar/models/user.py
server/polar/notifications/sender.py
server/polar/notifications/tasks/email.py
server/polar/organization/endpoints.py
server/polar/organization/schemas.py
server/polar/organization/service.py
server/polar/pledge/endpoints.py
server/polar/pledge/service.py
server/polar/pull_request/endpoints.py
server/polar/pull_request/schemas.py
server/polar/pull_request/service.py
server/polar/receivers/pledges.py
server/polar/repository/schemas.py

Hello, @birkjernstrom I will start here with a little pull request just refactoring some functions at the level of the code and best practices also while reading the codebase.
One of the best things I notice is the code naming of functions and variables easy and have a flow to follow up 😍

♻️ Refactor code & use some Py3.11 recommendations

---

clients/apps/web/src/components/Banner/Banner.tsx
clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Finance/List.tsx

Finance dark mode fixes

---

clients/apps/web/src/components/Dashboard/IssueList.tsx
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Dashboard/OrganizationDashboard.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddDependency.tsx
clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/apps/web/src/components/Pledge/PledgeByLink.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/status.tsx
clients/apps/web/src/stories/OnboardingAddDependency.stories.tsx

clients/dashboard: dependencies empty state

---

clients/apps/web/src/components/Dashboard/OrganizationDashboard.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddBadge.tsx
clients/apps/web/src/stories/OnboardingAddBadge.stories.tsx
clients/packages/polarkit/src/components/ui/PrimaryButton.tsx

Is show on the default dashboard page if no issues shown have the polar badge

clients/dashboard: onboarding push to add badge

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx

clients/promotion: select badge theme for external embeds

---

clients/apps/web/src/components/Layout/TopbarLayout.tsx
clients/apps/web/src/components/Organization/Footer.tsx
clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
clients/apps/web/src/components/Organization/RepositoryPublicPage.tsx
clients/apps/web/src/components/Pledge/HowItWorks.tsx
clients/apps/web/src/components/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Pledge/index.tsx
clients/apps/web/src/components/Shared/Topbar.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/index.tsx
clients/apps/web/src/stories/PledgePage.stories.tsx
clients/apps/web/src/stories/Topbar.stories.tsx
clients/apps/web/src/stories/testdata.ts

Pending some copy changes, leaving them to you @birkjernstrom!
Preview: https://www.chromatic.com/component?appId=646dd122a99fb9a2fe564ec3&csfId=pages-pledge--default&buildNumber=353&k=64a3dc3ed1832dada684805e-390-interactive-true&h=40&b=-7

clients/pledge: redesign pledge page

---

clients/packages/polarkit/src/api/client/services/InternalService.ts
clients/packages/polarkit/src/api/client/services/OrganizationsService.ts
clients/packages/polarkit/src/api/client/services/PublicService.ts
server/polar/organization/endpoints.py

Public Organization list/search/lookup APIs

---

clients/apps/web/src/components/Dashboard/RepoSelection.tsx
clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/hooks/org.ts
clients/apps/web/src/pages/dashboard/index.tsx
clients/apps/web/src/pages/settings/[organization]/index.tsx
clients/packages/polarkit/src/hooks/queries/index.ts
clients/packages/polarkit/src/store/userContext.ts

client: use new repository and organization APIs

---

clients/apps/web/src/components/Dashboard/RepoSelection.tsx
clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/hooks/org.ts
clients/apps/web/src/pages/dashboard/index.tsx
clients/apps/web/src/pages/settings/[organization]/index.tsx
clients/packages/polarkit/src/hooks/queries/index.ts
clients/packages/polarkit/src/store/userContext.ts

Reverts polarsource/polar#841
This causes some infinite useEffect loops in production. Reverting until I've figured out why. :-)

Revert "client: use new repository and organization APIs"

---

server/polar/issue/endpoints.py

server/badge: Fix #868 by prefixing badge with newlines in comment

---

clients/apps/web/src/components/Backoffice/Badge.tsx

- backoffice/badge: Admin to add/remove Polar label (badge)
- backoffice/badge: setAction with correct types
- backoffice/badge: Set correct action based on type check...
- backoffice/badge: Show success + link to issue

Backoffice: Ability to change action in badge admin

---

clients/apps/chrome-extension/package.json
server/polar/auth/service.py
server/polar/extension/endpoints.py
server/polar/kit/jwt.py

- extension: Fix manifest build issue
- extension: Handle JWT signature error
- extension: Posthog event for GitHub issues load

Posthog: Chrome Extension on GitHub Issue load

---

server/polar/issue/service.py

server/issues: use pledge_badge_currently_embedded as filter on public pages

---

clients/packages/polarkit/src/api/client/index.ts
clients/packages/polarkit/src/api/client/models/CurrencyAmount.ts
clients/packages/polarkit/src/api/client/models/Issue.ts
clients/packages/polarkit/src/api/client/models/Pledge.ts
clients/packages/polarkit/src/api/client/services/PledgesService.ts
server/polar/issue/schemas.py
server/polar/pledge/endpoints.py
server/polar/pledge/schemas.py
server/polar/visibility.py

Public API: get pledge

---

clients/packages/polarkit/src/api/client/index.ts
clients/packages/polarkit/src/api/client/models/ListResource_Pledge_.ts
clients/packages/polarkit/src/api/client/services/PledgesService.ts
server/polar/pledge/endpoints.py
server/polar/pledge/service.py
server/tests/pledge/test_endpoints.py

Public API: search pledges

---

clients/apps/web/src/components/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/stories/BadgePromotionModal.stories.tsx
clients/apps/web/src/stories/FinancePage.stories.tsx
clients/apps/web/src/stories/IssueCard.stories.tsx
clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/apps/web/src/stories/OpenGraphImage.stories.tsx
clients/apps/web/src/stories/OrganizationPublicPage.stories.tsx
clients/apps/web/src/stories/PledgePage.stories.tsx
clients/apps/web/src/stories/RepositoryPublicPage.stories.tsx
clients/apps/web/src/stories/testdata.ts
clients/packages/polarkit/src/api/client/index.ts
clients/packages/polarkit/src/api/client/models/Funding.ts
clients/packages/polarkit/src/api/client/models/Issue.ts
clients/packages/polarkit/src/api/client/models/PledgeResources.ts
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
server/polar/issue/schemas.py
server/polar/models/issue.py
server/polar/pledge/endpoints.py
server/polar/pledge/schemas.py
server/tests/issue/test_endpoints.py

Pledge Page: Funding Goals

---

clients/apps/web/package.json
clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge-injected.svg/route.tsx
clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx
clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Settings/FakePullRequest.tsx
clients/apps/web/src/stories/PledgeBadge.stories.tsx
clients/apps/web/src/stories/PledgeBadgeSVG.stories.tsx
clients/packages/polarkit/jest.config.js
clients/packages/polarkit/package.json
clients/packages/polarkit/src/api/client/models/GithubBadgeRead.ts
clients/packages/polarkit/src/components/badge/Badge.tsx
clients/packages/polarkit/src/money/index.ts
clients/packages/polarkit/src/money/money.test.ts
clients/pnpm-lock.yaml
server/polar/integrations/github/endpoints.py
server/polar/integrations/github/schemas.py

Badges: Funding Goal

---

clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddDependency.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/pages/[organization]/[repo]/issues/[number]/index.tsx
clients/apps/web/src/stories/BadgePromotionModal.stories.tsx
clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/apps/web/src/stories/testdata.ts
clients/packages/polarkit/src/api/client/models/Issue.ts
clients/packages/polarkit/src/api/client/models/IssueDashboardRead.ts
clients/packages/polarkit/src/api/client/models/IssueResources.ts
clients/packages/polarkit/src/api/client/services/IssuesService.ts
clients/packages/polarkit/src/components/badge/Badge.tsx
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
clients/packages/polarkit/src/hooks/queries/issue.ts
server/polar/dashboard/endpoints.py
server/polar/dashboard/schemas.py
server/polar/funding/schemas.py
server/polar/integrations/github/endpoints.py
server/polar/integrations/github/schemas.py
server/polar/issue/endpoints.py
server/polar/issue/schemas.py

Dashboard: set funding goal per issue

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddDependency.tsx
clients/apps/web/src/stories/BadgePromotionModal.stories.tsx
clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/packages/polarkit/src/api/client/models/IssueDashboardRead.ts
server/polar/dashboard/schemas.py

- server/dashboard: add pledge_badge_currently_embedded to issues
- clients/dashboard: handle BadgePromotionModal for issues that have badge without label

handle BadgePromotionModal for issues that have badge without label

---

clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddBadge.tsx
clients/apps/web/src/components/UI/CopyToClipboardInput.tsx

https://github.com/polarsource/polar/assets/281715/439c778b-3ef8-4648-8111-81fcb28098dc

Show badge issue by default

---

clients/packages/polarkit/src/api/client/index.ts
clients/packages/polarkit/src/api/client/models/Pledge.ts
clients/packages/polarkit/src/api/client/models/Pledger.ts
server/polar/pledge/schemas.py

Part of the work in #947 and #895.

server/pledge: add pledger to pledge objects in the public API

---

server/README.md

Update server readme with instructions on setting up a personal GitHub app.

Update server readme

---

clients/apps/web/src/components/Shared/ProfileSelection.tsx

clients/navigation: installation funding upsell

---

clients/apps/web/src/components/Dashboard/OrganizationIssues.tsx
clients/apps/web/src/components/Dashboard/filters.ts
clients/apps/web/src/components/Dashboard/index.tsx
clients/apps/web/src/pages/feed.tsx
clients/apps/web/src/pages/maintainer/[organization]/issues/index.tsx

Removes code to handle dependencies views for organizations.

clients/issues: refactor maintainer issues view to be less general

---

server/polar/integrations/github/service/issue.py

Fixes https://polar-sh.sentry.io/issues/4331993417/events/6a347f8567524fefb1c0c3cce4ef2117/?project=4505046565519360

server/issue: skip sync of moved issues

---

server/polar/integrations/github/service/organization.py

Also fixed #958 while I was working in the same function.

server/dependencies: handle 401

---

clients/apps/web/src/components/Dashboard/IssueList.tsx

modified: IssueList.tsx 
changes: 
Line 300
`className="m-0 w-48 border-0 bg-transparent bg-right p-0 text-sm font-medium ring-0 focus:border-0 focus:ring-0 dark:bg-gray-900 dark:text-gray-300"
`
[screen capture](https://i.imgur.com/u5BvBqq.png)

Issue #952: Sort low contrast in dark mode | Fixed ✅

---

.github/workflows/chromatic.yaml
.github/workflows/release_chrome_extension.yaml
.github/workflows/test_client.yaml

ci: use cached node js versions

---

server/polar/integrations/github/service/reference.py

The OpenAPI spec for this endpoint is not good at all. Adding a catch all event type to gracefully handle 'invalid' events.

server/references: add a catch all event type

---

clients/apps/web/src/components/Shared/ProfileSelection.tsx

clients/ProfileSelection: add indicator next to current user or org

---

server/polar/integrations/github/client.py
server/polar/integrations/github/service/issue.py
server/polar/issue/endpoints.py
server/polar/issue/schemas.py
server/polar/issue/service.py
server/polar/models/issue.py
server/polar/types.py
server/tests/integrations/github/tasks/test_webhook.py
server/tests/issue/test_service.py

server/issues: search issues by github milestone

---

server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/organization.py
server/polar/integrations/github/service/pull_request.py
server/polar/integrations/github/service/user.py
server/polar/integrations/github/tasks/utils.py
server/polar/integrations/stripe/endpoints.py
server/polar/issue/schemas.py
server/polar/issue/service.py
server/polar/kit/db/models/mixins/active_record.py
server/polar/kit/services.py
server/polar/models/issue.py
server/polar/models/organization.py
server/polar/models/pull_request.py
server/polar/models/repository.py
server/polar/models/user.py
server/polar/models/user_organization_settings.py
server/polar/organization/service.py
server/polar/pull_request/schemas.py
server/polar/pull_request/service.py
server/scripts/github.py

* Fewer layers of magic
* Better types

server/db: cleanup upserts

---

clients/apps/web/src/app/(backer)/for-you/page.tsx
clients/packages/polarkit/src/api/client/services/IssuesService.ts
clients/packages/polarkit/src/hooks/queries/issue.ts
server/polar/integrations/github/service/dependency.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/organization.py
server/polar/integrations/github/service/paginated.py
server/polar/integrations/github/service/pull_request.py
server/polar/integrations/github/service/repository.py
server/polar/integrations/github/tasks/repo.py
server/polar/issue/endpoints.py
server/tests/integrations/github/service/test_issue.py

Very much a work in progress, this page is not linked anywhere. :-)
Updates #1048

Add experimental /for-you page (recommendations)

---

server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/paginated.py

Fixes #1059 
- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)
<a href="https://polar.sh/polarsource/polar/issues/1061">
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1061/pledge.svg?darkmode=1">
</picture>
</a>

server/issues: additional checks to prevent PR to be saved as an issue

---

server/polar/account/endpoints.py
server/polar/account/service.py
server/polar/app.py
server/polar/auth/dependencies.py
server/polar/exception_handlers.py
server/polar/exceptions.py
server/polar/integrations/open_collective/service.py
server/polar/issue/endpoints.py
server/polar/organization/service.py
server/polar/pledge/endpoints.py

Following what we discussed in #849.
- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)
<a href="https://polar.sh/polarsource/polar/issues/1057">
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1057/pledge.svg?darkmode=1">
</picture>
</a>

Base exception and generic exception handler

---

clients/apps/web/src/app/backoffice/layout.tsx
clients/apps/web/src/app/maintainer/[organization]/initialize/layout.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Layout/TopbarLayout.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Shared/Topbar.tsx
clients/apps/web/src/components/Shared/TopbarRight.tsx

clients/topbar: propagate useOrgFromURL correctly from each layout

---

server/scripts/github.py

Adding a script to crawl and help cleanup PRs accidentally saved as issues

server/scripts: add delete_invalid_issues

---

server/polar/integrations/github/service/issue.py
server/polar/integrations/github/tasks/issue.py
server/polar/worker.py

Reduce load on workers

---

server/polar/integrations/github/tasks/issue.py

server/worker: job deduplication and defering

---

server/polar/integrations/github/service/issue.py
server/polar/issue/endpoints.py

* Speed up improvement by enabling concurrent crawling
* Shuffling recommendations by repository

Recommendations speed up and shuffling

---

clients/apps/web/src/app/(backer)/feed/page.tsx
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Feed/Recommended.tsx
clients/packages/polarkit/src/components/ui/atoms/ShadowBoxOnLg.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts
clients/packages/polarkit/src/github/index.ts

clients/feed: redesign and launch recommendations

---

clients/apps/web/src/app/(backer)/error.tsx
clients/apps/web/src/app/error.tsx
clients/apps/web/src/app/global-error.tsx

Slightly related to #1066 and #1074

clients: add global and backer routes error handling

---

clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/page.tsx
clients/apps/web/src/app/(pledge)/not-found.tsx
clients/apps/web/src/app/(public)/[organization]/[repo]/page.tsx
clients/apps/web/src/app/(public)/[organization]/page.tsx
clients/apps/web/src/app/(public)/not-found.tsx
clients/apps/web/src/app/not-found.tsx

clients: add custom not-found handler

---

clients/apps/web/src/app/(backer)/feed/page.tsx

clients/feed: add active/closed tabs for funded issues

---

clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/page.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/packages/polarkit/src/api/index.ts
clients/packages/polarkit/src/components/ui/molecules/Banner.tsx
server/polar/exceptions.py
server/polar/issue/endpoints.py

Add private notice on private issue pages

---

clients/apps/web/src/app/(backer)/feed/page.tsx

Reverts polarsource/polar#1097

Revert "clients/feed: add active/closed tabs for funded issues"

---

server/polar/integrations/github/service/issue.py

server/issues: skip recommendations cache if none found

---

clients/apps/web/src/app/(backer)/settings/page.tsx
clients/apps/web/src/components/Dashboard/BackerNavigation.tsx
clients/apps/web/src/components/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Pledge/payment.ts
clients/apps/web/src/components/Settings/PaymentMethodSettings.tsx
clients/packages/polarkit/src/api/client/services/PaymentMethodsService.ts
clients/packages/polarkit/src/hooks/queries/pledges.ts
server/polar/integrations/stripe/service.py
server/polar/payment_method/endpoints.py

Payment Method Settings

---

clients/apps/web/src/components/Dashboard/BackerConnectUpsell.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx

clients: updated backer navigation

---

clients/apps/web/src/components/Auth/MaintainerSignup.tsx

clients/signup: add legal disclaimer to maintainer signup

---

server/polar/integrations/github/service/issue.py

Fixes #1178 
Kind of related to #1170

server/issues: only call hooks if autocommit is on

---

clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Finance/ListPledges.tsx
clients/apps/web/src/components/Finance/ListRewards.tsx
clients/apps/web/src/stories/FinancePledgeList.stories.tsx
clients/apps/web/src/stories/FinanceRewardsList.stories.tsx

clients/finance: show invoice status

---

clients/apps/web/src/app/(backer)/feed/page.tsx

clients/web: fix #1160 a single 0 is printed on /feed

---

clients/apps/web/package.json
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/ui/tabs.tsx
clients/pnpm-lock.yaml

The tab selector is hidden by default, and can be enabled with a feature flag.

Pledge: Pay on Completion

---

clients/apps/web/src/components/Finance/Split.tsx

clients/finance: tweak split rewards darkmode

---

clients/apps/web/src/components/Pledge/Contribute.stories.tsx
clients/apps/web/src/components/Pledge/Contribute.tsx
clients/apps/web/src/components/Pledge/FundOnCompletion.tsx
clients/apps/web/src/components/Pledge/PaymentForm.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Pledge/Subtotal.tsx

clients/pledge: add contribute tab

---

clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge-injected.svg/route.tsx
clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx
clients/apps/web/src/stories/PledgeBadge.stories.tsx
clients/packages/polarkit/src/components/badge/Badge.tsx

clients/badge: show upfront rewards split

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/packages/polarkit/src/api/client/services/IssuesService.ts
clients/packages/polarkit/src/hooks/queries/issue.ts
server/polar/issue/endpoints.py

- server/issue: change internal APIs to follow the new API guidelines
- clients/issue: tweak to use new easier APIs

server/issues: prettier internal APIs

---

clients/apps/web/src/components/Backoffice/RewardsPending.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Pledge/FundOnCompletion.tsx
clients/packages/polarkit/src/components/ui/atoms/MoneyInput.tsx
clients/packages/polarkit/src/components/ui/molecules/Banner.tsx
server/polar/pledge/schemas.py

Seed rewards

---

server/polar/integrations/github/service/issue.py
server/polar/issue/endpoints.py
server/polar/postgres.py

server/issue: create new session for each coroutine

---

server/polar/integrations/github/service/issue.py
server/polar/issue/endpoints.py
server/polar/postgres.py

Reverts polarsource/polar#1239

Revert "server/issue: create new session for each coroutine"

---

server/poetry.lock
server/polar/integrations/github/service/reference.py
server/polar/integrations/github/tasks/webhook.py
server/polar/issue/schemas.py
server/pyproject.toml

server/organization: temp fix for #1241 by using a patched version of githubkit

---

README.md
clients/apps/chrome-extension/src/manifest.template.json
clients/apps/web/src/app/(installation)/github/installation/page.tsx
clients/apps/web/src/components/Auth/MaintainerSignup.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Finance/Split.tsx
clients/apps/web/src/components/Onboarding/FundAGithubIssue.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddDependency.tsx
clients/apps/web/src/components/Onboarding/OnboardingInstallChromeExtension.tsx
clients/apps/web/src/components/Pledge/PledgeByLink.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/components/Shared/TopbarRight.tsx
docs/mkdocs.yml
server/polar/issue/schemas.py

fix: ensure GitHub capitalization is correct across the wording

---

clients/packages/polarkit/src/github/index.test.ts
clients/packages/polarkit/src/github/index.ts

clients/kit: allow URL fragment when parsing GitHub issue URL

---

clients/packages/polarkit/src/components/Issue/IssuePledge.tsx

clients/issues: show amounts per pledge type

---

clients/packages/polarkit/src/components/Issue/IssuePledge.tsx

clients/issue: redesign mark as completed button

---

clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx

This API does not have this information anymore, see rewards page instead

clients/dashboard: remove payout status

---

server/polar/notifications/notification.py
server/polar/pledge/service.py
server/tests/notifications/test_email.py
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_no_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_with_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification.html
server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification_with_account.html
server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification.html
server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification_with_account.html
server/tests/notifications/testdata/test_PledgerPledgePendingNotification_pay_on_completion.html
server/tests/notifications/testdata/test_RewardPaidNotification.html

Add more content and descriptions to the emails, and support pay-on-completion alerts to backers
Fixes #1264

server/notifications: update email notifications

---

clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/packages/polarkit/src/components/Issue/Reference.tsx

Adds stories for missing cases
Fixes #1274

clients/issues: fix icon for external PR references

---

clients/apps/web/src/components/Toast/Toaster.tsx

Solves #838 
modified: src\components\Toast\Toaster.tsx
change:
line 21
`
<div className="grid gap-1 dark:bg-gray-900 dark:text-gray-300"
`

Toast low contrast in dark mode #838

---

clients/packages/polarkit/src/components/Issue/IssuePledge.tsx
clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx

Bringing the implementation:
one step closer to the design:
(before):
Also fixes #1309

clients/issues: redesign issue card as shown on /feed

---

clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/(create)/page.tsx
clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx
clients/packages/polarkit/src/api/client/models/SummaryPledge.ts
server/polar/dashboard/endpoints.py
server/polar/models/pledge.py
server/polar/pledge/endpoints.py
server/polar/pledge/schemas.py
server/polar/pledge/service.py
server/tests/dashboard/test_endpoints.py
server/tests/issue/test_service.py

Add PledgeSummary to the dashboard API.

Dashboard API pledge summaries

---

server/polar/reward/service.py

server/rewards: add missing commit when connecting rewards

---

clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Finance/ListPledges.tsx
clients/apps/web/src/components/Finance/ListRewards.tsx
clients/apps/web/src/stories/FinanceRewardsList.stories.tsx

Also some tweaks to show pledger on the rewards tab

clients/rewards: remove est. payout date

---

clients/apps/web/src/app/(backer)/feed/page.tsx

clients/feed: banner to notify about pending rewards

---

clients/apps/web/src/app/(public)/[organization]/[repo]/page.tsx
clients/apps/web/src/app/(public)/[organization]/page.tsx
clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
clients/apps/web/src/components/Organization/RepositoryPublicPage.tsx
clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/apps/web/src/stories/OrganizationPublicPage.stories.tsx
clients/apps/web/src/stories/RepositoryPublicPage.stories.tsx
clients/packages/polarkit/src/api/client/services/FundingService.ts
clients/packages/polarkit/src/components/Issue/IssueFundingDetails.stories.tsx
clients/packages/polarkit/src/components/Issue/IssueFundingDetails.tsx
clients/packages/polarkit/src/components/Issue/PledgeSummaryPill.stories.tsx
clients/packages/polarkit/src/components/Issue/PledgeSummaryPill.tsx
clients/packages/polarkit/src/components/Issue/PublicRewardPill.tsx
clients/packages/polarkit/src/components/Issue/index.ts
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
clients/packages/polarkit/src/components/pledge/Pledgers.tsx
clients/packages/polarkit/testdata.ts
server/polar/funding/endpoints.py
server/polar/funding/service.py

Update public maintainer's page

---

clients/apps/web/src/components/Finance/Split.stories.tsx
clients/apps/web/src/components/Finance/Split.tsx
clients/apps/web/src/components/Finance/SplitNotify.stories.tsx
clients/apps/web/src/components/Finance/SplitNotify.tsx
clients/apps/web/src/components/Finance/SplitRewardModal.tsx
clients/apps/web/src/utils/github.ts
clients/packages/polarkit/package.json
clients/packages/polarkit/src/components/ui/textarea.tsx

https://github.com/polarsource/polar/assets/47952/8c6feb2d-f117-4bf2-8979-35aa64abec13

clients/rewards: message to contributors after allocated split

---

clients/apps/web/src/components/Shared/ProfileSelection.tsx

Implemented new profile picker design: #1327.

Profile Picker: Reorder items and adjust margins

---

clients/apps/web/src/components/Shared/ProfileSelection.tsx

Adds spacing between profile name and type in Profile picker.

Profile Picker: Add spacing between profile name and type

---

clients/apps/web/src/app/(installation)/github/installation/page.tsx
clients/apps/web/src/components/Auth/MaintainerSignup.tsx
clients/apps/web/src/components/Pledge/FundOnCompletion.tsx
clients/apps/web/src/components/Shared/GithubLoginButton.tsx
clients/packages/polarkit/src/api/client/index.ts
clients/packages/polarkit/src/api/client/models/UserSignupType.ts
clients/packages/polarkit/src/api/client/services/IntegrationsService.ts
server/polar/config.py
server/polar/enums.py
server/polar/integrations/github/endpoints.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/repository.py
server/polar/integrations/github/service/user.py
server/polar/integrations/loops/client.py
server/polar/integrations/loops/service.py
server/polar/organization/service.py
server/polar/pledge/endpoints.py
server/polar/pledge/payment_intent_service.py
server/polar/pledge/service.py
server/polar/user/service.py
server/pyproject.toml
server/scripts/loops_migration.py

Loops integration

---

server/polar/auth/dependencies.py

Adds @frankie567 and @emilwidlund to backoffice users

server/backoffice: add frankie567 and emilwidlund to backoffice users

---

clients/apps/web/next.config.js
clients/packages/sdk/openapi/source.json
clients/packages/sdk/openapi/updated.json
docs/docs/api.md
server/polar/app.py
server/polar/auth/dependencies.py

Implements a redirect for `/settings/tokens` to `/settings`.

Add redirect for /settings/tokens to /settings

---

clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/(create)/page.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/apps/web/src/stories/PledgePage.stories.tsx
clients/packages/polarkit/src/api/client/models/PullRequest.ts
clients/packages/polarkit/src/components/Issue/IssueReference.tsx
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
server/polar/pull_request/schemas.py

clients/pledge: show related pull requests

---

clients/apps/web/tailwind.config.js

Adjusts the default shadow to have a smoother falloff

Slight adjustment to the shadow configuration

---

clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx

Adds empty state to issues list for maintainers.

Add empty state to issues list for maintainers

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Notifications/Popover.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Shared/Topbar.tsx

Move notification area from topbar to sidebar in Dashboard layout.

Move notification area from topbar to sidebar in Dashboard layout

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx

Implements upsell callouts in Sidebar for dashboard views. Also adjusts vertical sidebar content margins.

Add upsell areas to sidebars

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx

Adjusts dark mode styles for upsell areas in sidebar.

Adjust dark mode styles for upsell areas

---

clients/apps/web/src/components/Settings/AccessTokensSettings.tsx

Added formatted date & adjusted text sizes in Access Token Section.

Polish to access token section

---

clients/apps/web/src/app/layout.tsx
clients/apps/web/src/components/Dashboard/BackerNavigation.tsx
clients/apps/web/src/components/Dashboard/MaintainerNavigation.tsx
clients/apps/web/src/components/Dashboard/MaintainerRepoSelection.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Notifications/Popover.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/apps/web/src/components/Shared/Topbar.tsx
clients/apps/web/src/components/Shared/TopbarRight.tsx
clients/apps/web/tailwind.config.js

Improves color and shadow contrast for both light & dark mode.

Improve color/shadow contrast

---

server/polar/auth/service.py

This functionality seems to have disappeared in a refactoring. Adding it again with some comments this time :)

server/auth: re-add support for user_id JWT in auth header

---

clients/packages/polarkit/src/components/badge/Badge.tsx

Adjusts dark mode palette on badge.

Adjust dark mode palette on badge

---

clients/packages/polarkit/src/components/pledge/IssueCard.tsx

Fixes issue with issue card progress in dark mode

Fix issue card progress in dark mode

---

clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Finance/Finance.tsx
clients/apps/web/src/components/Onboarding/FundAGithubIssue.tsx
clients/apps/web/src/components/Organization/Header.tsx
clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
clients/apps/web/src/components/Organization/RepositoryPublicPage.tsx
clients/apps/web/src/components/Pledge/FundOnCompletion.tsx
clients/apps/web/src/components/Pledge/HowItWorks.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
clients/packages/polarkit/src/components/ui/atoms/MoneyInput.tsx

General adjustments to margins, colors & typography

General adjustments to margins, colors & typography

---

clients/packages/sdk/README.md
clients/packages/sdk/package.json
clients/packages/sdk/scripts/generate-schema.js
clients/pnpm-lock.yaml

Automatically generate a README for the SDK from Open AI schema.

Generate README for SDK from Openai schema

---

clients/apps/web/src/app/(backer)/feed/page.tsx
clients/apps/web/src/components/Dashboard/IssueList.tsx
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Feed/Recommended.tsx
clients/apps/web/src/stories/IssueListItem.stories.tsx
clients/packages/polarkit/src/components/Issue/IssuePledge.tsx
clients/packages/polarkit/src/components/Issue/IssueReference.tsx
clients/packages/polarkit/src/components/Issue/ListItemDecoration.tsx

A pledge is counted as your own if you have access to admin it from the senders perspective

clients/IssueListItem: show on behalf of org pledges as your own pledges

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx

Adjusts the background color for issue promotion modal in dark mode.

Fix dark mode contrast in modal

---

clients/apps/web/src/components/Pledge/FundOnCompletion.tsx
clients/apps/web/src/components/Pledge/OnBehalfOf.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx

Fixes #1282 
Fixes #1284
* If the user is logged in, and have organisations installed that are not their "own" org: show the "Attribute pledge to" field.
* You can select yourself, or any of the organisations.
* Available for both Fund Today and Pay On Completion.

Checkout: Pledge on behalf of

---

server/polar/auth/dependencies.py
server/polar/auth/service.py

Headers/Cookies are the transports, a header can contain a PAT, but we don't know that yet

server/auth: clarify header vs PAT

---

server/polar/notifications/endpoints.py
server/polar/notifications/schemas.py

Same issue as the bug for references #1451

server/notifications: fix generated types inconsistencies

---

.github/workflows/publish_sdk.yaml
clients/packages/sdk/examples/polar-next-example/src/app/page.tsx

Update Next.js example with outgoing link to issue, etc.

SDK: Update Next.js example

---

clients/apps/web/src/app/(backer)/settings/page.tsx
clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/promote/issues/ClientPage.tsx
clients/apps/web/src/components/Dashboard/BackerNavigation.tsx
clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Dashboard/MaintainerNavigation.tsx
clients/apps/web/src/components/Dropdown/index.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Settings/Badge/Repositories.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/components/Settings/PaymentMethodSettings.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/apps/web/src/components/Shared/TopbarRight.tsx
clients/packages/polarkit/src/components/Issue/IconCounter.tsx
clients/packages/polarkit/src/components/badge/Badge.tsx
clients/packages/polarkit/src/components/ui/atoms/ShadowBox.tsx
clients/packages/polarkit/src/components/ui/atoms/ShadowListGroup.tsx

Implements small tweaks for dark mode

Dark Mode: General polish

---

clients/apps/web/src/app/maintainer/[organization]/finance/layout.tsx
clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/promote/embeds/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/promote/issues/ClientPage.tsx
clients/apps/web/src/components/Dashboard/IssueList.tsx
clients/apps/web/src/components/Dashboard/MaintainerRepoSelection.tsx
clients/apps/web/src/components/Dropdown/index.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Organization/Navigation.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx

Implements a contextual slot in topbar that pages can use.

Implement topbar contextual slot

---

server/polar/dashboard/endpoints.py
server/polar/dashboard/schemas.py
server/tests/dashboard/test_endpoints.py

server/dashboard: remove JSON:API relations and includes

---

clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Shared/Topbar.tsx
clients/packages/polarkit/src/components/ui/atoms/MoneyInput.tsx

This PR adds and removes `z-index` for various nodes to exclude displaying of webpage elements over Notifications.
Fixes #1313

clients/web: Fix `z-index`es for Notifications (#1313)

---

clients/apps/web/src/stories/IssueCard.stories.tsx
clients/packages/polarkit/src/components/pledge/IssueCard.tsx
clients/packages/polarkit/testdata.ts

Pledge page issue tweaks

---

clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Feed/Recommended.tsx
clients/apps/web/src/components/Onboarding/FundAGithubIssue.tsx
clients/apps/web/src/components/Onboarding/OnboardingAddBadge.tsx
clients/packages/polarkit/src/components/Issue/IssueSummary.tsx
clients/packages/polarkit/src/components/ui/molecules/Banner.tsx

Add filtering context to issues list for maintainers

Polish issues list for maintainers

---

clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx

Use plain layout for maintainer issues list

Use plain layout for maintainer issues list

---

server/polar/notifications/notification.py
server/polar/receivers/pledges.py
server/tests/notifications/test_pledge_notifications.py
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_pay_on_completion.html

server/notifications: include pledge type and pledger name in emails

---

clients/apps/web/src/app/(installation)/github/installation/page.tsx
clients/packages/polarkit/src/hooks/queries/index.ts
clients/packages/polarkit/testdata.ts
clients/packages/sdk/src/client/apis/BackofficeApi.ts
clients/packages/sdk/src/client/apis/IntegrationsApi.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/backoffice/endpoints.py
server/polar/integrations/github/endpoints.py
server/polar/models/organization.py
server/polar/models/repository.py
server/polar/organization/endpoints.py
server/polar/organization/service.py

Remove deprecated types, remove the cyclic dependency between org and repo models. :)

Cleanup organization models and schemas

---

clients/apps/web/src/components/Dashboard/BackerNavigation.tsx
clients/apps/web/src/components/Dashboard/MaintainerNavigation.tsx
clients/apps/web/src/components/Dashboard/MetaNavigation.tsx
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx

Adds Github & Discord links in nav.

Add external nav with outgoing links

---

clients/apps/web/src/components/Dashboard/navigation.tsx

Adjusts the icon size for "Public site" entry in nav.

Fix icon size for public site nav link

---

clients/apps/web/src/app/team/[organization]/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/page.tsx
clients/apps/web/src/app/team/layout.tsx
clients/apps/web/src/components/Dashboard/MaintainerNavigation.tsx
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/packages/polarkit/package.json
clients/packages/polarkit/src/components/ui/atoms/Avatar.tsx
clients/packages/polarkit/src/components/ui/atoms/Pill.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts
clients/packages/polarkit/src/components/ui/table.tsx
clients/packages/polarkit/src/hooks/queries/org.ts

clients/team: add team members page

---

clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/funding/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/funding/page.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/packages/polarkit/src/components/Issue/IssuePledge.tsx
clients/packages/polarkit/src/hooks/queries/pledges.ts
clients/packages/sdk/src/client/apis/PledgesApi.ts
server/polar/pledge/endpoints.py
server/polar/pledge/service.py

Team: pledges list view

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx

Show "Connect Repositories" upsell and Add Organization link in profile picker.

Make sure to show connect repositories and Add Organization

---

clients/apps/web/src/app/(installation)/github/installation/page.tsx
clients/apps/web/src/components/Dashboard/LoadingScreen.tsx
clients/apps/web/src/components/Settings/Badge/Repository.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/packages/polarkit/src/components/ui/atoms/FormattedDateTime.tsx

clients/installation: fix error flashing and other React errors

---

server/polar/account/service.py

server/account: fix exists check for user-connected accounts

---

clients/apps/web/package.json
clients/apps/web/src/app/(public)/[organization]/page.tsx
clients/apps/web/src/app/(public)/subscribe/success/page.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/[tier]/page.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/new/page.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/page.tsx
clients/apps/web/src/utils/api.ts
clients/pnpm-lock.yaml

Next.js had a weird error when using their `cookies` function, resulting in crash on Vercel (ref: https://github.com/vercel/next.js/issues/56919)
Upgrade Next.js to 13.5.6 which fixes the issue.

Fix error when using `cookies` function

---

clients/apps/web/src/components/Subscriptions/PublicSubscriptionUpsell.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionGroupIcon.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx
clients/apps/web/src/components/Subscriptions/utils.ts

- Card aesthetics (tweaked colors, borders, etc)
- Add truncation to card title

Polish Subscription UI

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/apps/web/src/components/Shared/Topbar.tsx

Adjusts the background color for dark mode for better readability.

Dark-mode contrast improvements

---

clients/apps/web/src/components/Subscriptions/SubscriptionTierForm.tsx
clients/apps/web/src/styles/globals.scss

Configures shadcn css variables to match Polar

Configure shadcn css variables to match Polar

---

clients/apps/web/src/app/(public)/subscribe/success/page.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionSuccess.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCelebration.tsx
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/subscription/endpoints.py
server/polar/subscription/schemas.py
server/polar/subscription/service/subscription_tier.py
server/tests/subscription/test_endpoints.py

Subscription success page

---

server/polar/integrations/github/endpoints.py

server/auth: fix GitHub callback when user is logged in but doesn't have ID in the state data

---

clients/apps/web/src/components/Pledge/PledgeForm.tsx

Update checkout amount appropriately

---

clients/apps/web/src/app/maintainer/[organization]/finance/layout.tsx
clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/layout.tsx
clients/apps/web/src/app/maintainer/[organization]/promote/embeds/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/promote/issues/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/page.tsx
clients/apps/web/src/app/team/[organization]/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/funding/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/members/ClientPage.tsx
clients/apps/web/src/app/team/[organization]/settings/ClientPage.tsx
clients/apps/web/src/app/team/[team]/ClientPage.tsx
clients/apps/web/src/app/team/[team]/funding/ClientPage.tsx
clients/apps/web/src/app/team/[team]/funding/page.tsx
clients/apps/web/src/app/team/[team]/members/ClientPage.tsx
clients/apps/web/src/app/team/[team]/members/page.tsx
clients/apps/web/src/app/team/[team]/page.tsx
clients/apps/web/src/app/team/[team]/settings/ClientPage.tsx
clients/apps/web/src/app/team/[team]/settings/page.tsx
clients/apps/web/src/app/team/layout.tsx
clients/apps/web/src/components/Dashboard/TeamsNavigation.tsx
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/MaintainerLayout.stories.tsx
clients/apps/web/src/components/Layout/MaintainerLayout.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCreatePage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
clients/apps/web/src/components/Subscriptions/TiersPage.tsx
clients/apps/web/src/hooks/org.ts
server/polar/integrations/stripe/service.py

Enabled by a feature flag, hidden by deafult.

clients/teams: add teams to the sidebar

---

clients/apps/web/src/components/Dashboard/BadgeMessageForm.tsx
clients/apps/web/src/components/Dashboard/IssueListItem.tsx
clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Dashboard/UpfrontRewards.tsx
clients/apps/web/src/components/Finance/SplitNotify.tsx
clients/apps/web/src/components/Settings/Badge/index.tsx
clients/apps/web/src/components/Subscriptions/PublicSubscriptionUpsell.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionGroupPublic.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierForm.tsx
clients/packages/polarkit/src/components/ui/atoms/TextArea.stories.tsx
clients/packages/polarkit/src/components/ui/atoms/TextArea.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts

Adds TextArea component with stories.

clients/shadcn: Add textarea component

---

clients/apps/web/src/app/team/[team]/settings/ClientPage.tsx
clients/packages/polarkit/src/hooks/queries/org.ts
clients/packages/polarkit/src/hooks/queries/retry.ts
clients/packages/sdk/src/client/apis/OrganizationsApi.ts
clients/packages/sdk/src/client/models/index.ts

Fixes #1557 
Current amount of credits is shown to Admins, regular members will not see anything.

clients/team: show current credit amount

---

server/polar/integrations/stripe/service.py
server/polar/pledge/service.py
server/tests/pledge/test_service.py

server/pledge: support sending invoices to organizations

---

server/polar/organization/endpoints.py
server/polar/organization/schemas.py
server/tests/organization/test_endpoints.py

server/organization: add billing email to API

---

clients/apps/web/src/components/Pledge/OnBehalfOf.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierForm.tsx
clients/packages/polarkit/src/components/ui/atoms/Select.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts

Adds a proxied version of Select component with all its underlying primitives.

clients/select: Add proxied version of Select component

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Modal/index.tsx
clients/apps/web/src/components/Pledge/PledgeForm.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/styles/globals.scss
clients/packages/eslint-config-custom/index.js
clients/packages/polarkit/src/components/ui/atoms/Tabs.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts

- Implements proxied Tab components based on Shadcn. 
- Applied it to promotion modals & pledge form.
- Added import rule to prohibit imports from shadcn-directory

clients/tabs: Implement proxied Shadcn tab components

---

clients/apps/web/src/app/team/[team]/settings/ClientPage.tsx
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
clients/packages/sdk/src/client/models/index.ts

Updates #1287 
Merge after #1586

clients/team: spending limits form

---

clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/packages/eslint-config-custom/index.js
clients/packages/polarkit/src/components/ui/atoms/Input.tsx
clients/packages/polarkit/src/components/ui/atoms/Tabs.stories.tsx
clients/packages/polarkit/src/components/ui/atoms/Tabs.tsx

- Add Tab stories
- Set fallback color for inputs
- Use Tabs in DashboardTopbar

Shadcn component improvements

---

clients/apps/web/src/app/team/[team]/settings/ClientPage.tsx
server/polar/organization/service.py
server/polar/pledge/service.py
server/tests/pledge/test_endpoints.py
server/tests/pledge/test_service.py

Spending limits

---

clients/apps/web/src/components/Notifications/Popover.tsx
clients/apps/web/src/stories/Notification.stories.tsx
clients/packages/sdk/src/client/models/index.ts
server/polar/notifications/endpoints.py
server/polar/notifications/notification.py
server/polar/notifications/schemas.py
server/polar/notifications/service.py
server/polar/pledge/service.py
server/tests/notifications/test_email.py
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_pay_on_completion.html
server/tests/notifications/testdata/test_TeamAdminMemberPledgedNotification.html

server/notifications: add notification to team admin on pledge

---

clients/apps/web/src/components/Pledge/CircledNumber.tsx
clients/apps/web/src/components/Pledge/Pledge.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutContribute.stories.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutContribute.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFund.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFundOnCompletion.stories.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFundOnCompletion.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFundToday.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutPanel.tsx
clients/apps/web/src/components/Pledge/payment.ts

Split components into separate files, and renamed them to a consistent pattern. No other changes.

clients/checkout: split and refactor components

---

clients/apps/web/src/components/Pledge/PledgeCheckoutFund.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFundByTeam.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutFundToday.tsx
clients/apps/web/src/components/Pledge/TeamSelect.tsx

A work in progress, before merging I'll wrap the tab in the tab selector behind a feature flag :)
Updates #1287

clients/checkout: add fund by team option

---

server/polar/pledge/endpoints.py
server/polar/pledge/schemas.py
server/tests/pledge/test_endpoints.py

clients/pledges: API to get users current spending

---

clients/apps/web/src/components/Pledge/PledgeCheckoutFundByTeam.tsx
clients/packages/polarkit/src/api/errors.ts
clients/packages/polarkit/src/hooks/queries/pledges.ts
clients/packages/sdk/src/client/apis/PledgesApi.ts
clients/packages/sdk/src/client/models/index.ts

clients/pledge: show spending and propagate errors

---

clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/[tier]/page.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/new/page.tsx
clients/apps/web/src/app/maintainer/[organization]/subscriptions/tiers/page.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierBenefitsForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCreatePage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
clients/apps/web/src/components/Subscriptions/TiersPage.tsx
clients/packages/polarkit/src/hooks/queries/index.ts
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

Implements subscription hooks for use on dashboard pages.

Implement Subscription hooks

---

clients/apps/web/src/components/Subscriptions/SubscriptionTierBenefitsForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCreatePage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

Adjusts cache invalidation logic for Subscription hooks

Subscriptions: Adjust cache invalidation logic

---

clients/apps/web/src/components/Dashboard/IssuePromotionModal.tsx
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Subscriptions/utils.tsx
clients/packages/polarkit/src/components/ui/atoms/Button.tsx
clients/packages/polarkit/src/components/ui/atoms/Input.tsx

Polished icons & buttons across the web app.

Design polish

---

clients/apps/web/src/app/maintainer/[organization]/subscriptions/page.tsx
clients/apps/web/src/components/Subscriptions/OverviewPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionSuccess.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionsChart.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionsMetric.tsx
clients/packages/polarkit/src/components/ui/atoms/Card.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts
clients/packages/polarkit/src/components/ui/card.tsx

Subscriptions UI Overview polish
- Removed stroke ticks
- Adjusted font color for ticks
- New Card component
- Adjusted grid margins
- Adjusted graph curve function for smoother line interpolation

Subscriptions UI Overview polish

---

clients/apps/web/src/components/Subscriptions/SubscriptionsMetric.tsx
clients/packages/polarkit/src/components/ui/atoms/Card.tsx

- Adjust card background in dark mode 
- Add blue color to icons in card

Subscriptions UI Polish

---

server/polar/issue/service.py
server/polar/pledge/payment_intent_service.py
server/polar/pledge/service.py
server/tests/pledge/test_service.py

server/pledge: support pledges to closed issues

---

clients/apps/web/src/components/Pledge/PaymentForm.tsx

clients/pledge: spin spinner until redirected

---

clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
clients/apps/web/src/components/Organization/RepositoryPublicPage.tsx
clients/apps/web/src/components/Organization/index.ts

clients/external: make github-sourced links external

---

server/polar/kit/db/models/mixins/active_record.py
server/polar/notifications/service.py
server/polar/notifications/tasks/email.py
server/polar/pledge/service.py
server/polar/subscription/schemas.py
server/scripts/dev_github.py
server/tests/integrations/github/tasks/test_integration.py
server/tests/kit/db/models/mixins/test_active_record.py
server/tests/models/test_pledge.py
server/tests/subscription/service/test_subscription_tier.py

Prefer services over the mixing :)

server/db: remove find and find_by from ActiveRecordMixin

---

clients/apps/web/src/components/Shared/ConfirmModal.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierBenefitsForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierForm.tsx
clients/apps/web/src/styles/globals.scss
clients/packages/polarkit/src/hooks/queries/subscriptions.ts
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
clients/packages/sdk/src/client/models/index.ts

Adds benefit deletion capabiltities. Also adds a `<ConfirmModal />` component for shared usages.

Benefits UI: Add delete benefits functionality

---

clients/apps/web/src/components/Dashboard/UpfrontRewards.tsx
clients/apps/web/src/components/Finance/Split.tsx
clients/apps/web/src/components/Shared/ConfirmModal.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierBenefitsForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierEditPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionsChart.tsx
clients/packages/polarkit/src/components/ui/atoms/Button.tsx
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

- Use input slots for percentage signs
- Adjust stroke width on subscription charts
- Conditional divider on Subscription cards
- Client-side validation for benefit descriptions
- Archiving functionality for Subscriptions Tiers
- Confirm UI color & margin adjustments

General UI Polish

---

server/polar/integrations/github/service/api.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/reference.py

Fix #875
Stumbled upon this issue while checking if we could clean up some things; and thought it would be a quick and easy one.
Let me know if this looks correct!

server/github: remove custom githubkit request headers implementation

---

server/polar/pledge/service.py
server/tests/pledge/test_endpoints.py

server/pledge: require billing email

---

server/polar/integrations/github/tasks/organization.py

server/organization: daily refresh metadata from github

---

clients/apps/web/src/app/(backer)/settings/page.tsx
clients/apps/web/src/components/Settings/GeneralSettings.tsx

clients/themeing: implement a theme picker in settings

---

clients/apps/web/src/components/Notifications/Popover.tsx

clients/notifications: fix unclickable links in notifications list

---

clients/apps/web/package.json
clients/apps/web/src/app/(backer)/settings/blob/page.tsx
clients/apps/web/src/app/(pledge)/[organization]/[repo]/issues/[number]/(create)/page.tsx
clients/apps/web/src/app/api/blob/upload/route.ts
clients/apps/web/src/components/Shared/Spinner.tsx
clients/pnpm-lock.yaml
server/Caddyfile
server/docker-compose.yml

https://github.com/polarsource/polar/assets/47952/68b85373-b46a-4654-923d-5d1e817ae9f0

clients/blob: blob store integration and image picker

---

clients/apps/web/src/components/Organization/OpenGraphImage.tsx
clients/apps/web/src/stories/IssueCard.stories.tsx
clients/apps/web/src/stories/OpenGraphImage.stories.tsx
clients/packages/polarkit/src/components/pledge/IssueCard.tsx

clients/og: add funding goal to issue OG image

---

clients/packages/sdk/src/client/apis/FundingApi.ts
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/funding/endpoints.py
server/polar/funding/service.py
server/tests/funding/test_service.py

Add full-text search to Funding API

---

clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx

This PR fixes several minor typos in naming of variables in the source code:
`showConnectUsell` -> `showConnectUpsell`
`isBackerConnectUpsellSkiped` -> `isBackerConnectUpsellSkipped`

clients/onboarding: fix typos

---

clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/apps/web/src/components/Organization/filters.ts
clients/packages/polarkit/src/hooks/queries/funding.ts

clients/public: hide closed issues by default

---

clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/apps/web/src/components/Subscriptions/PublicSubscriptionUpsell.tsx

clients/public: fix hydration issues

---

clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/packages/polarkit/src/components/ui/atoms/Paginator.stories.tsx
clients/packages/polarkit/src/components/ui/atoms/Paginator.tsx
clients/packages/polarkit/src/components/ui/atoms/index.ts
clients/packages/polarkit/src/hooks/queries/funding.ts

Implements a Pagniator component & pagination support on funding lists.
Fixes #1690.

Add Pagination support for Funded issues

---

clients/apps/web/src/components/Organization/IssuesLookingForFunding.tsx
clients/apps/web/src/components/Shared/Pagination.tsx
clients/packages/polarkit/src/components/ui/atoms/Paginator.tsx

Implements a `<Pagination />` component and a `usePagination` hook which can be used to easliy fascilitate the search params state of current page, etc.

clients/pagination: implement a shared pagination component with hook

---

clients/apps/web/src/app/(backer)/settings/page.tsx
clients/apps/web/src/app/(public)/[organization]/page.tsx
clients/apps/web/src/components/Organization/OrganizationPublicPage.tsx
clients/apps/web/src/components/Settings/SubscriptionSettings.tsx
clients/packages/polarkit/src/hooks/queries/org.ts
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

Implements a Subscription overview in Settings, with links to management, etc.

Implement Subscription overview in Settings

---

server/polar/reward/service.py
server/tests/reward/test_service.py

server/rewards: fix join

---

clients/apps/web/next.config.js
clients/apps/web/package.json
clients/apps/web/src/app/(backer)/feed/page.tsx
clients/apps/web/src/app/maintainer/[organization]/issues/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/[post]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/[post]/page.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/page.tsx
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Feed/Editor.tsx
clients/apps/web/src/components/Feed/Feed.tsx
clients/apps/web/src/components/Feed/Post.tsx
clients/apps/web/src/components/Feed/data.ts
clients/apps/web/src/components/Layout/BackerLayout.tsx
clients/apps/web/src/components/Layout/MaintainerLayout.tsx
clients/apps/web/src/components/Settings/Section.tsx
clients/apps/web/src/components/Shared/DashboardTopbar.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/pnpm-lock.yaml

Implements mocked Feed with markdown capabilitites. Behind the `feed` feature flag.

Implement mocked Feed

---

clients/apps/web/src/app/maintainer/[organization]/posts/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/[post]/ClientPage.tsx
clients/apps/web/src/components/Dashboard/IssueList.tsx
clients/apps/web/src/components/Feed/Editor.tsx
clients/apps/web/src/components/Feed/Feed.tsx
clients/apps/web/src/components/Feed/Posts/Post.tsx
clients/apps/web/src/components/Feed/Posts/meta/Code.tsx
clients/apps/web/src/components/Feed/Posts/meta/Meta.tsx
clients/apps/web/src/components/Feed/Posts/meta/Newsletter.tsx
clients/apps/web/src/components/Feed/Posts/meta/Poll.tsx
clients/apps/web/src/components/Feed/Posts/meta/Video.tsx
clients/apps/web/src/components/Feed/Recommendations/Recommendation.tsx
clients/apps/web/src/components/Feed/Recommendations/meta/Meta.tsx
clients/apps/web/src/components/Feed/Recommendations/meta/Rewards.tsx
clients/apps/web/src/components/Feed/data.ts

Implements recommendations in the Feed

Implement recommendations in Feed

---

server/polar/integrations/stripe/service.py
server/polar/pledge/endpoints.py
server/polar/pledge/payment_intent_service.py

server/pledge: set stripe payment intent description

---

server/polar/account/service.py

server/stripe: updated account naming convention

---

server/polar/article/endpoints.py
server/polar/article/schemas.py
server/polar/article/service.py
server/polar/authz/service.py
server/polar/models/article.py
server/tests/article/test_endpoints.py

server/article: byline, visibility, list API

---

clients/apps/web/src/app/maintainer/[organization]/posts/[post]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/posts/new/ClientPage.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Markdown/MarkdownComponents.tsx
clients/apps/web/src/components/Markdown/MarkdownEditor.tsx
clients/apps/web/src/components/Markdown/MarkdownPreview.tsx

Refactor Markdown editor/preview

Markdown editor

---

server/migrations/versions/2023-11-24_set_account_active_status.py
server/polar/account/service.py
server/polar/integrations/stripe/endpoints.py
server/polar/integrations/stripe/tasks.py
server/polar/models/account.py
server/polar/transaction/service/transfer.py
server/tests/transaction/service/test_transfer.py

Add an `active` status to Account

---

server/polar/funding/service.py
server/polar/issue/search.py
server/polar/issue/service.py

server/search: cleanup search query from special characters

---

clients/apps/web/src/app/(public)/[organization]/posts/[postSlug]/ClientPage.tsx
clients/packages/sdk/src/client/apis/ArticlesApi.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/article/service.py

clients/posts: track article views

---

clients/apps/web/src/components/Feed/Posts/Poll.tsx
clients/apps/web/src/components/Feed/Posts/markdown.tsx

Improve the Poll parser.
```
<poll option0="aa"></poll>
<poll>
1. Spring
2. Summer
3. Autumn
4. Winter
</poll>
<poll>
* aaa
* bbb
* ccc
* lol **bold**
</poll>
```

clients/Poll: improve parser

---

clients/apps/web/src/app/(email)/email/article/[id]/route.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Feed/PostEditor.tsx
clients/apps/web/src/components/Feed/PostToolbar.tsx
clients/apps/web/src/components/Feed/Posts/BrowserRender.tsx
clients/apps/web/src/components/Feed/Posts/Paywall.tsx
clients/apps/web/src/components/Feed/Posts/markdown.tsx

And while we're at it, style the <paywall> component

clients/articles: preview what the post looks like for free subscribers

---

clients/apps/web/src/components/Feed/Posts/BrowserEmbed.tsx
clients/apps/web/src/components/Feed/Posts/BrowserRender.tsx
clients/apps/web/src/components/Feed/Posts/EmailEmbed.tsx
clients/apps/web/src/components/Feed/Posts/EmailRender.tsx
clients/apps/web/src/components/Feed/Posts/markdown.tsx

```md
<embed src="https://github.com/zegl/kube-score/issues/534" />
<embed src="https://github.com/polarsource/polar/issues/1860" />
```

clients/article: issue embeds

---

clients/apps/web/src/components/Feed/Posts/BrowserEmbed.tsx
clients/apps/web/src/components/Feed/Posts/BrowserIframe.tsx
clients/apps/web/src/components/Feed/Posts/BrowserRender.tsx
clients/apps/web/src/components/Feed/Posts/EmailIframe.tsx
clients/apps/web/src/components/Feed/Posts/EmailRender.tsx
clients/apps/web/src/components/Feed/Posts/markdown.tsx

```md
<iframe width="560" height="315" src="https://www.youtube.com/embed/bPB8chYwtDU?si=j70h0gmLqJUHFPTQ&amp;start=5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/bPB8chYwtDU?si=j70h0gmLqJUHFPTQ&amp;controls=0&amp;start=5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
(broken on purpose)
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/em?si=j70h0gmLqJUHFPTQ&amp;controls=0&amp;start=5" title="YouTube video player" …
```

clients/article: youtube embeds

---

clients/apps/web/src/components/Subscriptions/TiersPage.tsx
clients/apps/web/src/stories/FinancePage.stories.tsx
clients/packages/polarkit/src/hooks/queries/index.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/account/schemas.py
server/polar/models/account.py
server/polar/subscription/service/subscription_tier.py
server/tests/subscription/service/test_subscription_tier.py
server/tests/subscription/test_endpoints.py

Prevent tiers creation without account

---

server/polar/integrations/stripe/schemas.py
server/polar/integrations/stripe/service.py
server/polar/transaction/service/payment.py
server/tests/transaction/service/test_payment.py

server/transaction: fix anonymous pledge payment not linked to user/pledge

---

clients/packages/polarkit/src/components/Issue/IssueSummary.tsx

clients/Issue: count all positive reactions as thumbs up

---

server/polar/integrations/stripe/tasks.py

Payment Intents for invoices have the metadata on the invoice, not on the pi. Fallback to checking the invoice if one exists.

server/stripe: handle payment_intent.succeeded events on invoices again

---

server/polar/models/subscription_tier.py
server/polar/subscription/service/subscribe_session.py
server/polar/subscription/service/subscription.py
server/polar/subscription/service/subscription_tier.py
server/polar/subscription/tasks.py
server/tests/subscription/service/test_subscription.py
server/tests/subscription/service/test_subscription_tier.py
server/tests/subscription/test_tasks.py

Update benefits grants when tiers benefits are added/deleted

---

server/tests/article/test_service.py

Following fix in 2e0826c64f36275275236d5736dc927159451b8b

server/article: add more tests to service

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/[post]/ClientPage.tsx
clients/apps/web/src/components/Feed/PostToolbar.tsx
clients/apps/web/src/components/Feed/Publishing/PublishSettings.tsx
clients/apps/web/src/components/Feed/Publishing/PublishSummary.tsx
clients/apps/web/src/components/Feed/Publishing/PublishingTimePicker.tsx
clients/apps/web/src/components/Feed/Publishing/useArticleActions.ts

* Support making an article hidden or private after it's been published
* Support "Publish Now" for articles that are currently scheduled for the future
* Fix inconsistencies in for what accounts as `isPublished`
* ... and other smaller fixes

clients/article: various bugfixes to the publishing and settings flow

---

clients/apps/web/src/components/Feed/Posts/BrowserRender.tsx
clients/apps/web/src/components/Feed/Posts/SyntaxHighlighter.tsx

clients/article: fix code blocks and inline code

---

server/polar/article/tasks.py

clients/articles: handle email rendering as utf-8

---

clients/apps/web/src/components/Subscriptions/OverviewPage.tsx
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
server/polar/subscription/endpoints.py
server/polar/subscription/service/subscription.py
server/tests/subscription/service/test_subscription.py

Allow to query subscriptions stats by multiple types

---

clients/apps/web/src/app/(installation)/github/session/page.tsx

clients/web: fix flashing error message on GitHub OAuth callback

---

clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx
clients/apps/web/src/components/Subscriptions/OverviewPage.tsx
clients/apps/web/src/components/Subscriptions/SubscribersPage.tsx
clients/packages/sdk/src/client/apis/ArticlesApi.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/subscription/endpoints.py
server/polar/subscription/schemas.py
server/polar/subscription/service/subscription.py
server/tests/fixtures/random_objects.py
server/tests/subscription/test_endpoints.py

Subscriptions: hide emails in public APIs

---

clients/apps/web/src/app/(installation)/github/session/page.tsx

This reverts commit d50dba19ba99cb5a15a4c56b41d1f0c2f5009959.

Revert "clients/web: fix flashing error message on GitHub OAuth callback"

---

clients/packages/polarkit/src/components/Issue/IssueSummary.tsx

clients/IssueSummary: link to Polar

---

clients/apps/web/src/app/og/route.tsx

clients/og: skip custom fonts (use built in Noto-Sans for now)

---

clients/apps/web/src/components/Organization/OpenGraphImageFunding.tsx

To be fixed again later... this should at least get the image generation up and running again

clients/og: disable broken parts in OG

---

README.md
clients/apps/web/next.config.js
clients/apps/web/src/components/Organization/Footer.tsx
clients/apps/web/src/components/Pledge/PledgeCheckoutContribute.tsx

all: update links to FAQ

---

clients/apps/web/src/components/Feed/useEditorHelpers.ts

clients/posts: add GitHub-like keyboard shortcut to editor

---

clients/apps/web/src/app/(backer)/settings/page.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/settings/ClientPage.tsx
clients/apps/web/src/components/Settings/WebhookNotificationSettings.tsx

clients/webhooks: add hook settings to orgs

---

server/polar/models/subscription_tier.py
server/polar/models/subscription_tier_benefit.py
server/polar/subscription/service/subscription.py
server/polar/subscription/service/subscription_tier.py
server/tests/subscription/conftest.py
server/tests/subscription/service/test_subscribe_session.py
server/tests/subscription/service/test_subscription.py
server/tests/subscription/service/test_subscription_tier.py
server/tests/subscription/test_endpoints.py

This reverts commit a17e879cc5874f280d1944a4ff4dbfb6e0a66a35 and a80c000645fd59390a76729889018c1b95526c85
Fix #2055

server/subscription: eager load subscription tier benefits

---

clients/apps/web/src/components/Shared/Topbar.tsx

clients/Topbar: prevent flex shrinking

---

clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/ClientPage.tsx
clients/apps/web/src/components/Subscriptions/OrganizationSubscriptionsPublicPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionGroupIcon.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCelebration.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierForm.tsx
clients/apps/web/src/components/Subscriptions/utils.tsx
clients/packages/sdk/src/client/models/index.ts
server/migrations/versions/2024-01-04_migrate_subscriptiontiertype.py
server/polar/models/subscription_tier.py
server/polar/subscription/schemas.py
server/polar/subscription/service/subscription_tier.py
server/tests/subscription/conftest.py
server/tests/subscription/service/test_subscription_tier.py
server/tests/subscription/test_endpoints.py

Restructure subscription tier types

---

clients/apps/web/src/components/Feed/PostEditor.tsx
clients/apps/web/src/components/Feed/useEditorHelpers.ts

clients/editor: upload files without breaking undo history

---

clients/apps/web/src/components/Feed/Posts/SyntaxHighlighter/styles.ts

clients/syntax: add italics to light theme

---

clients/apps/web/src/components/Organization/FreeTierSubscribe.tsx
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

Fix loading indicators, properly reload data after submits, etc
Fixes #2054

clients/subscriptions: interactivity improvements on subscribe button

---

clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx

clients/posts: differentiate between no posts and loading posts

---

clients/apps/web/src/app/(backer)/loading.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/loading.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/issues/loading.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/loading.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/subscriptions/loading.tsx

Render a placeholder skeleton while waiting for the first render of components.
https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

clients: add loading.tsx where it makes sense

---

clients/apps/web/src/components/Transactions/TransactionsList.tsx

clients/finance: fix transaction description detection

---

clients/apps/web/src/app/(backer)/benefits/ClientPage.tsx

clients/benefits: make Buttons asChild

---

server/polar/subscription/endpoints.py
server/tests/subscription/conftest.py

To merge whenever we're ready 🚀

server/subscription: remove feature flag

---

clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/page.tsx

clients/posts: server side loading and rendering of posts and subscriptions data

---

server/polar/integrations/github/tasks/badge.py

server/github: improve embed badge tasks resiliency

---

clients/apps/web/src/components/Feed/Posts/BrowserMermaid.tsx
clients/apps/web/src/components/Feed/Posts/BrowserRender.tsx
clients/apps/web/src/components/Feed/Posts/SyntaxHighlighter/BrowserSyntaxHighlighter.tsx

clients/mermaid: add loading indicator

---

clients/apps/web/src/app/(public)/[organization]/(layout)/LayoutTopbarAuth.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/LayoutTopbarGitHubLogin.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/layout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx
clients/apps/web/src/components/Shared/TopbarRight.tsx

Page without JS:
Logged out without JS:

clients/public: serverside load authenticated user

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/ClientPage.tsx
clients/apps/web/src/components/Feed/Posts/Post.tsx

Makes the non-JS browsing experience a little bit better :)

clients/posts: add <Link> to <AnimatedIconButton> in posts list

---

clients/apps/web/next.config.js

Preparing for moving blog.polar.sh to the next app

clients: configure blog.polar.sh redirects in next app

---

clients/apps/web/src/app/(email)/email/article/[id]/route.tsx

clients/web: try to fix article email rendering

---

clients/apps/web/src/app/(email)/email/article/[id]/route.tsx

In hopes that this fixes the react-email <Tailwind> errors

clients/email: remove dark mode

---

clients/apps/web/src/components/Settings/SubscriptionSettings.tsx
clients/apps/web/src/components/Shared/ConfirmModal.tsx

clients/unsub: remove vague unsub text

---

clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx

clients/tiers: dont show separator if no benefits

---

clients/apps/web/src/components/Feed/Markdown/__snapshots__/render.test.tsx.snap
clients/apps/web/src/components/Feed/Markdown/markdown.tsx
clients/apps/web/src/components/Feed/Markdown/render.test.tsx

clients/markdown: handle double whitespace as newline

---

clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Shared/ProfileSelection.tsx

clients/dashboard: proper page reload after logout

---

clients/apps/web/src/app/(backer)/benefits/ClientPage.tsx
clients/apps/web/src/app/(backer)/benefits/page.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx
clients/apps/web/src/app/(public)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
clients/apps/web/src/components/Benefit/Benefit.tsx
clients/apps/web/src/components/Benefit/BenefitRow.tsx
clients/apps/web/src/components/Organization/FreeTierSubscribe.tsx
clients/apps/web/src/components/Settings/SubscriptionSettings.tsx
clients/apps/web/src/components/Subscriptions/OverviewPage.tsx
clients/apps/web/src/components/Subscriptions/SubscribersPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierBenefitsForm.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierSubscribeButton.tsx
clients/packages/polarkit/src/hooks/queries/subscriptions.ts
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
clients/packages/sdk/src/client/models/index.ts
server/migrations/versions/2024-01-12_migrate_custom_subscriptionbenefit_.py
server/polar/models/subscription_benefit.py
server/polar/models/user.py
server/polar/subscription/endpoints.py
server/polar/subscription/schemas.py
server/polar/subscription/service/subscription.py
server/polar/subscription/service/subscription_benefit.py
server/tests/funding/test_endpoints.py
server/tests/subscription/conftest.py
server/tests/subscription/service/test_subscription.py
server/tests/subscription/service/test_subscription_benefit.py
server/tests/subscription/service/test_subscription_benefit_grant.py
server/tests/subscription/test_endpoints.py

Update Subscriptions API and add custom note to benefit

---

server/polar/subscription/endpoints.py

server/subscription: silently swallow AlreadySubscribed when importing

---

server/tests/subscription/test_endpoints.py

server/subscriptions: add subscriptions test

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/new/ClientPage.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Feed/Markdown/markdown.tsx
clients/apps/web/src/components/Feed/PostPaywall.tsx
clients/packages/polarkit/testdata.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/article/schemas.py
server/polar/article/service.py
server/tests/article/test_endpoints.py
server/tests/article/test_schemas.py
server/tests/article/test_service.py

Premium articles preview

---

clients/apps/web/src/app/(public)/[organization]/(layout)/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/ClientPage.tsx
clients/apps/web/src/components/Feed/Feed.tsx
clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx

- clients/page: Link to dashboard overview vs. issues
- clients/page: Profile name to link back home
- clients/page: Update copy a bit

Minor public page polish

---

clients/apps/web/src/app/(public)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/[post]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/new/ClientPage.tsx
clients/apps/web/src/components/Feed/LongformPost.stories.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Feed/PostEditor.tsx
clients/packages/sdk/src/client/models/index.ts
server/polar/subscription/schemas.py

clients/articles: upsell card to upgrade from free to paid subscriptions

---

docs/docs/maintainers/ads/index.md

Some typos

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/ClientPage.tsx

clients/posts: fix analytics sticky on small displays

---

clients/apps/web/src/components/Accounts/AccountSetup.tsx
clients/packages/polarkit/src/components/ui/atoms/Button.tsx
clients/packages/polarkit/src/components/ui/atoms/CountryPicker.tsx
clients/packages/polarkit/src/components/ui/command.tsx

Searchable country picker

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/subscriptions/benefits/ClientPage.tsx

clients/benefits: copy-pastable markdown snippet for ads

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/subscriptions/subscribers/page.tsx
clients/apps/web/src/components/Subscriptions/SubscribersPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionStatusSelect.tsx
clients/packages/polarkit/src/hooks/queries/subscriptions.ts

clients/subscribers: add ability to filter active/canceled subscribers

---

clients/apps/web/src/components/Settings/AuthenticationSettings.tsx
clients/apps/web/src/components/Settings/ConnectedAppSettings.tsx
clients/packages/sdk/src/client/models/index.ts
server/polar/user/schemas.py

clients/oauth: show oauth usernames if exists

---

clients/apps/web/src/components/Feed/Publishing/PublishSettings.tsx

clients/editor: change slug without publishing

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/posts/ClientPage.tsx

clients/posts: analytics side by side on small screens

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/subscriptions/benefits/ClientPage.tsx

clients/benefits: dark theme for recommended benefits

---

clients/apps/web/src/app/(topbar)/(backer)/feed/page.tsx

To make sure that the user onboarding status is correct
Fixes #2466

clients/feed: refresh user data

---

clients/apps/web/src/app/(topbar)/[organization]/(layout)/layout.tsx

Fixes responsiveness for articles with code blocks.

clients/public: force post responsiveness

---

clients/apps/web/src/components/Feed/Markdown/SyntaxHighlighter/SyntaxHighlighter.tsx

clients/web: prevent empty lines when copying highlighted code

---

clients/apps/web/src/app/(topbar)/[organization]/(layout)/layout.tsx
clients/apps/web/src/app/(topbar)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Feed/PostPaywall.tsx
clients/apps/web/src/components/Organization/OrganizationPublicPageNav.tsx
clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx

clients/posts: optimize posts view for mobile

---

server/polar/magic_link/email_templates/magic_link.html
server/polar/magic_link/endpoints.py
server/polar/magic_link/service.py
server/tests/magic_link/test_service.py
server/tests/magic_link/testdata/magic_link_return_to.html

Fixes the HTML encoding of the return_to parameter in magic links

server/magic_link: fix links with return_to parameter

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/funding/ClientPage.tsx
clients/packages/polarkit/src/hooks/queries/pledges.ts
clients/packages/sdk/src/client/apis/PledgesApi.ts
server/polar/pledge/endpoints.py

/maintainer/ORG/funding will now show pledges made by the _user_ ORG, if ORG is a personal org.

clients/funding: show user pledges on personal org pages

---

clients/apps/web/src/components/Subscriptions/TiersPage.tsx
clients/apps/web/src/components/Transactions/AccountBanner.tsx
clients/packages/polarkit/src/components/ui/atoms/ShadowBox.tsx

clients/subscriptions: updated onboarding banner

---

clients/apps/web/src/app/(topbar)/[organization]/(layout)/posts/[postSlug]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(white)/posts/[post]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(white)/posts/new/ClientPage.tsx
clients/apps/web/src/components/Feed/LongformPost.tsx
clients/apps/web/src/components/Feed/PostEditor.tsx

Fixes #2510 
---
Might also be worth implementing some sort of check on the backend too. I had a look through the API, but I'd like to better understand how you folks would like this implemented

fix: don't show upsell to self

---

clients/apps/web/src/components/Feed/LongformPost.tsx

clients/posts: disable image shadows on small screens

---

clients/apps/web/src/components/Feed/Markdown/__snapshots__/render.test.tsx.snap
clients/apps/web/src/components/Feed/Markdown/markdown.tsx
clients/apps/web/src/components/Feed/Markdown/render.test.tsx

clients/markdown: allow same-page anchor links

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/overview/SubscriptionsOverview.tsx
server/polar/subscription/service/subscription.py

Tweak subscriptions statistics

---

clients/packages/polarkit/src/components/ui/atoms/Button.tsx

Was accidentally broken here: https://github.com/polarsource/polar/commit/7c882f3df880a4ce007bf5ea9dc10ce69b15fc17#diff-a441ee75a4131a2507fed267fb6ccbf867780a04cc8f313c830ea48e848d1033

clients/Button: fix disabled state

---

clients/apps/web/src/app/(topbar)/(backer)/subscriptions/ClientPage.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionsMetric.tsx
clients/apps/web/src/components/Transactions/TransactionsList.tsx
clients/packages/polarkit/src/components/ui/atoms/FormattedDateTime.tsx

Shows 'Feb 2024' instead of '1 Feb 2024'

clients/subscroptions: month label for stats instead of date of first day in period

---

server/polar/api.py
server/polar/auth/endpoints.py
server/polar/auth/schemas.py
server/polar/config.py
server/polar/kit/jwt.py

Extracted from #2681
Updates #2632

server/auth: custom domain auth exchange api

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/promote/ClientPage.tsx

Fix typo in light theme tier embed

---

clients/apps/web/src/app/[organization]/(sidebar)/ClientPage.tsx
clients/apps/web/src/components/Form/ImageUpload.tsx

clients/og-image: Fix squashed OG image on Publish page

---

server/polar/article/tasks.py

server/articles: set Reply-To header when sending article as email

---

clients/apps/web/src/app/[organization]/(sidebar)/ClientPage.tsx
clients/apps/web/src/app/[organization]/(sidebar)/layout.tsx
clients/apps/web/src/app/[organization]/(sidebar)/page.tsx
clients/apps/web/src/components/Organization/FreeTierSubscribe.tsx
clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierSubscribeButton.tsx

clients/public: load more data serverside

---

server/polar/funding/service.py

server/funding: do not include deleted issues

---

clients/apps/web/src/app/[organization]/(sidebar)/layout.tsx
clients/apps/web/src/components/Organization/OrganizationPublicSidebar.tsx

clients/public: make layout fit more (small-ish) screen sizes

---

server/polar/auth/endpoints.py
server/polar/auth/service.py
server/polar/integrations/discord/endpoints.py
server/polar/integrations/github/endpoints.py
server/polar/kit/jwt.py
server/polar/subscription/schemas.py
server/tests/fixtures/auth.py

Backwards compatible with untyped long lived tokens already in the wild

server/jwt: add and validate types to all jwts

---

server/polar/integrations/github/service/user.py
server/polar/reward/endpoints.py
server/polar/reward/service.py
server/polar/subscription/endpoints.py
server/polar/subscription/service/benefits/github_repository.py
server/polar/user/oauth_service.py
server/polar/user_organization/schemas.py
server/polar_backoffice/screens/accounts/list.py

Explicit handling of usernames, and where it comes form

server/users: move away from user.username

---

clients/apps/web/src/app/maintainer/[organization]/(white)/posts/[post]/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(white)/posts/new/ClientPage.tsx

Only load data from the server _once_. After that, all edits is coming from the client

clients/posts/editor: one way data binding

---

server/polar/integrations/stripe/service.py
server/polar/transaction/service/payout.py

server/transaction: handle already transferred Stripe balances on payout

---

server/polar/integrations/github/service/issue.py

This was an accidental regression a few days ago.
https://github.com/polarsource/polar/pull/2805/files#diff-5c8892be5fb594b1f700efc4bde270a05011a67327906320601cfd2375a72f19L324-L325

server/issue: fix issue syncing for 404s

---

clients/apps/web/src/app/maintainer/[organization]/(white)/posts/new/ClientPage.tsx

clients/posts: clear form cache on all save paths

---

clients/apps/web/src/app/maintainer/[organization]/(white)/posts/new/ClientPage.tsx
clients/packages/polarkit/src/hooks/queries/articles.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/article/schemas.py
server/polar/article/service.py
server/tests/article/test_endpoints.py

Base64 encoded posts over the wire

---

server/polar/subscription/service/subscription_benefit_grant.py
server/polar/subscription/tasks.py

Logs, logs everywhere!
---
💡 Would love a service to generate memes automatically with a dynamic url:
`https://coolmeme.com?template=buzz&top=Logs&bottom=Logs+everywhere`

server/subscription: add logging when granting/revoking benefits

---

clients/apps/web/src/app/embed/posts.svg/route.tsx
clients/apps/web/src/app/embed/tiers.svg/route.tsx

clients/og: remove cache from og images

---

clients/apps/web/src/components/Profile/DescriptionEditor/DescriptionEditor.tsx

clients/description: add suppressContentEditableWarning

---

server/polar/integrations/stripe/service.py
server/polar/integrations/stripe/service_pledge.py
server/polar/pledge/payment_intent_service.py
server/polar/pledge/service.py
server/tests/pledge/test_service.py

To make space for donation related stripe features :)

server/stripe: move pledge-only features to new service

---

clients/apps/web/src/app/[organization]/(sidebar)/posts/[postSlug]/page.tsx
clients/apps/web/src/app/maintainer/[organization]/(white)/posts/[post]/ClientPage.tsx

Might fix the behaviour observed in #2953

clients/articles: invalidate serverside cache on save

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/promote/ClientPage.tsx
clients/apps/web/src/app/maintainer/[organization]/(topbar)/promote/page.tsx

... and simplify org loading
Fixes #2809

clients/promote: remove install app banner

---

clients/apps/web/src/app/[organization]/(sidebar)/layout.tsx
clients/apps/web/src/components/Feed/Posts/Post.tsx
clients/apps/web/src/components/Onboarding/Creator/CreatorUpsell.tsx
clients/apps/web/src/components/Profile/CreatorEditor/CreatorsEditor.tsx
clients/apps/web/src/components/Profile/ProjectEditor/ProjectCard.tsx
clients/apps/web/src/components/Profile/ProjectEditor/ProjectsEditor.tsx

clients/public: responsiveness improvements to tablet sized devices

---

server/polar/subscription/service/subscription_tier.py
server/tests/subscription/service/test_subscription_tier.py

server/subscriptions: fix bad join in tiers search and pagination

---

clients/apps/web/src/app/[organization]/(sidebar)/layout.tsx
clients/apps/web/src/app/[organization]/[repo]/layout.tsx
clients/apps/web/src/app/[organization]/subscribe/layout.tsx
clients/apps/web/src/components/Profile/SubscriptionTierEditor/SubscriptionTierEditor.tsx

Slim down width on public pages to address this misalignment:

Adjust max-width for public pages

---

server/polar/subscription/service/subscription_tier.py
server/tests/subscription/service/test_subscription_tier.py

server/subscription: fix `include_archived` search filter for repository's tiers

---

clients/apps/web/src/components/Issues/BadgeMessageForm.tsx

clients/web: make badge preview consistent with the embed badge

---

clients/apps/web/src/components/Feed/useEditorHelpers.ts

clients/web: insert uploaded image at original cursor position

---

server/polar/donation/schemas.py
server/tests/donation/conftest.py
server/tests/donation/test_endpoints.py

server/donation: updated DonationUser avatar_url type

---

clients/apps/web/src/app/maintainer/[organization]/(white)/posts/[post]/ClientPage.tsx

clients/web: always save post when switching to Settings/Publish tab

---

clients/apps/web/src/components/Transactions/WithdrawModal.tsx
clients/apps/web/src/hooks/queries/transactions.ts

clients/web: handle payout estimate error message

---

clients/apps/web/src/app/[organization]/(sidebar)/donate/ClientPage.tsx
clients/apps/web/src/app/[organization]/[repo]/issues/[number]/(create)/page.tsx

clients/pledge: redirect closed issues to donations

---

clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx

clients/PledgeBadge: fix issue status detection

---

clients/apps/setup-github/package.json
clients/apps/web/next.config.js
clients/apps/web/package.json
clients/examples/next-js-example/package.json
clients/package.json
clients/pnpm-lock.yaml

Reverts polarsource/polar#3106

Revert "clients: update nextjs to 14.2"

---

server/polar/integrations/discord/service.py
server/polar/integrations/github/endpoints.py

server/benefits: fix `subscription.subscription_benefit.precondition_fulfilled` enqueue call

---

server/migrations/versions/2024-04-15-1126_rename_.py

server/notifications: migrate SubscriptionBenefitPreconditionErrorNotification to BenefitPreconditionErrorNotification

---

server/polar/eventstream/endpoints.py

server/eventstream: gracefully close pubsub loop when Uvicorn exits

---

server/poetry.lock
server/polar/account/service.py
server/polar/integrations/stripe/endpoints.py
server/polar/integrations/stripe/service.py
server/polar/integrations/stripe/utils.py
server/polar/pledge/payment_intent_service.py
server/pyproject.toml

server: upgrade Stripe

---

server/polar/benefit/tasks.py

server/benefit: fix benefit_force_free_articles by passing unresolved scope to subsequent task

---

server/poetry.lock
server/polar/webhook/tasks.py
server/pyproject.toml
server/tests/webhooks/test_webhooks.py

Prevent sending webhooks to internal URLs, etc

server/webhooks: validate url

---

docs/docs/maintainers/issue-funding/index.md

docs: correct issues-links

---

server/polar/auth/service.py

Reverts polarsource/polar#3174

Revert "server/auth: complete auth JWT migration"

---

clients/apps/web/src/app/api/github/[org]/[repo]/issues/[number]/pledge.svg/route.tsx

clients/pledge-embed: fix width issues

---

server/polar/integrations/github/service/reference.py

server/github: fix logging error

---

server/polar/transaction/service/payout.py
server/polar/transaction/tasks.py

This will avoid problems if one of the payout fails in the middle (e.g dangling payouts!)

server/transaction: run each Stripe payout trigger in its own job

---

server/polar/order/service.py
server/tests/order/test_service.py

server/order: fix Stripe invoice handling when there is proration

---

flake.lock
flake.nix

Not intended or certain to be used. Just Birk experimenting for personal use at
the moment.

Polar Development Flake

---

clients/apps/web/package.json
clients/apps/web/src/components/Landing/LandingLayout.tsx
clients/apps/web/src/components/Landing/LandingPage.tsx
clients/apps/web/src/components/Landing/LastPitch.tsx
clients/pnpm-lock.yaml

- **website: Remove unnecessary extra separator**
- **website: Custom GitHub button in header**
- **website: Minor copy tweak in last section**

website: Custom GitHub button

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/sales/subscriptions/ClientPage.tsx
server/polar/subscription/service.py

Explicitly show pending subscriptions cancellations

---

clients/apps/web/src/components/Documentation/Navigation.tsx

- **docs: Colorize API method pills**
- **docs: Rename "Overview" to "Product Guides"**

docs: Navigation enhancements

---

clients/apps/web/src/components/Documentation/BodySchema.tsx
clients/apps/web/src/components/Documentation/Parameters.tsx
clients/apps/web/src/components/Documentation/PropertyDefault.tsx
clients/apps/web/src/components/Documentation/Schema.tsx

clients/web/docs: show defaults on parameters

---

server/polar/organization/tasks.py

We experienced in prod `organization.post_install` triggered twice. Adding a lock here to prevent a race condition.

server/organization: add a lock around organization_post_creation_actions

---

clients/apps/web/jest.setup.ts
clients/apps/web/src/components/SyntaxHighlighterShiki/SyntaxHighlighterClient.tsx

Attempt to fix #3622
Not sure to merge it though, I fear the bundle size might explode.

clients/web: use full bundle for client-side Shiki

---

clients/apps/web/src/app/[organization]/(sidebar)/donate/page.tsx
clients/apps/web/src/app/[organization]/(sidebar)/page.tsx
clients/apps/web/src/app/[organization]/(sidebar)/posts/[postSlug]/page.tsx
clients/apps/web/src/app/[organization]/(sidebar)/products/page.tsx
clients/apps/web/src/app/[organization]/(sidebar)/subscriptions/page.tsx
clients/apps/web/src/app/[organization]/[repo]/page.tsx
clients/apps/web/src/app/[organization]/subscribe/page.tsx
clients/apps/web/src/app/embed/tiers.svg/route.tsx
clients/apps/web/src/hooks/queries/products.ts
clients/packages/sdk/openapi/source.json
clients/packages/sdk/openapi/updated.json
clients/packages/sdk/src/client/apis/BenefitsApi.ts
clients/packages/sdk/src/client/apis/ProductsApi.ts
server/polar/benefit/endpoints.py
server/polar/product/endpoints.py
server/polar/product/service/product.py
server/tests/product/service/test_product.py

Products API: replace `include_archived` by `is_archived`

---

clients/apps/web/next.config.mjs

Apply it first so it's not catched by the /docs rewrite.

clients/web: fix Posthog rewrite under docs.polar.sh

---

server/polar/transaction/service/processor_fee.py
server/tests/transaction/service/test_processor_fee.py

server/transaction: fix Stripe processor fee type that has changed

---

server/polar/account/service.py
server/polar/advertisement/endpoints.py
server/polar/article/service.py
server/polar/auth/service.py
server/polar/backoffice/endpoints.py
server/polar/backoffice/pledge_service.py
server/polar/benefit/endpoints.py
server/polar/checkout/endpoints.py
server/polar/file/endpoints.py
server/polar/integrations/github/tasks/repo.py
server/polar/integrations/github_repository_benefit/endpoints.py
server/polar/issue/schemas.py
server/polar/issue/service.py
server/polar/kit/template.py
server/polar/notifications/endpoints.py
server/polar/notifications/service.py
server/polar/payment_method/endpoints.py
server/polar/personal_access_token/endpoints.py
server/polar/pledge/payment_intent_service.py
server/polar/pull_request/schemas.py
server/polar/pull_request/service.py
server/polar/repository/endpoints.py
server/polar/reward/service.py
server/polar/traffic/endpoints.py
server/polar/user/endpoints/downloadables.py
server/polar/user/endpoints/user.py
server/polar/user_organization/service.py
server/polar/webhook/endpoints.py
server/polar/webhook_notifications/service.py

server: remove unused log instances

---

clients/apps/web/src/app/maintainer/[organization]/(topbar)/overview/ClientPage.tsx
clients/apps/web/src/components/Issues/IssuePromotionModal.tsx
clients/apps/web/src/components/Widgets/SubscribersWidget.tsx

Also adjusts the Issue List callout "Badged" to "Edit Badge".

clients/overview: replace mrr with subscriber count

---

server/polar/magic_link/endpoints.py

server/magic_link: escape token value when rendering interstitial auth page

---

clients/apps/web/src/components/Products/ProductForm.tsx
clients/apps/web/src/utils/auth.ts
clients/packages/sdk/openapi/source.json
clients/packages/sdk/openapi/updated.json
clients/packages/sdk/src/client/apis/MagicLinkApi.ts
clients/packages/sdk/src/client/apis/Oauth2Api.ts
clients/packages/sdk/src/client/models/index.ts
server/polar/kit/schemas.py
server/polar/product/schemas.py

Found a clever trick (🤓) to force Pydantic to output a discriminated union as a ref schema.

Fix ProductPrice being generated several times in OpenAPI spec

---

flake.lock

update nixpkgs to get latest stripe cli

chore: flake update

---

clients/apps/web/src/components/Documentation/openapi.ts

I really should stop doing things after 6pm.

docs: remove nasty console.log

---

clients/apps/web/src/components/Landing/API.tsx
clients/apps/web/src/components/Landing/Benefits.tsx
clients/apps/web/src/components/Landing/MOR.tsx
clients/apps/web/src/components/Landing/Monetization.tsx

- **website: Updated product section copy**
- **website: Updated funding section copy**
- **website: Updated funding section**
- **website: Updated MOR section**
- **website: Updated API section**

Update website copy

---

clients/apps/web/src/app/dashboard/(onboarding)/create/ClientPage.tsx

clients/web: improve organization slug generation and show server error message if any

---

clients/apps/web/src/app/dashboard/(onboarding)/create/ClientPage.tsx

client: Create Organization button clear existing error

---

clients/apps/web/src/components/Landing/TopbarNavigation.tsx

- **clients: Fix incorrect FAQ link on website**
- **clients: Docs navigation copy changes**

website: Fix FAQ link

---

clients/apps/web/src/app/dashboard/(onboarding)/create/ClientPage.tsx

clients/web: don't disable create organization button when errors are present

---

clients/apps/web/src/app/docs/(mdx)/merchant-of-record/tax/page.mdx
clients/apps/web/src/components/Landing/Hero/Hero.tsx
clients/apps/web/src/components/Landing/MOR.tsx

- **docs: Updated merchant of record docs**
- **website: Clarify Merchant of Record on site**
- **website: Clarify Merchant of Record on site + copy tweaks**

website: Clarify MOR

---

clients/apps/web/src/app/docs/api/(mdx)/webhooks/page.mdx

Docs: Fix typo in webhook section

---

server/polar/product/schemas.py

server: Set minimum product price of $0.5

---

clients/apps/web/src/components/Auth/GetStartedButton.tsx

Horrible mistake forgetting the `=`...

clients: Fix signup redirection URL to dashboard

---

clients/apps/web/next.config.mjs
clients/apps/web/src/app/dashboard/[organization]/promote/ClientPage.tsx

- **clients: Redirect former /:slug/subscriptions to /:slug**
- **clients: Update Tier embed URL**

Fix /:slug/subscriptions to /:slug redirect

---

clients/apps/web/src/app/(topbar)/(backer)/(sidebar)/funding/page.tsx

Update funding app page banner ui

---

clients/apps/web/src/components/Products/ProductMediasField/index.tsx

note: tested by modifying copy in browser. feel free to modify copy and merge w/o permission :)

clients/web: revise copy on media uploads

---

clients/packages/sdk/openapi/source.json
clients/packages/sdk/openapi/updated.json
clients/packages/sdk/src/client/apis/BenefitsApi.ts
clients/packages/sdk/src/client/models/index.ts
sdk/overlays/product_price_discriminator.yml
server/polar/benefit/schemas.py
server/polar/integrations/aws/s3/schemas.py
server/polar/kit/schemas.py
server/polar/subscription/schemas.py

Mainly because of the webhook definitions. Forcing the JSON schema mode solves most of it.

Tweak schema generation so it doesn't generate Input/Output schema when not necessary

---

server/poetry.lock
server/pyproject.toml

Fix deploy not working on Render

server: move taskipy to production dependecies

---

server/poetry.lock
server/pyproject.toml

Fix deploy not working on Render

server: move psycopg2-binary to production dependencies

---

clients/apps/web/src/app/docs/api/(mdx)/webhooks/page.mdx
server/polar/integrations/github/tasks/badge.py
server/polar/integrations/loops/tasks.py
server/polar/integrations/stripe/tasks.py
server/polar/webhook/tasks.py
server/polar/worker.py
server/tests/webhooks/test_webhooks.py

Stripe tasks retries and backoff

---

clients/apps/web/src/app/[organization]/(header)/layout.tsx
clients/apps/web/src/components/Auth/GetStartedButton.tsx
clients/apps/web/src/components/Layout/PolarMenu.tsx
clients/apps/web/src/components/Layout/Public/TopbarRight.tsx
clients/packages/sdk/openapi/source.json
clients/packages/sdk/openapi/updated.json
clients/packages/sdk/src/client/models/index.ts
server/polar/user/schemas/user.py

- **server: Add flywheel flag on user attribution**
- **clients: Set flywheel flag on storefront signups**
- **server: Save flywheel storefront ID**
- **clients: Save storefront ID in creator flywheel signup**

Storefront flywheel attribution

---

clients/apps/web/src/app/(installation)/github/installation/page.tsx
clients/apps/web/src/app/dashboard/(create)/create/ClientPage.tsx
clients/apps/web/src/app/dashboard/[organization]/(white)/posts/[post]/ClientPage.tsx
clients/apps/web/src/components/Auth/GetStartedButton.tsx
clients/apps/web/src/components/Auth/GithubLoginButton.tsx
clients/apps/web/src/components/Auth/GoogleLoginButton.tsx
clients/apps/web/src/components/Auth/Login.tsx
clients/apps/web/src/components/Auth/MagicLinkLoginForm.tsx
clients/apps/web/src/components/Documentation/OAuthSettings.tsx
clients/apps/web/src/components/Landing/LandingLayout.tsx
clients/apps/web/src/components/Layout/PolarMenu.tsx
clients/apps/web/src/components/Layout/Public/TopbarRight.tsx
clients/apps/web/src/hooks/auth.ts
clients/apps/web/src/utils/posthog.ts
server/polar/integrations/github/endpoints.py
server/polar/integrations/github/service/user.py
server/polar/integrations/google/endpoints.py
server/polar/integrations/google/service.py
server/polar/magic_link/endpoints.py
server/polar/magic_link/service.py
server/polar/order/service.py
server/polar/organization/service.py
server/polar/pledge/payment_intent_service.py
server/polar/posthog.py
server/polar/subscription/service.py
server/polar/user/service/user.py
server/scripts/anonymous_pledge_migration.py
server/tests/magic_link/test_endpoints.py
server/tests/magic_link/test_service.py

- **server: Posthog set user signup attribution**
- **clients: Posthog reset on logout**
- **server: Posthog user identify & signup + login events**
- **clients: Sync posthog event types with backend**
- **clients: posthog.capture user:(signup|login):view**
- **clients: posthog.capture user:signup:click**
- **clients: posthog.capture user:(signup|login):submit**
- **clients: posthog.capture organizations:create:(view|submit)**
- **server: posthog.capture organizations:create:done**
- **clients: wrap user:(signup|login):view in useEffect**

Posthog: Signup events

---

server/polar/integrations/github/service/paginated.py
server/polar/worker.py

Make sure we have the same state and logic applied across workers!

server/worker: use common hooks for default worker and github crawler worker

---

server/polar/integrations/github/endpoints.py
server/polar/integrations/github/service/issue.py
server/polar/integrations/github/service/user.py
server/polar/integrations/google/endpoints.py
server/polar/integrations/google/service.py
server/polar/integrations/loops/client.py
server/polar/integrations/loops/service.py
server/polar/magic_link/endpoints.py
server/polar/models/organization.py
server/polar/order/service.py
server/polar/organization/service.py
server/polar/personal_access_token/service.py
server/polar/pledge/payment_intent_service.py
server/polar/pledge/service.py
server/polar/product/service/product.py
server/polar/subscription/service.py
server/polar/user/service/user.py
server/tests/fixtures/file.py

- **server: Only create Loops contacts for creators**
- **server: Sync new Loops organization properties**
- **server: Remove unused Loops event**
- **server: Remove Loops event for issue badging**
- **server: Remove legacy Loops properties**
- **server: Send product created event to Loops**
- **server: Send user PAT created event to Loops**
- **server: Send user enabled storefront event to Loops**
- **server: Rename Loops product creation handler**
- **server: Rename Loops organization membership added handler**
- **server: Refactor to streamline Loops service**

Updated Loops events & properties

---

server/polar/account/service.py
server/polar/integrations/github/endpoints.py
server/polar/integrations/google/endpoints.py
server/polar/integrations/loops/service.py
server/polar/magic_link/endpoints.py
server/polar/models/user.py
server/polar/personal_access_token/service.py
server/polar/user_organization/service.py

- **server: Ensure Loops events are only stored for creators**
- **server: Loops send account creation event vs. update**

Loops: Creator contacts only

---

server/polar/integrations/github/endpoints.py
server/polar/integrations/loops/client.py
server/polar/integrations/loops/service.py
server/polar/issue/endpoints.py
server/polar/organization/service.py

- **server: Capture GitHub organization install in Loops**
- **server: Capture GitHub issue badge event in Loops**
- **server: Capture donations enabled in Loops**

Loops: Capture creator funding activation

---

clients/apps/web/src/app/docs/guides/(mdx)/GuideCard.tsx
clients/apps/web/src/app/docs/guides/(mdx)/express/page.mdx
clients/apps/web/src/app/docs/guides/(mdx)/nextjs/page.mdx
clients/apps/web/src/app/docs/guides/(mdx)/page.mdx
clients/apps/web/src/components/Documentation/Navigation.tsx

clients/guides: add express guide

---

clients/apps/web/src/components/Landing/Hero/Hero.tsx

- **clients: Updated hero copy**
- **clients: Signup for free CTA**

website: Updated hero copy

---

clients/apps/web/src/components/Landing/Hero/Hero.tsx

- **clients: Even shorter hero copy**

website: Even shorter copy

---

clients/apps/web/src/components/Accounts/AccountSetup.tsx

chore: open dashboard in a new tab

---

server/polar/order/service.py
server/tests/order/test_service.py

server/order: try to create balance only if amount_paid > 0

---

clients/apps/web/src/components/Auth/GetStartedButton.tsx
clients/apps/web/src/components/Landing/Hero/Hero.tsx

clients: Support keyboard submission in hero signup

---

README.md

This PR fixes a typo in the README and improves the sentence for clarity.

readme: fix typo + improve clarity

---

clients/apps/web/src/components/Products/CreateProductPage.tsx
clients/apps/web/src/components/Products/EditProductPage.tsx

Getting customers with more than the handful of benefits we've seen
historically. This is a quick - initial - fix to ensure they can manage
products properly.
True pagination support in our UI is needed to offer a better & scalable
solution.

fix: Increase benefit limit in product management

---

server/polar/models/transaction.py
server/polar/transaction/service/payout.py
server/tests/transaction/service/test_payout.py

server/transaction: handle refunded transactions that have been paid out during payout

---

clients/apps/web/src/components/Checkout/CheckoutCard.tsx
clients/apps/web/src/components/Products/BenefitList.tsx
clients/apps/web/src/components/Subscriptions/SubscriptionTierCard.tsx

clients: Toggle benefits in case more than 5

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/custom-fields/ClientPage.tsx
clients/apps/web/src/components/Checkout/Checkout.tsx
clients/apps/web/src/components/Checkout/CheckoutForm.tsx
clients/apps/web/src/components/Layout/Section.tsx
clients/apps/web/src/components/Products/ProductForm/ProductCustomFieldSection.tsx

- Some small polish to Checkout experience
- Add manage custom fields link on product creation/edit

clients/checkout: polish checkout

---

clients/apps/web/src/components/Benefit/CreateBenefitModalContent.tsx
clients/apps/web/src/components/Benefit/Downloadables/BenefitForm.tsx
clients/apps/web/src/components/Benefit/UpdateBenefitModalContent.tsx
server/polar/benefit/schemas.py

Improve file downloads benefit validation

---

server/polar/subscription/service.py

server/subscription: send notification to creators only on truly active subscription

---

server/polar/checkout/service.py
server/polar/checkout_link/service.py

server/checkout: handle gracefully blocked organizations

---

server/polar/webhook/tasks.py

server/webhook: catch SSLError when trying to deliver webhook

---

clients/apps/web/src/components/Settings/AccessTokensSettings.tsx

Need to generate our SDK to remove them properly. However, it introduces
a few different changes that are a bit more involed. Doing a quick fix
for now.

clients: Quick fix to remove articles from PAT scope selection

---

clients/apps/web/src/app/(main)/docs/developers/guides/nextjs/page.mdx

Just a small fix in nextjs docs guide

Nextjs docs guide small syntax fix

---

clients/apps/web/src/components/Settings/AccessTokensSettings.tsx

clients: Fix PAT form and move into InlineModal

---

DEVELOPMENT.md
README.md
clients/README.md
clients/apps/web/src/app/(main)/docs/(mdx)/page.mdx
server/README.md

This PR improves grammar + updates the docs.

docs: improve grammar + update docs

---

server/polar/user/service/user.py
server/polar/user/tasks.py
server/tests/fixtures/database.py
server/tests/user/service/test_service.py

server/user: link existing customers by email on signup

---

clients/apps/web/src/components/Discounts/DiscountForm.tsx
server/polar/discount/service.py
server/tests/discount/test_service.py

Discounts: Case insensitive

---

server/polar/integrations/stripe/service.py

server/integrations/stripe: don't try to recreate tax id on customer if it already exists

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx

clients/web: validate minimum price when creating product

---

clients/apps/web/src/app/(main)/(landing)/(mdx)/blog/(header)/upsell-private-github-repositories/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/benefits/ads/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/benefits/discord/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/benefits/file-downloads/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/benefits/github-repositories/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/benefits/license-keys/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/checkout/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/finance/accounts/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/github/embeds/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/github/funding-yaml/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/products/create/page.mdx
clients/apps/web/src/app/(main)/docs/(mdx)/products/paritydeals/page.mdx
clients/apps/web/src/components/Settings/Badge/index.tsx

This PR fixes typos and grammatical errors in the docs.

docs: Fix typo

---

server/polar/customer_portal/service/customer_session.py
server/polar/email/sender.py
server/polar/email/tasks.py
server/polar/email_update/service.py
server/polar/magic_link/service.py
server/polar/notifications/tasks/email.py
server/polar/oauth2/service/oauth2_client.py
server/polar/oauth2/service/oauth2_token.py
server/polar/order/service.py
server/polar/personal_access_token/service.py
server/polar/subscription/service.py
server/polar/tasks.py
server/pyproject.toml
server/tests/fixtures/__init__.py
server/tests/fixtures/email.py
server/tests/magic_link/test_service.py
server/tests/oauth2/service/test_oauth2_client.py
server/tests/oauth2/service/test_oauth2_token.py
server/tests/order/test_service.py
server/tests/personal_access_token/test_service.py
server/tests/subscription/test_service.py
server/uv.lock

Revamp email sending to avoid block the worker

---

clients/apps/web/src/components/Checkout/CheckoutForm.tsx

- **clients: Reset discount state once input is emptied**
- **clients: Prevent form submission on applying discount**
- **clients: Improve UX for discounts apply/reset**

checkout: Improve discount form

---

server/tests/magic_link/test_service.py
server/tests/magic_link/testdata/magic_link.html
server/tests/magic_link/testdata/magic_link_return_to.html
server/tests/notifications/test_email.py
server/tests/notifications/testdata/test_MaintainerCreateAccountNotificationPayload.html
server/tests/notifications/testdata/test_MaintainerNewPaidSubscriptionNotification.html
server/tests/notifications/testdata/test_MaintainerNewProductSaleNotification.html
server/tests/notifications/testdata/test_MaintainerPledgeConfirmationPendingdNotification_no_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgeConfirmationPendingdNotification_with_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_anonymous.html
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_no_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_pay_on_completion.html
server/tests/notifications/testdata/test_MaintainerPledgeCreatedNotification_with_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgePaidNotification.html
server/tests/notifications/testdata/test_MaintainerPledgePendingdNotification_no_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgePendingdNotification_with_stripe.html
server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification.html
server/tests/notifications/testdata/test_MaintainerPledgedIssueConfirmationPendingNotification_with_account.html
server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification.html
server/tests/notifications/testdata/test_MaintainerPledgedIssuePendingNotification_with_account.html
server/tests/notifications/testdata/test_PledgerPledgePendingNotification.html
server/tests/notifications/testdata/test_PledgerPledgePendingNotification_pay_on_completion.html
server/tests/notifications/testdata/test_RewardPaidNotification.html
server/tests/notifications/testdata/test_TeamAdminMemberPledgedNotification.html

- **chore(tests): Fix hardcoded year in email test data**
- **chore(tests): Fix hardcoded year in magic link test data**

Fix hardcoded year in email test data

---

server/polar/checkout/service.py

Fixes #4741
- **server: Skip checkout tax calculation for free orders**
- **chore(server): Format checkout service**

checkout: Skip tax calculation for free orders

---

server/polar/customer/service.py
server/polar/customer_session/schemas.py
server/polar/customer_session/service.py
server/polar/models/customer_session.py
server/tests/customer_session/test_endpoints.py

server/customer_session: add customer portal URL to API output

---

clients/apps/web/src/app/(main)/[organization]/portal/(topbar)/authenticate/ClientPage.tsx

clients/web: tweak OTP input for mobile

---

clients/packages/polarkit/package.json
clients/pnpm-lock.yaml

clients/packages/polarkit: upgrade @radix-ui/react-select

---

clients/apps/web/src/components/Products/ProductSelect.tsx
clients/apps/web/src/hooks/queries/products.ts
clients/packages/sdk/src/client/apis/ProductsApi.ts
clients/packages/sdk/src/client/apis/SubscriptionsApi.ts
server/polar/product/endpoints.py
server/polar/product/service/product.py

Handle paginated selections in ProductSelect

---

server/polar/integrations/plain/service.py

server/integrations/plain: fix organization card JSON output

---

server/polar/subscription/service.py
server/tests/subscription/test_endpoints.py

server/subscription: prevent pricing update on canceled subscriptions

---

server/polar/auth/dependencies.py

We found out that users were troubled by the fact that their own customer portal was showing up instead of the one tied to the customer session token that was present in the URL.
With this change, if the backend finds a valid customer session token, it uses it instead of the web cookie session, correctly showing the customer we're trying to see instead of the authenticated user.

server/auth: prioritize customer session over web session

---

clients/apps/web/src/components/Checkout/CheckoutCard.tsx

- Added a label: `Name a fair price`
- In case of a minimum: Show it in context with the label
- Allow changing the PWYW price directly vs. via an explicit `Change` -> `Submit` flow. However, do so via a debounce (600ms) to keep checkout updates & tax calculations to a minimum  
Fixes #4829

clients: Improved PWYW copy & input form

---

server/polar/checkout/service.py

Not very nice, but really helps when we need to rerun an event when something has gone wrong

server/checkout: remove idempotency keys when handling Stripe success

---

server/.vscode/settings.json
server/polar/checkout/service.py
server/tests/checkout/test_service.py

server/checkout: prevent redeeming recurring discount on one-time pricing

---

clients/apps/web/src/components/Vision/Navigation.tsx
clients/apps/web/src/components/Vision/sections/DNASection.tsx
clients/apps/web/src/components/Vision/sections/EntitlementsSection.tsx
clients/apps/web/src/components/Vision/sections/IndexSection.tsx
clients/apps/web/src/components/Vision/sections/InvestorsSection.tsx
clients/apps/web/src/components/Vision/sections/OpenSourceSection.tsx
clients/apps/web/src/components/Vision/sections/TeamSection.tsx
clients/apps/web/src/components/Vision/sections/UsageBasedSection.tsx

- **improve vision**
- **update vision**
- **adjust entitlement**
- **vision: Copy updates**

Vision copy changes

---

server/polar/refund/schemas.py
server/polar/refund/service.py
server/tests/refunds/test_service.py

- **server: Use getattr for refund destination details**
- **server: Raise RefundedAlready vs. Stripe 500**

fix: Better refund error handling

---

clients/apps/web/src/components/Checkout/CheckoutLinkForm.tsx

- **clients: Fix Checkout Link state issue with discounts**
- **clients: Fix Checkout Link state issue with success_url**

fix: Checkout Link state issues

---

server/polar/models/discount.py

We're controlling that on our side anyway

server/discount: don't pass `redeem_by` and `max_redemptions` param to Stripe

---

server/polar/checkout/service.py
server/polar/config.py

server/checkout: add statement descriptor suffix

---

server/polar/checkout/endpoints.py

Important to be complete so the official SDK can pick them up correctly

server/checkout: improve schema of checkout errors

---

clients/apps/web/src/app/(main)/[organization]/[repo]/ClientPage.tsx
clients/apps/web/src/app/(main)/[organization]/[repo]/issues/(create)/ClientPage.tsx
clients/apps/web/src/app/(main)/[organization]/[repo]/issues/(create)/page.tsx
clients/apps/web/src/app/(main)/[organization]/[repo]/issues/status/page.tsx
clients/apps/web/src/app/(main)/[organization]/[repo]/layout.tsx
clients/apps/web/src/app/(main)/[organization]/[repo]/page.tsx

clients/issues: fix 404 on issue pages

---

clients/apps/web/src/app/(main)/[organization]/(header)/issues/page.tsx
clients/apps/web/src/app/(main)/[organization]/(header)/page.tsx

Try to avoid DB hiccups because of that large query.

clients/web: raise funding API cache duration

---

server/migrations/versions/2025-02-10-1545_remove_discountredemption_saved_for_.py
server/polar/checkout/service.py
server/polar/discount/repository.py
server/polar/discount/service.py
server/tests/checkout/test_service.py

server/checkout: delete DiscountRedemption if the Checkout session goes to `failed` status

---

clients/apps/web/src/app/(main)/(topbar)/(backer)/settings/page.tsx

clients/web: hide PAT section in user settings if no organization created

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/benefits/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/products/benefits/ClientPage.tsx

clients/web: add ability to copy benefit id

---

clients/apps/web/package.json
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/meters/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/products/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/products/checkout-links/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/products/checkout-links/page.tsx
clients/apps/web/src/components/Checkout/Checkout.tsx
clients/apps/web/src/components/Checkout/CheckoutCard.tsx
clients/apps/web/src/components/Checkout/CheckoutLinkContextView.tsx
clients/apps/web/src/components/Checkout/CheckoutLinkForm.tsx
clients/apps/web/src/components/Checkout/CheckoutLinkManagementModal.tsx
clients/apps/web/src/components/Customization/utils.ts
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Products/CreateProductPage.tsx
clients/apps/web/src/components/Products/ProductSelect.tsx
clients/apps/web/src/hooks/queries/checkout_links.ts
clients/examples/checkout-components/package.json
clients/packages/checkout/package.json
clients/packages/checkout/src/components/AmountLabel.tsx
clients/packages/checkout/src/components/CheckoutForm.tsx
clients/packages/checkout/src/components/CheckoutPricing.tsx
clients/packages/checkout/src/components/CheckoutProductSwitcher.tsx
clients/packages/checkout/src/components/ProductPriceLabel.tsx
clients/packages/checkout/src/components/index.ts
clients/packages/checkout/src/utils/product.ts
clients/packages/client/src/v1.ts
clients/packages/ui/src/components/atoms/MoneyInput.tsx
clients/pnpm-lock.yaml

Merge this after:
* Having regenerated the JS SDK
* Bumped it here in package.json

Client-side handling of multiple checkout products

---

docs/docs.json

This reverts commit 49f8594448320862018ec2f96e9c93254d3f147d.

Revert "docs: change random setting in hope it'll deploy something"

---

clients/packages/checkout/src/components/CheckoutPricing.tsx

Thanks to feedback from Ilias Ism (MagicSpace) https://x.com/illyism/status/1892233958663819398
Unfortunately, I have to admit it got lost in my notes from the call 🤦🏼‍♂️ Thanks for the nudge today Ilias 🙏🏼

checkout: Show discounted product price in card

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/benefits/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/customers/ClientPage.tsx
clients/apps/web/src/components/Checkout/Checkout.tsx
clients/apps/web/src/components/Checkout/CheckoutCard.tsx
clients/apps/web/src/components/Layout/Dashboard/DashboardSidebar.tsx
clients/apps/web/src/components/Layout/DashboardLayout.tsx
clients/apps/web/src/components/Metrics/DateRangePicker.tsx
clients/apps/web/src/components/Notifications/NotificationsPopover.tsx
clients/apps/web/src/components/Products/ProductForm/ProductCustomFieldSection.tsx
clients/apps/web/src/components/Products/ProductSelect.tsx
clients/apps/web/src/components/Settings/AuthenticationSettings.tsx
clients/apps/web/src/components/Settings/OrganizationAccessTokensSettings.tsx
clients/apps/web/src/utils/metrics.ts
clients/packages/checkout/src/components/CheckoutForm.tsx
clients/packages/ui/src/components/atoms/Button.tsx
clients/packages/ui/src/components/atoms/DateTimePicker.tsx
clients/packages/ui/src/components/atoms/Input.tsx
clients/packages/ui/src/components/atoms/Select.tsx
clients/packages/ui/src/components/atoms/Tabs.tsx

- New Button roundness
- New Input roundness
- Updated Sidebar

clients: new dashboard aesthetics

---

server/polar/subscription/service.py

server/subscription: make sure to send confirmation email when subscription is immediately active

---

clients/apps/web/src/components/Accounts/AccountCreateModal.tsx

KYC preparation. Removing the OC choice completely and migrating the form to a React Hook Form.

Refactor account setup

---

clients/apps/web/src/components/Transactions/TransactionsList.tsx

finance: fix product link in finance

---

sdk/overlays/security.yml

sdk: fix security overlay to state unauthenticated endpoint

---

server/polar/web_backoffice/components/_base.py
server/polar/web_backoffice/components/_layout.py
server/polar/web_backoffice/middlewares.py
server/polar/web_backoffice/organizations/forms.py
server/polar/web_backoffice/package.json
server/polar/web_backoffice/pnpm-lock.yaml
server/polar/web_backoffice/scripts.mjs

- server/web_backoffice: add a bit of HTMX 😬
- server/web_backoffice: remove no cache header

server/web_backoffice: add a bit of HTMX 😬

---

server/polar_backoffice/screens/accounts/list.py

- **backoffice: List only accounts for review**

backoffice: Review improvements

---

server/polar/integrations/stripe/service.py

- server: fix account review link in Plain card

server: fix account review link in Plain card

---

clients/apps/web/src/components/Checkout/CheckoutProductInfo.tsx

checkout: add image slideshow component to CHeckout

---

render.yaml
server/polar/config.py
server/polar/customer_portal/service/downloadables.py

- server: fix generate_external_url

server: fix generate_external_url

---

render.yaml
server/polar/checkout/schemas.py
server/polar/config.py
server/polar/customer_portal/service/downloadables.py

- server/checkout: add customer_external_id to Checkout schema
- server: fix generate_external_url

server/checkout: add customer_external_id to Checkout schema

---

server/polar/web_backoffice/README.md

- server/web_backoffice: add README

server/web_backoffice: add README

---

server/polar/transaction/service/processor_fee.py

- server/transaction: add another Stripe fee!

server/transaction: add another Stripe fee!

---

server/uv.lock

server: bump dependencies

---

clients/packages/checkout/package.json
clients/packages/ui/package.json

add repo details to package.json to make it's clear where to look for the package source

add repository field to package.json for checkout and ui packages

---

server/polar/integrations/plain/service.py

- server/integrations/plain: add button to backoffice in Organization card

server/integrations/plain: add button to backoffice in Organization card

---

clients/apps/web/src/app/(main)/login/magic-link/authenticate/ClientPage.tsx
clients/apps/web/src/app/(main)/login/magic-link/authenticate/page.tsx

- clients/web: disable login button on magic link page

clients/web: disable login button on magic link page

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
server/polar/product/schemas.py

- **server: Validate PWYW price is within range**
- **clients: Validate PWYW pricing form**

fix: Better error handling on invalid PWYW pricing

---

server/polar/subscription/service.py
server/tests/subscription/test_service.py

- server/subscription: disable automatic_tax for free products

server/subscription: disable automatic_tax for free products

---

clients/apps/web/src/components/Refunds/RefundModal.tsx

Prevent accidental double-clicks on Refund button

Prevent accidental double-clicks on Refund button

---

docs/features/integrations/zapier.mdx
docs/snippets/zapier-embed.mdx

docs: fix Zapier embed

---

server/polar/checkout/service.py

- server/checkout: fix eager loading on CheckoutPriceCreate

server/checkout: fix eager loading on CheckoutPriceCreate

---

clients/packages/client/src/v1.ts
server/polar/customer_portal/schemas/order.py
server/polar/order/schemas.py

- server/order: fix definition of deprecated Order.amount field

server/order: fix definition of deprecated Order.amount field

---

server/polar/order/service.py
server/tests/order/test_service.py

- server/order: disable automatic tax for free purchases (free *and* fully discounted)

server/order: disable automatic tax for free purchases (free *and* fully discounted)

---

docs/changelog/api.mdx
docs/docs.json
docs/package.json
docs/pnpm-lock.yaml

docs: add API changelog

---

server/polar/order/service.py

- server/order: add missing checkout event on order created from Stripe

server/order: add missing checkout event on order created from Stripe

---

server/tests/order/test_service.py
server/tests/subscription/test_service.py

- server: add tests for checkout events after subscription and order

server: add tests for checkout events after subscription and order

---

server/polar/checkout/service.py
server/polar/order/service.py
server/polar/subscription/repository.py
server/tests/order/test_service.py

- server/order: load subscription customer through eager load
- server/order: fix custom pricing not correctly handled when creating order
- server/checkout: fix eager loading error

server/order: load subscription customer through eager load

---

server/polar/refund/schemas.py

- server/refund: validate minimum refund amount input payload

server/refund: validate minimum refund amount input payload

---

server/polar/subscription/service.py

- server/subscription: prevent concurrent updates to subscriptions with a lock

server/subscription: prevent concurrent updates to subscriptions with a lock

---

server/scripts/remove_badges.py

- server/scripts: implement script to remove github badges

server/scripts: implement script to remove github badges

---

server/scripts/remove_badges.py

- server/scripts: fix remove github badges

server/scripts: fix remove github badges

---

server/migrations/versions/2025-03-21-1019_remove_archived_products_from_checkout_.py
server/polar/checkout/service.py
server/polar/checkout_link/repository.py
server/polar/exceptions.py
server/polar/product/service/product.py
server/scripts/remove_badges.py
server/tests/checkout/test_service.py
server/tests/product/service/test_product.py

- server: create migration to remove archived products from checkout links
- server/product: remove product from related checkout links when archiving
- server/checkout_link: prevent checkout link creation with archived products
- server/scripts: fix typing issue

server: create migration to remove archived products from checkout links

---

server/polar/checkout_link/repository.py
server/polar/kit/repository/base.py
server/polar/product/service/product.py
server/tests/product/service/test_product.py

- server/product: ensure to soft delete checkout link if no product anymore after archiving it

server/product: ensure to soft delete checkout link if no product anymore after archiving it

---

clients/apps/web/src/middleware.ts

- clients/web: add middleware logs

clients/web: add middleware logs

---

server/polar/benefit/benefits/discord.py
server/polar/benefit/tasks.py

- server/benefit/discord: fix log message
- server/benefits: raise number of retries for grant/revoke benefits

server/benefit/discord: fix log message

---

server/polar/billing_entry/service.py
server/polar/models/product_price.py
server/polar/product/schemas.py

- server/product: add meter schema to ProductPriceMeteredUnit

server/product: add meter schema to ProductPriceMeteredUnit

---

server/polar/product/schemas.py

- server/product: add currency to ProductPriceMeteredUnit schema

server/product: add currency to ProductPriceMeteredUnit schema

---

server/polar/checkout/schemas.py
server/polar/checkout/service.py
server/polar/models/checkout.py
server/tests/checkout/test_service.py
server/tests/order/test_service.py

- server/checkout: fix amount properties for consistency with Order

server/checkout: fix amount properties for consistency with Order

---

docs/features/checkout/session.mdx

Fixed typo in session.mdx

---

server/polar/product/service/product.py

- server/product: fix eager loading when updating product

server/product: fix eager loading when updating product

---

server/polar/product/service/product.py

- server/product: set product when adding new price to product

server/product: set product when adding new price to product

---

server/polar/models/product.py

- server/product: enable cascade all on Product.all_prices

server/product: enable cascade all on Product.all_prices

---

clients/apps/web/src/middleware.ts

- clients/web: fix customer portal settings not accessible

clients/web: fix customer portal settings not accessible

---

server/polar/models/product.py
server/polar/product/service/product.py
server/tests/product/service/test_product.py

- server/product: fix product update provoking DB integrity errors

server/product: fix product update provoking DB integrity errors

---

server/polar/redis.py
server/polar/worker.py

- server: ensure to force close Redis connection pool on cleanups

server: ensure to force close Redis connection pool on cleanups

---

server/polar/benefit/tasks.py
server/tests/benefit/test_tasks.py

- server/benefit: allow soft deleted benefit when handling benefit.delete task

server/benefit: allow soft deleted benefit when handling benefit.delete task

---

server/polar/transaction/service/payout.py

- server/transaction/payout: handle case where transferred amount conversion is zero

server/transaction/payout: handle case where transferred amount conversion is zero

---

server/migrations/versions/2025-04-02-1118_normalize_billing_address_states.py
server/polar/kit/address.py
server/tests/checkout/test_endpoints.py
server/tests/kit/test_address.py
server/tests/order/test_service.py

- server: add migration to normalize existing states in DB
- server: add proper validation for US and CA states

server: add migration to normalize existing states in DB

---

.zed/settings.json
server/polar/transaction/service/payout.py

- server/payout: greatly increase payout lock lifetime
- dx: fix Zed settings

server/payout: greatly increase payout lock lifetime

---

clients/packages/ui/src/components/atoms/Avatar.tsx

dont apply gradient to avatar if url is passed

---

server/polar/transaction/service/refund.py

- server/transaction/refund: don't set payment transaction on refund reversal transaction

server/transaction/refund: don't set payment transaction on refund reversal transaction

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx

- clients/web: add Metered price type behind feature flag

clients/web: add Metered price type behind feature flag

---

clients/apps/web/src/hooks/magicLink.ts

API request did not pass the attribution for the right key.

clients: Fix Magic Link attribution

---

server/polar/benefit/grant/service.py
server/polar/benefit/service.py
server/polar/checkout/service.py
server/polar/customer/service.py
server/polar/models/benefit_grant.py
server/polar/order/service.py
server/polar/organization/service.py
server/polar/pledge/service.py
server/polar/product/service/product.py
server/polar/refund/service.py
server/polar/subscription/service.py
server/polar/webhook/service.py
server/polar/webhook/webhooks.py
server/tests/customer/test_service.py
server/tests/webhooks/test_webhooks.py

- server: protect against None organizations when trying to send webhooks
- server/webhooks: refactor and revamp typing of send function

server: protect against None organizations when trying to send webhooks

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx

- clients/web: hide Add Price button when usaged based billing flag is disabled

clients/web: hide Add Price button when usaged based billing flag is disabled

---

clients/apps/web/package.json
clients/apps/web/src/components/CustomerPortal/CurrentPeriodOverview.tsx
clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
clients/apps/web/src/components/Products/ProductForm/UnitAmountInput.tsx
clients/apps/web/src/components/Products/utils.ts
clients/examples/checkout-components/package.json
clients/packages/checkout/package.json
clients/packages/checkout/src/components/MeteredPriceLabel.tsx
clients/packages/checkout/src/utils/money.ts
clients/packages/client/src/v1.ts
clients/pnpm-lock.yaml

- clients/web: add support to decimal unit pricing to dashboard and checkout

clients/web: add support to decimal unit pricing to dashboard and checkout

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
clients/apps/web/src/utils/product.ts
server/polar/product/schemas.py
server/polar/product/service/product.py
server/tests/product/service/test_product.py

- clients/web: prevent creation of metered prices on one-time products
- server/product: prevent creation of metered price on one-time products

clients/web: prevent creation of metered prices on one-time products

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/events/ClientPage.tsx
clients/apps/web/src/hooks/queries/events.ts
clients/packages/client/src/v1.ts
server/polar/event/endpoints.py
server/polar/event/repository.py
server/polar/event/schemas.py
server/polar/event/service.py
server/polar/event/sorting.py
server/tests/event/test_service.py

- clients/web: use infinite loading for events page
- server/event: tweak event names endpoint

clients/web: use infinite loading for events page

---

clients/apps/web/src/app/(main)/[organization]/portal/page.tsx
clients/apps/web/src/app/(main)/[organization]/portal/usage/ClientPage.tsx
clients/apps/web/src/app/(main)/[organization]/portal/usage/page.tsx
clients/apps/web/src/components/CustomerPortal/CustomerUsage.tsx
clients/apps/web/src/hooks/queries/customerPortal.ts
clients/packages/client/src/v1.ts
server/polar/customer_portal/endpoints/__init__.py
server/polar/customer_portal/endpoints/customer_meter.py
server/polar/customer_portal/repository/customer_meter.py
server/polar/customer_portal/schemas/customer_meter.py
server/polar/customer_portal/service/customer_meter.py
server/polar/customer_portal/sorting/customer_meter.py
server/polar/meter/schemas.py

- clients/web: implement meters in customer portal
- server/customer_portal: add endpoint to query meters

clients/web: implement meters in customer portal

---

clients/packages/client/src/v1.ts
server/polar/checkout/endpoints.py
server/polar/checkout/repository.py
server/polar/checkout/service.py
server/polar/models/checkout.py
server/tests/checkout/test_endpoints.py

- server/checkout: add a specific API error when retrieving expired checkout

clients/packages/client: update OpenAPI client

---

clients/apps/web/package.json
clients/apps/web/src/app/checkout/[clientSecret]/confirmation/page.tsx
clients/apps/web/src/app/checkout/[clientSecret]/page.tsx
clients/examples/checkout-components/package.json
clients/packages/checkout/package.json
clients/packages/checkout/src/providers/CheckoutProvider.tsx
clients/pnpm-lock.yaml

- clients/web: handle ExpiredCheckoutError

clients/web: handle ExpiredCheckoutError

---

server/Dockerfile

server: fix Dockerfile

---

.github/workflows/deploy_server.sh

- ops: remove GitHub workers from deploy script

ops: remove GitHub workers from deploy script

---

server/migrations/versions/2025-04-14-1430_remove_outdated_scope_and_events.py

- server: remove outdated webhook events from endpoints

server: remove outdated webhook events from endpoints

---

clients/packages/client/src/v1.ts
server/polar/event/repository.py
server/polar/event/schemas.py
server/polar/event/service.py
server/tests/event/test_service.py

- server/event: add source to event names endpoint

server/event: add source to event names endpoint

---

server/polar/subscription/service.py

- server/subscription: allow soft deleted org when sending customer email

server/subscription: allow soft deleted org when sending customer email

---

server/polar/checkout/service.py
server/polar/models/checkout.py
server/polar/product/guard.py

- server/checkout: ask for billing info on a Free product with metered prices

server/checkout: ask for billing info on a Free product with metered prices

---

server/polar/account/tasks.py
server/polar/benefit/tasks.py
server/polar/checkout/tasks.py
server/polar/customer/tasks.py
server/polar/customer_meter/tasks.py
server/polar/email/tasks.py
server/polar/event/tasks.py
server/polar/eventstream/tasks.py
server/polar/integrations/loops/tasks.py
server/polar/integrations/stripe/tasks.py
server/polar/meter/tasks.py
server/polar/notifications/tasks/email.py
server/polar/notifications/tasks/push.py
server/polar/order/tasks.py
server/polar/organization/tasks.py
server/polar/organization_access_token/tasks.py
server/polar/personal_access_token/tasks.py
server/polar/subscription/tasks.py
server/polar/transaction/tasks.py
server/polar/user/tasks.py
server/polar/webhook/tasks.py
server/polar/worker.py
server/tests/account/test_tasks.py
server/tests/benefit/test_tasks.py
server/tests/fixtures/worker.py
server/tests/organization/test_tasks.py
server/tests/subscription/test_tasks.py
server/tests/webhooks/test_webhooks.py

- server: remove unneeded polar worker context

server: remove unneeded polar worker context

---

server/polar/checkout/service.py

- server/checkout: fix eager load error when creating checkout with price and discount

server/checkout: fix eager load error when creating checkout with price and discount

---

server/migrations/versions/2025-04-16-0927_rename_meter_credited_system_event.py
server/polar/event/system.py
server/polar/webhook/webhooks.py

- server/event: rename meter credited system event
- server/webhook: add missing webhook type

server/event: rename meter credited system event

---

clients/apps/web/src/app/(main)/[organization]/portal/Navigation.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/usage-billing/events/ClientPage.tsx
clients/apps/web/src/components/Benefit/BenefitForm.tsx
clients/apps/web/src/components/Customer/CustomerPage.tsx
clients/apps/web/src/components/Dashboard/navigation.tsx
clients/apps/web/src/components/Products/ProductBenefitsForm.tsx
clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
clients/apps/web/src/components/Settings/FeatureSettings.tsx
clients/apps/web/src/utils/testdata.ts
clients/packages/client/src/v1.ts
server/polar/benefit/service.py
server/polar/event/endpoints.py
server/polar/organization/schemas.py
server/polar/product/service/product.py

- clients/web: use organization setting to enable usage based billing features
- clients/web: add usage based billing setting toggle
- server/organization: add a feature setting for usage based billing

Implement organization setting to enable usage-based billing features

---

docs/features/usage-based-billing/billing.mdx
docs/features/usage-based-billing/credits.mdx
docs/features/usage-based-billing/event-ingestion.mdx
docs/features/usage-based-billing/meters.mdx

- docs: tweak usage based billing sections

docs: tweak usage based billing sections

---

docs/features/usage-based-billing/ingestion-strategies.mdx

- docs: add Python ingestion strategies

docs: add Python ingestion strategies

---

server/polar/transaction/service/refund.py
server/tests/transaction/service/test_refund.py

- server/transaction: fix refund_reversal balances linking

server/transaction: fix refund_reversal balances linking

---

server/polar/benefit/strategies/meter_credit/service.py

- server/benefit/strategies/meter_credit: don't uncredit on revoke if never granted

server/benefit/strategies/meter_credit: don't uncredit on revoke if never granted

---

server/polar/benefit/strategies/github_repository/service.py
server/polar/integrations/github/client.py
server/polar/integrations/github_repository_benefit/service.py

- server/integrations/github: tweak client and disable cache

server/integrations/github: tweak client and disable cache

---

server/polar/meter/aggregation.py
server/tests/fixtures/random_objects.py
server/tests/meter/test_aggregation.py

- server/meter: support aggregation on floating property and improve resilience on wrong types

server/meter: support aggregation on floating property and improve resilience on wrong types

---

docs/api-reference/customer-meters/get.mdx
docs/api-reference/customer-meters/list.mdx
docs/docs.json
docs/features/usage-based-billing/credits.mdx
docs/features/usage-based-billing/event-ingestion.mdx
docs/features/usage-based-billing/introduction.mdx
docs/features/usage-based-billing/meters.mdx
docs/integrate/customer-state.mdx
docs/package.json
docs/pnpm-lock.yaml
docs/snippets/usage/events.mdx
docs/snippets/usage/meter-credits.mdx
docs/snippets/usage/metered-price.mdx
docs/snippets/usage/meters.mdx

- docs: add more details to usage based billing

docs: add more details to usage based billing

---

server/polar/kit/tax.py

- server/kit/tax: allow to process list as valid tax value

server/kit/tax: allow to process list as valid tax value

---

server/polar/kit/repository/base.py

- server/kit/repository: apply unique on get_one_or_none

server/kit/repository: apply unique on get_one_or_none

---

server/polar/meter/filter.py
server/tests/meter/test_filter.py

- server/meter: handle gracefully like/not_like operator with non-string values

server/meter: handle gracefully like/not_like operator with non-string values

---

server/polar/benefit/tasks.py

- server/benefit: fix eager loading on benefit_delete_grant

server/benefit: fix eager loading on benefit_delete_grant

---

server/polar/transaction/service/payment.py

- server/transaction: don't store tax state if not US or CA

server/transaction: don't store tax state if not US or CA

---

server/polar/integrations/stripe/service.py
server/polar/order/service.py

- server/integrations/stripe: set statement descriptor on subscription renewals

server/integrations/stripe: set statement descriptor on subscription renewals

---

render.yaml

- ops: tweak Dramatiq run configuration

ops: tweak Dramatiq run configuration

---

render.yaml

- ops: fix Dramatiq prometheus port

ops: fix Dramatiq prometheus port

---

server/polar/worker.py

- server/worker: add Logfire middleware

server/worker: add Logfire middleware

---

.github/workflows/build_server.yaml
.github/workflows/deploy_server.sh

- ops: reestablish server deploy now that Dramatiq workers are properly up

ops: reestablish server deploy now that Dramatiq workers are properly up

---

render.yaml
server/polar/worker.py
server/pyproject.toml
server/uv.lock

- server/worker: tweak Dramatiq logfire instrumentation
- server/worker: fix scheduler not working

server/worker: tweak Dramatiq logfire instrumentation

---

render.yaml

- ops: remove old worker from Render blueprint

ops: remove old worker from Render blueprint

---

clients/apps/web/src/app/(main)/[organization]/portal/authenticate/ClientPage.tsx

- clients/web: fix customer portal OTP not accepting lowercase letters

clients/web: fix customer portal OTP not accepting lowercase letters

---

clients/packages/ui/src/components/atoms/CountryPicker.tsx
clients/packages/ui/src/components/atoms/CountryStatePicker.tsx

- clients/packages/ui: fix country and state selector bug when used with browser translation

clients/packages/ui: fix country and state selector bug when used with browser translation

---

server/polar/checkout/service.py
server/polar/customer_portal/service/customer.py
server/polar/kit/tax.py
server/tests/checkout/test_tax.py

- server/checkout: fix CA GST HST tax ID validation

server/checkout: fix CA GST HST tax ID validation

---

clients/packages/checkout/src/components/CheckoutForm.tsx

- clients/web: use an Apply button for tax ID to avoid infinite validation loop

clients/web: use an Apply button for tax ID to avoid infinite validation loop

---

server/polar/kit/tax.py
server/tests/checkout/test_tax.py

- server/kit/tax: handle CA GST HST validator with spaces in it

server/kit/tax: handle CA GST HST validator with spaces in it

---

server/polar/benefit/strategies/github_repository/service.py

- server/benefit/strategies/github_repository: raise on client error status code

server/benefit/strategies/github_repository: raise on client error status code

---

server/polar/benefit/strategies/meter_credit/service.py
server/polar/event/service.py
server/polar/meter/service.py
server/polar/middlewares.py
server/polar/worker.py
server/tests/event/test_service.py

- server/event: make sure to call ingestion task when creating system events
- server/meter: query events linked to an existing customer when creating billing entries

server/event: make sure to call ingestion task when creating system events

---

server/polar/integrations/stripe/tasks.py
server/polar/transaction/service/dispute.py

- server/transaction: handle dispute in warning_closed state gracefully

server/transaction: handle dispute in warning_closed state gracefully

---

server/polar/integrations/plain/service.py
server/polar/models/user.py
server/polar/user/repository.py
server/polar/user/sorting.py
server/polar/web_backoffice/__init__.py
server/polar/web_backoffice/components/_accordion.py
server/polar/web_backoffice/navigation.py
server/polar/web_backoffice/organizations/endpoints.py
server/polar/web_backoffice/users/endpoints.py

- server/web_backoffice: display organization users
- server/integrations/plain: add link to backoffice on User card
- server/web_backoffice: add users backoffice

server/web_backoffice: display organization users

---

server/polar/user/endpoints.py

- server/user: reintroduce aliases for customer portal endpoints to ensure backward compat

server/user: reintroduce aliases for customer portal endpoints to ensure backward compat

---

clients/apps/web/src/components/Benefit/MeterCredit/BenefitForm.tsx

- clients/web: fix meter credits benefit form not submittable if rollover unchecked

clients/web: fix meter credits benefit form not submittable if rollover unchecked

---

server/polar/metrics/metrics.py

- server/metrics: fix aggregation function for some metrics

server/metrics: fix aggregation function for some metrics

---

clients/packages/checkout/src/components/CheckoutForm.tsx

- clients/packages/checkout: fix double-submit issue when entering a wrong discount code

clients/packages/checkout: fix double-submit issue when entering a wrong discount code

---

server/polar/account/service.py

- server/account: fix relationship eager loading

server/account: fix relationship eager loading

---

server/polar/account/tasks.py

- server/account: fix org eager loading in under_review task

server/account: fix org eager loading in under_review task

---

server/polar/integrations/plain/service.py
server/polar/web_backoffice/organizations/endpoints.py

- server/backoffice: surface organization support email

server/backoffice: surface organization support email

---

clients/apps/web/src/components/Products/ProductSelect.tsx

Fixes #5696 
I have fixed the length of the container below are the ss for mobile view and pc screen.
Mobile View:
[
](url)
Pc View:

feat: Analytics: Filter input length fix

---

clients/apps/web/src/components/Subscriptions/SubscriptionStatus.tsx
server/polar/models/subscription.py
server/tests/subscription/test_endpoints.py

- clients/web: show cancel badge on past due subscriptions
- server/subscription: allow to cancel past due subscriptions

Allow to cancel past due subscriptions

---

clients/apps/web/src/components/Metrics/MetricChart.tsx
clients/apps/web/src/utils/metrics.ts

- clients/web: show full values in metrics chart box

clients/web: show full values in metrics chart box

---

server/polar/payment/service.py

- server/payment: handle payment intent failed for subscription orders

server/payment: handle payment intent failed for subscription orders

---

docs/changelog/recent.mdx

- docs: add changelog for purchasing as business option

docs: add changelog for purchasing as business option

---

docs/features/checkout/embed.mdx

- docs: add advanded embed examples

docs: add advanded embed examples

---

server/polar/kit/tax.py

- server/kit/tax: add not_supported taxability reason

server/kit/tax: add not_supported taxability reason

---

server/polar/subscription/service.py

- server/subscription: use idempotency keys when creating subscriptions

server/subscription: use idempotency keys when creating subscriptions

---

server/scripts/tax_rates_import.py

- server/scripts: fix tax rates import script

server/scripts: fix tax rates import script

---

clients/packages/client/src/v1.ts
server/polar/customer/schemas/state.py

- server/customer: add missing ID on customer state meter schema

server/customer: add missing ID on customer state meter schema

---

server/polar/customer_meter/service.py

server/customer_meter: filter meters on customer's organization when updating balances

---

.zed/settings.json
server/polar/event/repository.py
server/polar/event/service.py
server/polar/kit/metadata.py
server/polar/meter/service.py
server/polar/models/event.py

- server/event: don't eager load customer systematically to improve performance when updating balances
- dx: update Zed settings
- server/customer_meter: tweak customer meter query performance

server/event: don't eager load customer systematically to improve performance when updating balances

---

server/polar/locker.py

- server/locker: add Logfire spans around distributed lock logic

server/locker: add Logfire spans around distributed lock logic

---

clients/packages/checkout/src/components/CheckoutForm.tsx
server/polar/benefit/strategies/github_repository/service.py

- clients/packages/checkout: show address when required even if free order
- server/benefit/strategies/github_repository: use a proper context manager for http client

clients/packages/checkout: show address when required even if free order

---

docs/api-reference/customer-portal/orders/get-invoice.mdx
docs/api-reference/customer-portal/orders/patch.mdx
docs/api-reference/customer-portal/orders/post-invoice.mdx
docs/api-reference/orders/get-invoice.mdx
docs/api-reference/orders/patch.mdx
docs/api-reference/orders/post-invoice.mdx
docs/changelog/api.mdx
docs/docs.json

- docs: add information about invoice generation API
- docs: update OpenAPI schema
- build(deps): bump dawidd6/action-download-artifact from 8 to 10

docs: add information about invoice generation API

---

server/polar/event/repository.py
server/tests/event/test_service.py

- server/event: handle empty ingestion payload gracefully

server/event: handle empty ingestion payload gracefully

---

docs/features/finance/payouts.mdx

docs: fix typos

---

docs/api-reference/rate-limits.mdx
docs/changelog/api.mdx
docs/docs.json
docs/package.json
docs/pnpm-lock.yaml

docs: add API rate limits

---

server/polar/payout/service.py
server/polar/payout/tasks.py

- server/payout: handle gracefully the case where payout is already triggered on processor

server/payout: handle gracefully the case where payout is already triggered on processor

---

server/polar/integrations/stripe/service.py

- server/integrations/stripe: tweak OOB invoice creation for cases where idempotency requests return outdated data

server/integrations/stripe: tweak OOB invoice creation for cases where idempotency requests return outdated data

---

server/polar/billing_entry/service.py
server/polar/customer_meter/service.py
server/polar/event/system.py
server/polar/meter/service.py
server/polar/models/event.py

- server/customer_meter: optimize meter update to handle cases where we have lot of events

server/customer_meter: optimize meter update to handle cases where we have lot of events

---

render.yaml

- ops: reduce number of worker threads

ops: reduce number of worker threads

---

server/polar/billing_entry/service.py
server/polar/event/repository.py

- server/billing_entry: optimize pending usage computation when there are lot of events

server/billing_entry: optimize pending usage computation when there are lot of events

---

server/polar/worker.py

- server/worker: close Logfire span in after_skip_message

server/worker: close Logfire span in after_skip_message

---

server/polar/order/service.py

- server/order: quick fix for tax calculation with multiple rates

server/order: quick fix for tax calculation with multiple rates

---

server/polar/worker.py
server/pyproject.toml

- server/worker: tweak middlewares to try to solve memory leaks

server/worker: tweak middlewares to try to solve memory leaks

---

server/polar/auth/service.py

- server/auth: remove useless query when fetching user session

server/auth: remove useless query when fetching user session

---

server/polar/transaction/service/processor_fee.py

- server/transaction: add Stripe tax fee type

server/transaction: add Stripe tax fee type

---

server/polar/logfire.py
server/run_worker.py

- Revert "server/worker: add Redis instrumentation to Logfire"

Revert "server/worker: add Redis instrumentation to Logfire"

---

server/polar/email/sender.py
server/polar/email/tasks.py
server/polar/subscription/service.py

- server/email: optimize Resend calls by reusing client across sendings

server/email: optimize Resend calls by reusing client across sendings

---

clients/apps/web/src/components/Checkout/CheckoutProductInfo.tsx

Removed skeletons for no product description in checkout

---

server/polar/kit/metadata.py
server/polar/meter/endpoints.py
server/polar/meter/service.py
server/polar/product/endpoints.py
server/polar/product/service.py
server/tests/meter/test_service.py

- server/meter: allow to query quantities with metadata filter

server/meter: allow to query quantities with metadata filter

---

clients/apps/web/src/components/Checkout/CheckoutBenefits.tsx
clients/apps/web/src/components/Checkout/CheckoutConfirmation.tsx
clients/apps/web/src/hooks/checkout.ts
clients/examples/checkout-embed/index.html
clients/packages/checkout/src/hooks/fulfillment.ts

- clients: improve Checkout resiliency when missing SSE events

clients: improve Checkout resiliency when missing SSE events

---

render.yaml

- ops: use a more powerful plan for production worker

ops: use a more powerful plan for production worker

---

docs/changelog/api.mdx
docs/changelog/recent.mdx
docs/features/checkout/session.mdx

- docs: external_customer_id change and benefit metadata in customer state

docs: external_customer_id change and benefit metadata in customer state

---

server/polar/worker/__init__.py

- server/worker: preserve actor functions signatures

server/worker: preserve actor functions signatures

---

server/polar/notifications/tasks/email.py

- server/notifications: disable email

server/notifications: disable email

---

server/polar/notifications/notification.py
server/polar/notifications/tasks/email.py
server/tests/notifications/test_email.py
server/tests/notifications/testdata/test_MaintainerNewPaidSubscriptionNotification.html
server/tests/notifications/testdata/test_MaintainerNewProductSaleNotification.html

- server/notification: fix email renderer that was exposed to SSTI

server/notification: fix email renderer that was exposed to SSTI

---

server/polar/notifications/notification.py

- server/notifications: fix formatted_price_amount computed field

server/notifications: fix formatted_price_amount computed field

---

docs/integrate/sdk/adapters/better-auth.mdx

Lot of details went into this (as follows):
- Linking the top level TOC to each section
- Multiple packages installation setup (beyond pnpm)
- Improved heading for "Preparation"
- Step level walkthrough for "Preparation" for improved hierarchy (configuration option are only part of the server setup step now) and guidance to the developers as a flow of steps
- Each plugin options are now documented inside the plugin itself - developers/readers don't need to check the source code anymore
- Introduce number in the headings where the plugin/section had subsections in it (it was hard for me to follow the hierarchy otherwise)
- Linking to the source code for each plugin
- Indicator on top of code block as to what's happening in that code block
- Line level highlight in the code block to show …

docs: Improve Polar's BetterAuth plugin documentation

---

server/polar/payment_method/service.py

- server/payment_method: fix eager loading

server/payment_method: fix eager loading

---

server/polar/subscription/service.py
server/tests/subscription/test_service.py

- server/subscription: fix custom price not applying automatic tax

server/subscription: fix custom price not applying automatic tax

---

server/scripts/payment_methods_import.py

- server/scripts: fix payment methods import script by handling conflicts

server/scripts: fix payment methods import script by handling conflicts

---

server/polar/payment_method/repository.py
server/polar/payment_method/service.py
server/tests/payment_method/test_service.py

- server/payment_method: fix issue when the same payment method exists for different customers

server/payment_method: fix issue when the same payment method exists for different customers

---

docs/docs.json
docs/package.json
docs/pnpm-lock.yaml

- docs: make LLM-friendly content more prominent

docs: make LLM-friendly content more prominent

---

pyrightconfig.json

- dx: remove pyrightconfig.json that's no longer necessary to make Zed working

dx: remove pyrightconfig.json that's no longer necessary to make Zed working

---

server/polar/integrations/stripe/service.py

- server/integrations/stripe: don't attempt to finalize OOB invoice if not in draft state

server/integrations/stripe: don't attempt to finalize OOB invoice if not in draft state

---

clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx

only render metered price if meters exist

---

server/polar/checkout/service.py
server/polar/models/organization.py
server/polar/order/service.py

- server: prevent non-ascii chars in payments statement descriptors

server: prevent non-ascii chars in payments statement descriptors

---

clients/packages/checkout/src/components/CheckoutForm.tsx

- clients/packages/checkout: remove discount code from confirm payload if empty

clients/packages/checkout: remove discount code from confirm payload if empty

---

docs/integrate/sdk/adapters/astro.mdx
docs/integrate/sdk/adapters/better-auth.mdx
docs/integrate/sdk/adapters/deno.mdx
docs/integrate/sdk/adapters/elysia.mdx
docs/integrate/sdk/adapters/express.mdx
docs/integrate/sdk/adapters/fastify.mdx
docs/integrate/sdk/adapters/hono.mdx
docs/integrate/sdk/adapters/nextjs.mdx
docs/integrate/sdk/adapters/nuxt.mdx
docs/integrate/sdk/adapters/remix.mdx
docs/integrate/sdk/adapters/sveltekit.mdx
docs/integrate/sdk/adapters/tanstack-start.mdx

- **docs: fix customer state webhook description**

webhooks docs

---

docs/features/usage-based-billing/introduction.mdx

Avoid scaring customers away with a warning about alpha, but highlight that it is a new feature with a lot of enhancements to come and that we welcome feedback.

docs: Clarify Usage Based Billing stage

---

server/polar/order/service.py
server/tests/order/test_service.py

- server/order: handle case where Stripe order is already marked as paid in handle_payment

server/order: handle case where Stripe order is already marked as paid in handle_payment

---

server/polar/processor_transaction/repository.py
server/polar/processor_transaction/service.py
server/polar/processor_transaction/tasks.py
server/polar/tasks.py

- server/processor_transaction: add cron task to sync Stripe balance transactions

server/processor_transaction: add cron task to sync Stripe balance transactions

---

server/polar/transaction/service/processor_fee.py

- server/transaction: add yet another missing stripe fee type

server/transaction: add yet another missing stripe fee type

---

clients/apps/web/src/app/(main)/login/code/verify/ClientPage.tsx
clients/apps/web/src/app/(main)/login/code/verify/page.tsx

The `return_to` parameter was not working as it was being passed as `returnTo`.
Also there were some auto-formatting fixes.

Login code: Fix `return_to`

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/layout.tsx
clients/apps/web/src/app/(main)/dashboard/account/layout.tsx

- **clients: default sidebar to open state**
- **clients: default sidebar to open state**

Default sidebar to open state

---

clients/apps/web/src/components/Settings/OAuth/OAuthForm.tsx
clients/apps/web/src/components/Settings/OrganizationAccessTokensSettings.tsx

Hi!
I've added the implementation for https://github.com/polarsource/polar/issues/5208. Let me know if I need to make any other changes!

Sort scopes alphabetically

---

server/polar/account/service.py
server/polar/web_backoffice/forms.py
server/polar/web_backoffice/organizations/endpoints.py
server/polar/web_backoffice/organizations/forms.py

Added new form `Update Organization` to update organization name and slug
Added a way to "Deny" it and change it to "Under Review" too.

server/web_backoffice: able to change name/slug and status of an organization

---

clients/apps/web/src/components/Meter/MeterFilterInput.tsx

- Closes https://github.com/polarsource/polar/issues/6014
**Current Behavior**
**After Fix**

Fixes alignment issue for filter field on create meter page

---

server/polar/web_backoffice/dependencies.py
server/pyproject.toml
server/scripts/seeds_load.py

Can be run as `uv run task seeds_load`
This task creates 3 organizations with products, benefits, and
customers.

Add `seeds_load` server task

---

server/polar/transaction/service/payout.py

- server/transaction: make payout transfers more robust

server/transaction: make payout transfers more robust

---

server/polar/processor_transaction/tasks.py

- server/processor_transaction: run Stripe sync every hour

server/processor_transaction: run Stripe sync every hour

---

.github/workflows/link_pr_to_issue.yaml

- dx: add action to link PR named after Linear branch with GitHub issue

dx: add action to link PR named after Linear branch with GitHub issue

---

.github/workflows/link_pr_to_issue.yaml

- dx: fix link_pr_to_issue branch trigger

dx: fix link_pr_to_issue branch trigger

---

clients/apps/web/src/components/Products/ProductSelect.tsx

feat: enhance product selection with "select all" functionality

---

.github/workflows/test_client.yaml
.github/workflows/test_server.yaml

- dx: fix syntax error in CI following automatic Copilot fix

dx: fix syntax error in CI following automatic Copilot fix

---

server/polar/models/discount.py
server/polar/order/service.py
server/polar/subscription/service.py
server/tests/order/test_service.py
server/tests/subscription/test_service.py

Handle discounts in new billing engine

---

server/polar/subscription/endpoints.py

Fix #6221
- server/subscription: fix GET endpoint scope

server/subscription: fix GET endpoint scope

---

server/polar/order/service.py

- server/order: ignore tax transaction error to unblock an order

server/order: ignore tax transaction error to unblock an order

---

server/polar/email/react.py
server/polar/oauth2/service/oauth2_client.py
server/polar/oauth2/service/oauth2_token.py
server/polar/organization_access_token/service.py
server/polar/personal_access_token/service.py
server/polar/subscription/service.py

- Emails: Add more strict typing for email properties
- Emails: Fix benefits property on subscription emails

Emails: Fix `benefit.description` and add better typing

---

server/polar/order/service.py

- Revert "server/order: ignore tax transaction error to unblock an order"

Revert "server/order: ignore tax transaction error to unblock an order"

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/members/ClientPage.tsx
server/emails/src/emails/organization_invite.tsx
server/polar/organization/endpoints.py
server/tests/organization/test_endpoints.py

- **Organization members: Better handling of already invited members**
- **Organization invite: Better match invite email copy to behavior**

Org members: Improve invite behavior and email copy

---

server/polar/config.py
server/polar/kit/db/postgres.py
server/polar/postgres.py

- server: set timeouts to database queries

server: set timeouts to database queries

---

clients/apps/web/src/components/Onboarding/OrganizationStep.tsx

- Added clear prohibited products
- Mentioned that social and website verificcation may be required
- Mentioned that transactions will be canceled and refunded

refactor(organization): update product restrictions information for clarity

---

server/tests/fixtures/random_objects.py

Previously, the subscription fixture would always have a cycle of 30
days (and never e.g. 31, 28 or 29 days).

test(create_subscription): Fix cycle dates

---

server/polar/auth/dependencies.py
server/polar/auth/models.py
server/polar/logfire.py

- server/auth: add log to catch authenticated subject on each request

server/auth: add log to catch authenticated subject on each request

---

server/polar/rate_limit.py

- server/rate_limit: enable stricter rate limit rules

server/rate_limit: enable stricter rate limit rules

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/finance/account/ClientPage.tsx
clients/apps/web/src/components/Finance/StreamlinedAccountReview.tsx

refactor: improve step initialization logic and type for organization

---

clients/packages/client/src/v1.ts
server/polar/embed/schemas.py

server/embed: return public benefits schema

---

clients/apps/web/src/components/Meter/MeterForm.tsx
clients/packages/client/src/enums.ts
clients/packages/client/src/v1.ts
docs/features/custom-fields.mdx
docs/features/usage-based-billing/meters.mdx
server/polar/meter/aggregation.py
server/tests/meter/test_aggregation.py

Fix #6440
- clients/web: add unique aggregation support to meter creation
- server/meter: add support for unique aggregation function

Meters: add support for unique aggregation function

---

clients/apps/web/src/components/Benefit/CreateBenefitModalContent.tsx
clients/apps/web/src/components/Benefit/GitHubRepositoryBenefitForm.tsx

clients/web: tweak benefit form validation

---

clients/apps/web/src/app/(main)/(landing)/resources/pricing/page.tsx
clients/apps/web/src/components/Benefit/MeterCredit/BenefitForm.tsx
clients/apps/web/src/components/Landing/LandingLayout.tsx
clients/apps/web/src/components/Landing/Pricing.tsx
clients/apps/web/src/components/Landing/resources/PricingPage.tsx
clients/apps/web/src/components/Landing/resources/ResourceLayout.tsx
clients/apps/web/src/components/Landing/resources/WhyPolarPage.tsx
clients/apps/web/src/components/Onboarding/IntegrateStep.tsx
clients/apps/web/src/components/Onboarding/OrganizationStep.tsx
clients/apps/web/src/components/Onboarding/ProductStep.tsx
clients/apps/web/src/components/Organization/Footer.tsx
clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx

- **add pricing resource**
- **add resources**

Add resources entry in nav

---

server/polar/organization/service.py
server/polar/refund/endpoints.py

removed log = structlog.get_logger where it was not used.

removed unused logger variables

---

server/polar/checkout/repository.py
server/polar/checkout/service.py
server/polar/models/checkout.py
server/tests/checkout/test_endpoints.py

- server/checkout: tidy up eager loading

server/checkout: tidy up eager loading

---

server/polar/kit/math.py
server/polar/models/account.py
server/polar/models/discount.py
server/polar/models/product_price.py
server/tests/kit/test_math.py

This is a pattern we use in couple of places, so just generalizing it here.

Add `polar_round()`: A rounding function rounding 0.5 away from 0

---

docs/integrate/sdk/adapters/tanstack-start.mdx

Docs show the old way. New way as documented in https://tanstack.com/start/latest/docs/framework/solid/server-routes#defining-a-server-route.

docs: Update TanStack Start guide to match the latest steps

---

.github/actions/maintenance-mode/action.yml
.github/workflows/disable_maintenance_mode.yml
.github/workflows/enable_maintenance_mode.yml

- ci: fix maintenance mode workflow
- ci: add maintenance mode workflow

ci: fix maintenance mode workflow

---

server/polar/integrations/plain/service.py

- server/integrations/plain: add customer portal URL to order card

server/integrations/plain: add customer portal URL to order card

---

server/polar/organization/service.py
server/polar/web_backoffice/components/account_review/_ai_review.py

feat(organization): approve/reject pending appeals during organization review

---

.github/workflows/build_server.yaml
.github/workflows/deploy_server.sh

This is how it will look like:

feat: use staged deploying

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/usage-billing/meters/ClientPage.tsx
clients/apps/web/src/components/Benefit/MeterCredit/BenefitForm.tsx
clients/apps/web/src/components/Meter/MeterSelect.tsx
clients/apps/web/src/components/Products/ProductForm/ProductPricingSection.tsx
clients/apps/web/src/components/Products/ProductPage/ProductPage.tsx
clients/apps/web/src/utils/api/errors.ts
clients/packages/client/src/v1.ts

- Adds a dropdown on the individual Meter (top-right of page) that allows archiving and unarchiving
- Adds a filter on the Meter list to filter on archived / not archived
- Adds the ability to unarchive Products

Add ability to archive meters in UI

---

clients/apps/web/src/components/Benefit/BenefitGrant.tsx
clients/packages/client/src/v1.ts
server/migrations/versions/2025-09-04-1028_update_github_benefit_grant_properties.py
server/polar/benefit/strategies/discord/properties.py
server/polar/benefit/strategies/discord/service.py
server/polar/benefit/strategies/github_repository/properties.py
server/polar/benefit/strategies/github_repository/service.py
server/polar/customer_portal/schemas/benefit_grant.py
server/polar/customer_portal/service/benefit_grant.py

- clients/web: allow to change GitHub/Discord account in benefit grant
- server/benefits: allow to change GitHub/Discord account

clients/web: allow to change GitHub/Discord account in benefit grant

---

.github/workflows/copilot-setup-steps.yml

- ops: add Copilot setup steps

ops: add Copilot setup steps

---

.github/workflows/copilot-setup-steps.yml

- ops: tweak GitHub Copilot setup

ops: tweak GitHub Copilot setup

---

.github/copilot-instructions.md

- ai: tweak Copilot instructions
- ops: tweak GitHub Copilot setup

ai: tweak Copilot instructions

---

.github/workflows/deploy-environment.yml
.github/workflows/deploy.yml
.github/workflows/deploy_server.sh
clients/apps/web/vercel.json

ops: revamp deploy workflow

---

.github/workflows/deploy-environment.yml

- ops: make Vercel build on their own infra, not locally

ops: make Vercel build on their own infra, not locally

---

.github/workflows/deploy-environment.yml

- ops: fix Vercel deploy working dir

ops: fix Vercel deploy working dir

---

.github/workflows/deploy-environment.yml
.github/workflows/deploy.yml

- ops: add deploy filters and fix Vercel promote

ops: add deploy filters and fix Vercel promote

---

.github/workflows/test_client.yaml
.github/workflows/test_server.yaml

- ops: fix PR trigger events on test server/client CI

ops: fix PR trigger events on test server/client CI

---

render.yaml

- ops: enable new billing engine on new organizations

ops: enable new billing engine on new organizations

---

server/polar/benefit/repository.py
server/polar/benefit/service.py
server/polar/benefit/sorting.py
server/polar/models/benefit.py
server/polar/web_backoffice/__init__.py
server/polar/web_backoffice/benefits/endpoints.py
server/polar/web_backoffice/navigation.py

- server/backoffice: add benefit endpoints

server/backoffice: add benefit endpoints

---

server/polar/webhook/tasks.py

- server/webhook: temp cut archive task

server/webhook: temp cut archive task

---

server/polar/webhook/service.py
server/polar/webhook/tasks.py

- server/webhook: revamp archive task to execute in batches

server/webhook: revamp archive task to execute in batches

---

clients/packages/client/src/v1.ts
server/polar/benefit/schemas.py

Fix BenefitGrant webhook schema

---

clients/apps/web/src/app/(main)/verify-email/page.tsx
clients/apps/web/src/components/Settings/AuthenticationSettings.tsx
server/polar/email_update/service.py

Fix #6829
- clients/web: fix email update submission
- server/email_update: add missing session.add

clients/web: fix email update submission

---

clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/webhooks/ClientPage.tsx
clients/apps/web/src/app/(main)/dashboard/[organization]/(header)/settings/webhooks/endpoints/[id]/ClientPage.tsx
clients/apps/web/src/components/Metrics/DateRangePicker.tsx
clients/apps/web/src/components/Settings/Webhook/WebhookDeliveriesTable.tsx
clients/apps/web/src/components/Settings/Webhook/WebhookFilter.tsx
clients/apps/web/src/components/Settings/Webhook/WebhookSettings.tsx
clients/apps/web/src/hooks/queries/webhooks.ts
clients/packages/client/src/v1.ts
server/polar/webhook/endpoints.py
server/polar/webhook/service.py

Fixes #6560
Adds support for filtering webhooks by a custom date range or a specific date,

Add date and date-range filters for webhooks 

---

server/uv.lock

server: update uv.lock 🤦‍♂️

---

clients/packages/checkout/src/components/CheckoutForm.tsx

Fixes #6823 
I had an earlier iteration that repeated the full price (e.g. "for the first 3 months, $20 / mo after that", but it felt duplicate since it just repeats the subtotal amount from two lines above, so I think this is cleaner.

Show discount period as part of checkout flow

---

clients/apps/web/package.json
clients/apps/web/src/components/Accounts/AccountCreateModal.tsx
clients/apps/web/src/components/Checkout/DummyCheckoutContextProvider.tsx
clients/apps/web/src/components/CustomerPortal/EditBillingDetails.tsx
clients/apps/web/src/components/Orders/DownloadInvoice.tsx
clients/apps/web/src/components/Payouts/DownloadInvoice.tsx
clients/apps/web/src/components/Payouts/useInvoiceDownload.ts
clients/apps/web/src/utils/config.ts
clients/examples/checkout-components/package.json
clients/packages/checkout/package.json
clients/packages/checkout/src/components/CheckoutForm.tsx
clients/packages/checkout/src/providers/CheckoutFormProvider.tsx
clients/packages/client/src/enums.ts
clients/packages/client/src/v1.ts
clients/packages/ui/src/components/atoms/CountryPicker.tsx
clients/pnpm-lock.yaml

- clients: revamp CountryPicker so it takes a list of countries from SDK

clients: revamp CountryPicker so it takes a list of countries from SDK

---

server/polar/webhook/service.py

- server/webhook: make on_event_success more resilient to webhook payload changes

server/webhook: make on_event_success more resilient to webhook payload changes

---

server/scripts/fix_migrated_subscription.py

- server/scripts: make the migration fix script more resilient

server/scripts: make the migration fix script more resilient

---

server/polar/subscription/tasks.py
server/scripts/fix_migrated_subscription.py

- server/scripts: reintroduce subscriptions migrations fix

server/scripts: reintroduce subscriptions migrations fix

---

server/polar/subscription/service.py

- server/subscriptions: make sure to not set legacy_stripe_subscription_id if not ready

server/subscriptions: make sure to not set legacy_stripe_subscription_id if not ready

---

clients/apps/web/src/app/(main)/[organization]/(header)/layout.tsx
clients/apps/web/src/app/(main)/login/page.tsx
clients/apps/web/src/components/Customization/Storefront/StorefrontPreview.tsx
clients/apps/web/src/components/Landing/LandingLayout.tsx
clients/apps/web/src/components/Layout/Dashboard/DashboardSidebar.tsx
clients/apps/web/src/components/Layout/Public/PolarLogotype.tsx
clients/apps/web/src/components/Layout/Public/Topbar.tsx
clients/apps/web/src/components/Organization/Footer.tsx

- **branding: rename the Logotype component**
- **landing: adjust footer width for consistency**

Landing Page polish

---

clients/apps/web/src/components/Metrics/CancellationsStackedChart.tsx
clients/apps/web/src/components/Metrics/MetricChart.tsx
clients/packages/ui/package.json
clients/packages/ui/src/components/ui/chart.tsx
clients/pnpm-lock.yaml

Upgrade Recharts to v3

---

clients/apps/web/src/app/(main)/signup/page.tsx

**Related Issue**: Fixes #7096
Happy to make my first (small) contribution to Polar!
Sets `h-screen` so the signup page fits the full height
1.
2.
3.
Before:
After:

fix: issue 7096 - signup page styling

---

render.yaml

- ops: fix cors origins and allowed hosts

ops: fix cors origins and allowed hosts

---

server/polar/checkout/service.py

Fix #7121
- server/checkout: reload full checkout object after acquiring lock

server/checkout: reload full checkout object after acquiring lock

---

clients/apps/web/src/components/Checkout/CheckoutBenefits.tsx
server/polar/customer_seat/service.py
server/polar/models/product.py
server/polar/subscription/service.py
server/tests/customer_seat/test_service.py
server/tests/fixtures/random_objects.py
server/tests/product/test_service.py
server/tests/subscription/test_service.py

feat: do not grant benefits to billing manager for seat-based pricing

---

clients/apps/web/vercel.json

Wildcard path for Mintlify API requests

---

server/polar/customer_meter/service.py
server/polar/customer_meter/tasks.py

- server/customer_meter: hotfix task to raise early and don't retry

server/customer_meter: hotfix task to raise early and don't retry

---

server/polar/subscription/service.py
server/tests/subscription/test_service.py

Fix #7168
- server/subscription: don't send cycle email on subscription end

server/subscription: don't send cycle email on subscription end

---

docs/docs.json

docs: add GA4
